Imports System.Diagnostics
Imports Microsoft.VisualBasic
<CompilerServices.DesignerGenerated()>
Partial Class Form1
    Inherits Form

    'Form overrides dispose to clean up the component list.
    <DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(disposing As Boolean)
        Try
            If disposing Then
                If components IsNot Nothing Then
                    components.Dispose()
                End If
                If _cancellationTokenSource IsNot Nothing Then
                    _cancellationTokenSource.Dispose()
                End If
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
        Me.MenuFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileOpen = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileLoadLastSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileSaveSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuFileSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuFileLabelLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileSep3 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuFileConvertProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileLastProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileLastSolution = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileSaveAs = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuFileSep4 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuFileExit = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEdit = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditFind = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuEditUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuEditCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuEditSelectAll = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuCompile = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuConvert = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuConvertConvertFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuConvertConvertSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuConvertConvertTopLevelStmts = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuConvertSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuConvertStartFolderConvertFromLastFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptions = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsColorizeResult = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsColorizeSource = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsDelayBetweenConversions = New System.Windows.Forms.ToolStripComboBox()
        Me.MenuOptionsSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsEditIgnoreFilesWithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuOptionsFolderConversionsOptions = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsPauseConvertOnSuccess = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsSep3 = New System.Windows.Forms.ToolStripSeparator()
        Me.MenuOptionsDefaultFramework = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsDefaultFrameworkCore = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsDefaultFrameworkFullAnyCore = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsDefaultFrameworkFull = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsDefaultFrameworkFullAnyFull = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuOptionsAdvanced = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuView = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuViewShowSourceLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuViewShowDestinationLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuHelp = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuHelpReportIssueMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuHelpCheckForUpdatesMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.MenuHelpAboutMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.TSFindToolStrip = New System.Windows.Forms.ToolStrip()
        Me.TSFindFindWhatComboBox = New System.Windows.Forms.ToolStripComboBox()
        Me.TSFindSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindLookInLabel = New System.Windows.Forms.ToolStripLabel()
        Me.TSFindLookInComboBox = New System.Windows.Forms.ToolStripComboBox()
        Me.TSFindSeparator2 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindFindPreviousButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindFindNextButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindSeparator3 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindMatchCaseCheckBox = New CSharpToVBApp.ToolStripCheckBox()
        Me.TSFindMatchWholeWordCheckBox = New CSharpToVBApp.ToolStripCheckBox()
        Me.TSFindSeparator4 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindClearHighlightsButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindSeparator5 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSThemeButton = New System.Windows.Forms.ToolStripButton()
        Me.SaveFileDialog1 = New System.Windows.Forms.SaveFileDialog()
        Me.ContextMenuStrip1 = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.ContextMenuUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.ContextMenuCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuSelectAll = New System.Windows.Forms.ToolStripMenuItem()
        Me.InputFolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog()
        Me.ButtonStopConversion = New System.Windows.Forms.Button()
        Me.LabelErrorCount = New System.Windows.Forms.Label()
        Me.SplitContainer1 = New System.Windows.Forms.SplitContainer()
        Me.ConversionInputPanelEx = New CSharpToVBApp.PanelEx()
        Me.ConversionInput = New System.Windows.Forms.RichTextBox()
        Me.LineNumbersForConversionInput = New CSharpToVBApp.LineNumbersForRichTextBox()
        Me.ConversionOutputPanelEx = New CSharpToVBApp.PanelEx()
        Me.ConversionOutput = New System.Windows.Forms.RichTextBox()
        Me.LineNumbersForConversionOutput = New CSharpToVBApp.LineNumbersForRichTextBox()
        Me.FileListPanelEx = New CSharpToVBApp.PanelEx()
        Me.FileListListBox = New System.Windows.Forms.ListBox()
        Me.ErrorListPanelEx = New CSharpToVBApp.PanelEx()
        Me.ErrorListListBox = New System.Windows.Forms.ListBox()
        Me.StatusStrip1 = New System.Windows.Forms.StatusStrip()
        Me.StatusStripElapasedTimeLabel = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripCurrentFileName = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripSpacer = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripConversionProgressBar = New CSharpToVBApp.ToolStripTextProgressBar()
        Me.StatusStripConversionFileProgressLabel = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripUpdateAvailable = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripUpdateNotAvailable = New System.Windows.Forms.ToolStripStatusLabel()
        Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
        Me.ProjectConversionInitProgressBar = New System.Windows.Forms.ProgressBar()
        Me.ProjectConversionInitProgressLabel = New System.Windows.Forms.Label()
        Me.ToolTipFileList = New System.Windows.Forms.ToolTip(Me.components)
        Me.ToolTipErrorList = New System.Windows.Forms.ToolTip(Me.components)
        Me.MenuStrip1.SuspendLayout()
        Me.TSFindToolStrip.SuspendLayout()
        Me.ContextMenuStrip1.SuspendLayout()
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        Me.ConversionInputPanelEx.SuspendLayout()
        Me.ConversionOutputPanelEx.SuspendLayout()
        Me.FileListPanelEx.SuspendLayout()
        Me.ErrorListPanelEx.SuspendLayout()
        Me.StatusStrip1.SuspendLayout()
        Me.SuspendLayout()
        '
        'MenuStrip1
        '
        Me.MenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuFile, Me.MenuEdit, Me.MenuCompile, Me.MenuConvert, Me.MenuOptions, Me.MenuView, Me.MenuHelp})
        Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Padding = New System.Windows.Forms.Padding(7, 2, 0, 2)
        Me.MenuStrip1.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional
        Me.MenuStrip1.Size = New System.Drawing.Size(1923, 24)
        Me.MenuStrip1.TabIndex = 0
        '
        'MenuFile
        '
        Me.MenuFile.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuFileOpen, Me.MenuFileLoadLastSnippet, Me.MenuFileSaveSnippet, Me.MenuFileSep1, Me.MenuFileSep2, Me.MenuFileLabelLastFolder, Me.MenuFileLastFolder, Me.MenuFileSep3, Me.MenuFileConvertProject, Me.MenuFileLastProject, Me.MenuFileLastSolution, Me.MenuFileSaveAs, Me.MenuFileSep4, Me.MenuFileExit})
        Me.MenuFile.Name = "MenuFile"
        Me.MenuFile.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.MenuFile.Size = New System.Drawing.Size(37, 20)
        Me.MenuFile.Text = "&File"
        '
        'MenuFileOpen
        '
        Me.MenuFileOpen.Image = Global.CSharpToVBApp.My.Resources.Resources.OpenFile
        Me.MenuFileOpen.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileOpen.Name = "MenuFileOpen"
        Me.MenuFileOpen.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.MenuFileOpen.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileOpen.Text = "Open C# File..."
        '
        'MenuFileLoadLastSnippet
        '
        Me.MenuFileLoadLastSnippet.Enabled = False
        Me.MenuFileLoadLastSnippet.Image = Global.CSharpToVBApp.My.Resources.Resources.Snippet
        Me.MenuFileLoadLastSnippet.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileLoadLastSnippet.Name = "MenuFileLoadLastSnippet"
        Me.MenuFileLoadLastSnippet.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileLoadLastSnippet.Text = "Load Last Snippet"
        '
        'MenuFileSaveSnippet
        '
        Me.MenuFileSaveSnippet.Enabled = False
        Me.MenuFileSaveSnippet.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileSaveSnippet.Name = "MenuFileSaveSnippet"
        Me.MenuFileSaveSnippet.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileSaveSnippet.Text = "Save Snippet"
        '
        'MenuFileSep1
        '
        Me.MenuFileSep1.Name = "MenuFileSep1"
        Me.MenuFileSep1.Size = New System.Drawing.Size(286, 6)
        '
        'MenuFileSep2
        '
        Me.MenuFileSep2.Name = "MenuFileSep2"
        Me.MenuFileSep2.Size = New System.Drawing.Size(286, 6)
        '
        'MenuFileLabelLastFolder
        '
        Me.MenuFileLabelLastFolder.Enabled = False
        Me.MenuFileLabelLastFolder.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileLabelLastFolder.Name = "MenuFileLabelLastFolder"
        Me.MenuFileLabelLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileLabelLastFolder.Text = "Last Converted Folder"
        '
        'MenuFileLastFolder
        '
        Me.MenuFileLastFolder.Name = "MenuFileLastFolder"
        Me.MenuFileLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileLastFolder.Visible = False
        '
        'MenuFileSep3
        '
        Me.MenuFileSep3.Name = "MenuFileSep3"
        Me.MenuFileSep3.Size = New System.Drawing.Size(286, 6)
        '
        'MenuFileConvertProject
        '
        Me.MenuFileConvertProject.Image = Global.CSharpToVBApp.My.Resources.Resources.OpenProjectFolder
        Me.MenuFileConvertProject.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileConvertProject.Name = "MenuFileConvertProject"
        Me.MenuFileConvertProject.ShortcutKeys = CType(((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Shift) _
            Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.MenuFileConvertProject.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileConvertProject.Text = "Convert Project/Solution..."
        '
        'MenuFileLastProject
        '
        Me.MenuFileLastProject.Enabled = False
        Me.MenuFileLastProject.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileLastProject.Name = "MenuFileLastProject"
        Me.MenuFileLastProject.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileLastProject.Text = "Open Last Project"
        '
        'MenuFileLastSolution
        '
        Me.MenuFileLastSolution.Enabled = False
        Me.MenuFileLastSolution.Name = "MenuFileLastSolution"
        Me.MenuFileLastSolution.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileLastSolution.Text = "Open Last Solution"
        '
        'MenuFileSaveAs
        '
        Me.MenuFileSaveAs.Enabled = False
        Me.MenuFileSaveAs.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileSaveAs.Name = "MenuFileSaveAs"
        Me.MenuFileSaveAs.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.MenuFileSaveAs.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileSaveAs.Text = "Save Visual Basic File &As..."
        '
        'MenuFileSep4
        '
        Me.MenuFileSep4.Name = "MenuFileSep4"
        Me.MenuFileSep4.Size = New System.Drawing.Size(286, 6)
        '
        'MenuFileExit
        '
        Me.MenuFileExit.Image = Global.CSharpToVBApp.My.Resources.Resources._Exit
        Me.MenuFileExit.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuFileExit.Name = "MenuFileExit"
        Me.MenuFileExit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.MenuFileExit.Size = New System.Drawing.Size(289, 22)
        Me.MenuFileExit.Text = "E&xit"
        '
        'MenuEdit
        '
        Me.MenuEdit.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuEditFind, Me.MenuEditSep1, Me.MenuEditUndo, Me.MenuEditRedo, Me.MenuEditSep2, Me.MenuEditCut, Me.MenuEditCopy, Me.MenuEditPaste, Me.MenuEditSelectAll})
        Me.MenuEdit.Name = "MenuEdit"
        Me.MenuEdit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.E), System.Windows.Forms.Keys)
        Me.MenuEdit.Size = New System.Drawing.Size(39, 20)
        Me.MenuEdit.Text = "&Edit"
        '
        'MenuEditFind
        '
        Me.MenuEditFind.Image = Global.CSharpToVBApp.My.Resources.Resources.FindNext
        Me.MenuEditFind.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditFind.Name = "MenuEditFind"
        Me.MenuEditFind.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.MenuEditFind.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditFind.Text = "&Find..."
        '
        'MenuEditSep1
        '
        Me.MenuEditSep1.Name = "MenuEditSep1"
        Me.MenuEditSep1.Size = New System.Drawing.Size(161, 6)
        '
        'MenuEditUndo
        '
        Me.MenuEditUndo.Image = Global.CSharpToVBApp.My.Resources.Resources.Undo
        Me.MenuEditUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditUndo.Name = "MenuEditUndo"
        Me.MenuEditUndo.ShortcutKeyDisplayString = "Ctrl+Z"
        Me.MenuEditUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.MenuEditUndo.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditUndo.Text = "Undo"
        '
        'MenuEditRedo
        '
        Me.MenuEditRedo.Image = Global.CSharpToVBApp.My.Resources.Resources.Redo
        Me.MenuEditRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditRedo.Name = "MenuEditRedo"
        Me.MenuEditRedo.ShortcutKeyDisplayString = "Ctrl+Y"
        Me.MenuEditRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.MenuEditRedo.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditRedo.Text = "Redo"
        '
        'MenuEditSep2
        '
        Me.MenuEditSep2.Name = "MenuEditSep2"
        Me.MenuEditSep2.Size = New System.Drawing.Size(161, 6)
        '
        'MenuEditCut
        '
        Me.MenuEditCut.Image = Global.CSharpToVBApp.My.Resources.Resources.Cut
        Me.MenuEditCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditCut.Name = "MenuEditCut"
        Me.MenuEditCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.MenuEditCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.MenuEditCut.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditCut.Text = "Cut"
        '
        'MenuEditCopy
        '
        Me.MenuEditCopy.Image = Global.CSharpToVBApp.My.Resources.Resources.Copy
        Me.MenuEditCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditCopy.Name = "MenuEditCopy"
        Me.MenuEditCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.MenuEditCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.MenuEditCopy.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditCopy.Text = "Copy"
        '
        'MenuEditPaste
        '
        Me.MenuEditPaste.Image = Global.CSharpToVBApp.My.Resources.Resources.Paste
        Me.MenuEditPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditPaste.Name = "MenuEditPaste"
        Me.MenuEditPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.MenuEditPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.MenuEditPaste.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditPaste.Text = "Paste"
        '
        'MenuEditSelectAll
        '
        Me.MenuEditSelectAll.Image = Global.CSharpToVBApp.My.Resources.Resources.SelectAll
        Me.MenuEditSelectAll.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuEditSelectAll.Name = "MenuEditSelectAll"
        Me.MenuEditSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.MenuEditSelectAll.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.MenuEditSelectAll.Size = New System.Drawing.Size(164, 22)
        Me.MenuEditSelectAll.Text = "Select All"
        '
        'MenuCompile
        '
        Me.MenuCompile.Enabled = False
        Me.MenuCompile.Name = "MenuCompile"
        Me.MenuCompile.Size = New System.Drawing.Size(64, 20)
        Me.MenuCompile.Text = "Compile"
        '
        'MenuConvert
        '
        Me.MenuConvert.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuConvertConvertFolder, Me.MenuConvertConvertSnippet, Me.MenuConvertConvertTopLevelStmts, Me.MenuConvertSep1, Me.MenuConvertStartFolderConvertFromLastFile})
        Me.MenuConvert.Name = "MenuConvert"
        Me.MenuConvert.Size = New System.Drawing.Size(61, 20)
        Me.MenuConvert.Text = "Convert"
        '
        'MenuConvertConvertFolder
        '
        Me.MenuConvertConvertFolder.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuConvertConvertFolder.Name = "MenuConvertConvertFolder"
        Me.MenuConvertConvertFolder.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.MenuConvertConvertFolder.Size = New System.Drawing.Size(237, 22)
        Me.MenuConvertConvertFolder.Text = "Convert Folder"
        '
        'MenuConvertConvertSnippet
        '
        Me.MenuConvertConvertSnippet.Enabled = False
        Me.MenuConvertConvertSnippet.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuConvertConvertSnippet.Name = "MenuConvertConvertSnippet"
        Me.MenuConvertConvertSnippet.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.S), System.Windows.Forms.Keys)
        Me.MenuConvertConvertSnippet.Size = New System.Drawing.Size(237, 22)
        Me.MenuConvertConvertSnippet.Text = "Convert Snippet"
        '
        'MenuConvertConvertTopLevelStmts
        '
        Me.MenuConvertConvertTopLevelStmts.Enabled = False
        Me.MenuConvertConvertTopLevelStmts.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuConvertConvertTopLevelStmts.Name = "MenuConvertConvertTopLevelStmts"
        Me.MenuConvertConvertTopLevelStmts.Size = New System.Drawing.Size(237, 22)
        Me.MenuConvertConvertTopLevelStmts.Text = "Convert Top Level Statements"
        '
        'MenuConvertSep1
        '
        Me.MenuConvertSep1.Name = "MenuConvertSep1"
        Me.MenuConvertSep1.Size = New System.Drawing.Size(234, 6)
        '
        'MenuConvertStartFolderConvertFromLastFile
        '
        Me.MenuConvertStartFolderConvertFromLastFile.Checked = True
        Me.MenuConvertStartFolderConvertFromLastFile.CheckOnClick = True
        Me.MenuConvertStartFolderConvertFromLastFile.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuConvertStartFolderConvertFromLastFile.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuConvertStartFolderConvertFromLastFile.Name = "MenuConvertStartFolderConvertFromLastFile"
        Me.MenuConvertStartFolderConvertFromLastFile.Size = New System.Drawing.Size(237, 22)
        Me.MenuConvertStartFolderConvertFromLastFile.Text = "Start Conversion From Last File"
        '
        'MenuOptions
        '
        Me.MenuOptions.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuOptionsColorizeResult, Me.MenuOptionsColorizeSource, Me.MenuOptionsDelayBetweenConversions, Me.MenuOptionsSep1, Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList, Me.MenuOptionsEditIgnoreFilesWithErrorsList, Me.MenuOptionsSep2, Me.MenuOptionsFolderConversionsOptions, Me.MenuOptionsPauseConvertOnSuccess, Me.MenuOptionsSep3, Me.MenuOptionsDefaultFramework, Me.MenuOptionsAdvanced})
        Me.MenuOptions.Name = "MenuOptions"
        Me.MenuOptions.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.MenuOptions.Size = New System.Drawing.Size(61, 20)
        Me.MenuOptions.Text = "&Options"
        '
        'MenuOptionsColorizeResult
        '
        Me.MenuOptionsColorizeResult.CheckOnClick = True
        Me.MenuOptionsColorizeResult.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsColorizeResult.Name = "MenuOptionsColorizeResult"
        Me.MenuOptionsColorizeResult.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsColorizeResult.Text = "Colorize Result"
        '
        'MenuOptionsColorizeSource
        '
        Me.MenuOptionsColorizeSource.CheckOnClick = True
        Me.MenuOptionsColorizeSource.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsColorizeSource.Name = "MenuOptionsColorizeSource"
        Me.MenuOptionsColorizeSource.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsColorizeSource.Text = "Colorize Source"
        '
        'MenuOptionsDelayBetweenConversions
        '
        Me.MenuOptionsDelayBetweenConversions.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.MenuOptionsDelayBetweenConversions.Items.AddRange(New Object() {"Delay Between Conversions = None", "Delay Between Conversions = 5 Seconds", "Delay Between Conversions = 10 Seconds"})
        Me.MenuOptionsDelayBetweenConversions.MaxDropDownItems = 3
        Me.MenuOptionsDelayBetweenConversions.Name = "MenuOptionsDelayBetweenConversions"
        Me.MenuOptionsDelayBetweenConversions.Size = New System.Drawing.Size(300, 23)
        '
        'MenuOptionsSep1
        '
        Me.MenuOptionsSep1.Name = "MenuOptionsSep1"
        Me.MenuOptionsSep1.Size = New System.Drawing.Size(357, 6)
        '
        'MenuOptionsAddFilesToIgnoreFilesEithErrorsList
        '
        Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList.Name = "MenuOptionsAddFilesToIgnoreFilesEithErrorsList"
        Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsAddFilesToIgnoreFilesEithErrorsList.Text = "Add File to the ""Ignore files with errors list"""
        '
        'MenuOptionsEditIgnoreFilesWithErrorsList
        '
        Me.MenuOptionsEditIgnoreFilesWithErrorsList.Name = "MenuOptionsEditIgnoreFilesWithErrorsList"
        Me.MenuOptionsEditIgnoreFilesWithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsEditIgnoreFilesWithErrorsList.Text = "Show/Edit the ""Ignore files with errors"" list..."
        '
        'MenuOptionsSep2
        '
        Me.MenuOptionsSep2.Name = "MenuOptionsSep2"
        Me.MenuOptionsSep2.Size = New System.Drawing.Size(357, 6)
        '
        'MenuOptionsFolderConversionsOptions
        '
        Me.MenuOptionsFolderConversionsOptions.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated, Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders, Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles})
        Me.MenuOptionsFolderConversionsOptions.Name = "MenuOptionsFolderConversionsOptions"
        Me.MenuOptionsFolderConversionsOptions.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsFolderConversionsOptions.Text = "Folder Conversions Options"
        '
        'MenuOptionsFolderConversionsOptionsSkipAutoGenerated
        '
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.Checked = True
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckOnClick = True
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.Name = "MenuOptionsFolderConversionsOptionsSkipAutoGenerated"
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.Size = New System.Drawing.Size(202, 22)
        Me.MenuOptionsFolderConversionsOptionsSkipAutoGenerated.Text = "Skip Auto Generated"
        '
        'MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders
        '
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Checked = True
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckOnClick = True
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Name = "MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders"
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Size = New System.Drawing.Size(202, 22)
        Me.MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Text = "Skip Bin and Obj Folders"
        '
        'MenuOptionsFolderConversionsOptionsSkipTestResourceFiles
        '
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.Checked = True
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckOnClick = True
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.Name = "MenuOptionsFolderConversionsOptionsSkipTestResourceFiles"
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.Size = New System.Drawing.Size(202, 22)
        Me.MenuOptionsFolderConversionsOptionsSkipTestResourceFiles.Text = "Skip Test/Resource Files"
        '
        'MenuOptionsPauseConvertOnSuccess
        '
        Me.MenuOptionsPauseConvertOnSuccess.CheckOnClick = True
        Me.MenuOptionsPauseConvertOnSuccess.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsPauseConvertOnSuccess.Name = "MenuOptionsPauseConvertOnSuccess"
        Me.MenuOptionsPauseConvertOnSuccess.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsPauseConvertOnSuccess.Text = "Pause Conversion on Success"
        '
        'MenuOptionsSep3
        '
        Me.MenuOptionsSep3.Name = "MenuOptionsSep3"
        Me.MenuOptionsSep3.Size = New System.Drawing.Size(357, 6)
        '
        'MenuOptionsDefaultFramework
        '
        Me.MenuOptionsDefaultFramework.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuOptionsDefaultFrameworkCore, Me.MenuOptionsDefaultFrameworkFull})
        Me.MenuOptionsDefaultFramework.Name = "MenuOptionsDefaultFramework"
        Me.MenuOptionsDefaultFramework.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsDefaultFramework.Text = "Default Framework For Conversion"
        '
        'MenuOptionsDefaultFrameworkCore
        '
        Me.MenuOptionsDefaultFrameworkCore.Checked = True
        Me.MenuOptionsDefaultFrameworkCore.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuOptionsDefaultFrameworkCore.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuOptionsDefaultFrameworkFullAnyCore})
        Me.MenuOptionsDefaultFrameworkCore.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsDefaultFrameworkCore.Name = "MenuOptionsDefaultFrameworkCore"
        Me.MenuOptionsDefaultFrameworkCore.Size = New System.Drawing.Size(180, 22)
        Me.MenuOptionsDefaultFrameworkCore.Text = ".Net Core"
        '
        'MenuOptionsDefaultFrameworkFullAnyCore
        '
        Me.MenuOptionsDefaultFrameworkFullAnyCore.Checked = True
        Me.MenuOptionsDefaultFrameworkFullAnyCore.CheckOnClick = True
        Me.MenuOptionsDefaultFrameworkFullAnyCore.CheckState = System.Windows.Forms.CheckState.Checked
        Me.MenuOptionsDefaultFrameworkFullAnyCore.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsDefaultFrameworkFullAnyCore.Name = "MenuOptionsDefaultFrameworkFullAnyCore"
        Me.MenuOptionsDefaultFrameworkFullAnyCore.Size = New System.Drawing.Size(146, 22)
        Me.MenuOptionsDefaultFrameworkFullAnyCore.Text = "NETCOREAPP"
        '
        'MenuOptionsDefaultFrameworkFull
        '
        Me.MenuOptionsDefaultFrameworkFull.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuOptionsDefaultFrameworkFullAnyFull})
        Me.MenuOptionsDefaultFrameworkFull.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsDefaultFrameworkFull.Name = "MenuOptionsDefaultFrameworkFull"
        Me.MenuOptionsDefaultFrameworkFull.Size = New System.Drawing.Size(180, 22)
        Me.MenuOptionsDefaultFrameworkFull.Text = ".Net Full Framework"
        '
        'MenuOptionsDefaultFrameworkFullAnyFull
        '
        Me.MenuOptionsDefaultFrameworkFullAnyFull.CheckOnClick = True
        Me.MenuOptionsDefaultFrameworkFullAnyFull.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsDefaultFrameworkFullAnyFull.Name = "MenuOptionsDefaultFrameworkFullAnyFull"
        Me.MenuOptionsDefaultFrameworkFullAnyFull.Size = New System.Drawing.Size(167, 22)
        Me.MenuOptionsDefaultFrameworkFullAnyFull.Text = "NETFRAMEWORK"
        '
        'MenuOptionsAdvanced
        '
        Me.MenuOptionsAdvanced.Image = Global.CSharpToVBApp.My.Resources.Resources.AdvancedView
        Me.MenuOptionsAdvanced.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuOptionsAdvanced.Name = "MenuOptionsAdvanced"
        Me.MenuOptionsAdvanced.Size = New System.Drawing.Size(360, 22)
        Me.MenuOptionsAdvanced.Text = "Advanced Options..."
        '
        'MenuView
        '
        Me.MenuView.CheckOnClick = True
        Me.MenuView.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuViewShowSourceLineNumbers, Me.MenuViewShowDestinationLineNumbers})
        Me.MenuView.Name = "MenuView"
        Me.MenuView.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.MenuView.Size = New System.Drawing.Size(44, 20)
        Me.MenuView.Text = "&View"
        '
        'MenuViewShowSourceLineNumbers
        '
        Me.MenuViewShowSourceLineNumbers.CheckOnClick = True
        Me.MenuViewShowSourceLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuViewShowSourceLineNumbers.Name = "MenuViewShowSourceLineNumbers"
        Me.MenuViewShowSourceLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.MenuViewShowSourceLineNumbers.Text = "Show Source Line Numbers"
        '
        'MenuViewShowDestinationLineNumbers
        '
        Me.MenuViewShowDestinationLineNumbers.CheckOnClick = True
        Me.MenuViewShowDestinationLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuViewShowDestinationLineNumbers.Name = "MenuViewShowDestinationLineNumbers"
        Me.MenuViewShowDestinationLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.MenuViewShowDestinationLineNumbers.Text = "Show Destination Line Numbers"
        '
        'MenuHelp
        '
        Me.MenuHelp.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.MenuHelpReportIssueMenuItem, Me.MenuHelpCheckForUpdatesMenuItem, Me.MenuHelpAboutMenuItem})
        Me.MenuHelp.Name = "MenuHelp"
        Me.MenuHelp.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.H), System.Windows.Forms.Keys)
        Me.MenuHelp.Size = New System.Drawing.Size(44, 20)
        Me.MenuHelp.Text = "&Help"
        '
        'MenuHelpReportIssueMenuItem
        '
        Me.MenuHelpReportIssueMenuItem.Image = Global.CSharpToVBApp.My.Resources.Resources.FeedbackSmile_16x
        Me.MenuHelpReportIssueMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuHelpReportIssueMenuItem.Name = "MenuHelpReportIssueMenuItem"
        Me.MenuHelpReportIssueMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.MenuHelpReportIssueMenuItem.Text = "Report A Problem..."
        '
        'MenuHelpCheckForUpdatesMenuItem
        '
        Me.MenuHelpCheckForUpdatesMenuItem.Name = "MenuHelpCheckForUpdatesMenuItem"
        Me.MenuHelpCheckForUpdatesMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.MenuHelpCheckForUpdatesMenuItem.Text = "Check For Updates"
        '
        'MenuHelpAboutMenuItem
        '
        Me.MenuHelpAboutMenuItem.Image = Global.CSharpToVBApp.My.Resources.Resources.AboutBox
        Me.MenuHelpAboutMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.MenuHelpAboutMenuItem.Name = "MenuHelpAboutMenuItem"
        Me.MenuHelpAboutMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.MenuHelpAboutMenuItem.Text = "About"
        '
        'TSFindToolStrip
        '
        Me.TSFindToolStrip.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSFindFindWhatComboBox, Me.TSFindSeparator1, Me.TSFindLookInLabel, Me.TSFindLookInComboBox, Me.TSFindSeparator2, Me.TSFindFindPreviousButton, Me.TSFindFindNextButton, Me.TSFindSeparator3, Me.TSFindMatchCaseCheckBox, Me.TSFindMatchWholeWordCheckBox, Me.TSFindSeparator4, Me.TSFindClearHighlightsButton, Me.TSFindSeparator5, Me.TSThemeButton})
        Me.TSFindToolStrip.Location = New System.Drawing.Point(0, 24)
        Me.TSFindToolStrip.Name = "TSFindToolStrip"
        Me.TSFindToolStrip.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional
        Me.TSFindToolStrip.Size = New System.Drawing.Size(1923, 25)
        Me.TSFindToolStrip.TabIndex = 2
        Me.TSFindToolStrip.Text = "ToolStrip1"
        '
        'TSFindFindWhatComboBox
        '
        Me.TSFindFindWhatComboBox.AutoSize = False
        Me.TSFindFindWhatComboBox.ForeColor = System.Drawing.SystemColors.GrayText
        Me.TSFindFindWhatComboBox.Name = "TSFindFindWhatComboBox"
        Me.TSFindFindWhatComboBox.Size = New System.Drawing.Size(400, 23)
        Me.TSFindFindWhatComboBox.Text = "Search..."
        '
        'TSFindSeparator1
        '
        Me.TSFindSeparator1.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator1.Name = "TSFindSeparator1"
        Me.TSFindSeparator1.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindLookInLabel
        '
        Me.TSFindLookInLabel.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindLookInLabel.Name = "TSFindLookInLabel"
        Me.TSFindLookInLabel.Size = New System.Drawing.Size(49, 25)
        Me.TSFindLookInLabel.Text = "Look In:"
        '
        'TSFindLookInComboBox
        '
        Me.TSFindLookInComboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
        Me.TSFindLookInComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.TSFindLookInComboBox.Items.AddRange(New Object() {"C# Source", "Visual Basic Output", "Both"})
        Me.TSFindLookInComboBox.MaxDropDownItems = 3
        Me.TSFindLookInComboBox.Name = "TSFindLookInComboBox"
        Me.TSFindLookInComboBox.Size = New System.Drawing.Size(130, 25)
        '
        'TSFindSeparator2
        '
        Me.TSFindSeparator2.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator2.Name = "TSFindSeparator2"
        Me.TSFindSeparator2.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindFindPreviousButton
        '
        Me.TSFindFindPreviousButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindFindPreviousButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindFindPreviousButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindFindPreviousButton.Name = "TSFindFindPreviousButton"
        Me.TSFindFindPreviousButton.Size = New System.Drawing.Size(82, 25)
        Me.TSFindFindPreviousButton.Text = "Find Previous"
        '
        'TSFindFindNextButton
        '
        Me.TSFindFindNextButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindFindNextButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindFindNextButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindFindNextButton.Name = "TSFindFindNextButton"
        Me.TSFindFindNextButton.Size = New System.Drawing.Size(62, 25)
        Me.TSFindFindNextButton.Text = "Find Next"
        '
        'TSFindSeparator3
        '
        Me.TSFindSeparator3.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator3.Name = "TSFindSeparator3"
        Me.TSFindSeparator3.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindMatchCaseCheckBox
        '
        Me.TSFindMatchCaseCheckBox.Checked = False
        Me.TSFindMatchCaseCheckBox.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindMatchCaseCheckBox.Name = "TSFindMatchCaseCheckBox"
        Me.TSFindMatchCaseCheckBox.Size = New System.Drawing.Size(88, 25)
        Me.TSFindMatchCaseCheckBox.Text = "Match Case"
        '
        'TSFindMatchWholeWordCheckBox
        '
        Me.TSFindMatchWholeWordCheckBox.Checked = False
        Me.TSFindMatchWholeWordCheckBox.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindMatchWholeWordCheckBox.Name = "TSFindMatchWholeWordCheckBox"
        Me.TSFindMatchWholeWordCheckBox.Size = New System.Drawing.Size(129, 25)
        Me.TSFindMatchWholeWordCheckBox.Text = "Match Whole Word"
        '
        'TSFindSeparator4
        '
        Me.TSFindSeparator4.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator4.Name = "TSFindSeparator4"
        Me.TSFindSeparator4.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindClearHighlightsButton
        '
        Me.TSFindClearHighlightsButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindClearHighlightsButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindClearHighlightsButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindClearHighlightsButton.Name = "TSFindClearHighlightsButton"
        Me.TSFindClearHighlightsButton.Size = New System.Drawing.Size(96, 25)
        Me.TSFindClearHighlightsButton.Text = "Clear Highlights"
        '
        'TSFindSeparator5
        '
        Me.TSFindSeparator5.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator5.Name = "TSFindSeparator5"
        Me.TSFindSeparator5.Size = New System.Drawing.Size(6, 25)
        '
        'TSThemeButton
        '
        Me.TSThemeButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSThemeButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSThemeButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSThemeButton.Name = "TSThemeButton"
        Me.TSThemeButton.Size = New System.Drawing.Size(72, 25)
        Me.TSThemeButton.Text = "Light Mode"
        '
        'ContextMenuStrip1
        '
        Me.ContextMenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.ContextMenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ContextMenuUndo, Me.ContextMenuRedo, Me.ContextMenuSeparator1, Me.ContextMenuCut, Me.ContextMenuCopy, Me.ContextMenuPaste, Me.ContextMenuSelectAll})
        Me.ContextMenuStrip1.Name = "ContextMenuStrip1"
        Me.ContextMenuStrip1.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional
        Me.ContextMenuStrip1.Size = New System.Drawing.Size(165, 142)
        '
        'ContextMenuUndo
        '
        Me.ContextMenuUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuUndo.Name = "ContextMenuUndo"
        Me.ContextMenuUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.ContextMenuUndo.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuUndo.Text = "Undo"
        '
        'ContextMenuRedo
        '
        Me.ContextMenuRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuRedo.Name = "ContextMenuRedo"
        Me.ContextMenuRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.ContextMenuRedo.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuRedo.Text = "Redo"
        '
        'ContextMenuSeparator1
        '
        Me.ContextMenuSeparator1.Name = "ContextMenuSeparator1"
        Me.ContextMenuSeparator1.Size = New System.Drawing.Size(161, 6)
        '
        'ContextMenuCut
        '
        Me.ContextMenuCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCut.Name = "ContextMenuCut"
        Me.ContextMenuCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.ContextMenuCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.ContextMenuCut.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuCut.Text = "Cut"
        '
        'ContextMenuCopy
        '
        Me.ContextMenuCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCopy.Name = "ContextMenuCopy"
        Me.ContextMenuCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.ContextMenuCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.ContextMenuCopy.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuCopy.Text = "Copy"
        '
        'ContextMenuPaste
        '
        Me.ContextMenuPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuPaste.Name = "ContextMenuPaste"
        Me.ContextMenuPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.ContextMenuPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.ContextMenuPaste.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuPaste.Text = "Paste"
        '
        'ContextMenuSelectAll
        '
        Me.ContextMenuSelectAll.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuSelectAll.Name = "ContextMenuSelectAll"
        Me.ContextMenuSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.ContextMenuSelectAll.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.ContextMenuSelectAll.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuSelectAll.Text = "Select All"
        '
        'InputFolderBrowserDialog1
        '
        Me.InputFolderBrowserDialog1.RootFolder = System.Environment.SpecialFolder.CommonDocuments
        Me.InputFolderBrowserDialog1.ShowNewFolderButton = False
        '
        'ButtonStopConversion
        '
        Me.ButtonStopConversion.Location = New System.Drawing.Point(1250, 0)
        Me.ButtonStopConversion.Name = "ButtonStopConversion"
        Me.ButtonStopConversion.Size = New System.Drawing.Size(110, 23)
        Me.ButtonStopConversion.TabIndex = 5
        Me.ButtonStopConversion.Text = "Stop Conversion"
        Me.ButtonStopConversion.UseVisualStyleBackColor = True
        Me.ButtonStopConversion.Visible = False
        '
        'LabelErrorCount
        '
        Me.LabelErrorCount.AutoSize = True
        Me.LabelErrorCount.Location = New System.Drawing.Point(1463, 4)
        Me.LabelErrorCount.Name = "LabelErrorCount"
        Me.LabelErrorCount.Size = New System.Drawing.Size(101, 15)
        Me.LabelErrorCount.TabIndex = 5
        Me.LabelErrorCount.Text = "Number of Errors:"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.BackColor = System.Drawing.SystemColors.Control
        Me.SplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2
        Me.SplitContainer1.Location = New System.Drawing.Point(0, 49)
        Me.SplitContainer1.Name = "SplitContainer1"
        Me.SplitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionInputPanelEx)
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionOutputPanelEx)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.FileListPanelEx)
        Me.SplitContainer1.Panel2.Controls.Add(Me.ErrorListPanelEx)
        Me.SplitContainer1.Size = New System.Drawing.Size(1923, 751)
        Me.SplitContainer1.SplitterDistance = 710
        Me.SplitContainer1.SplitterWidth = 2
        Me.SplitContainer1.TabIndex = 22
        '
        'ConversionInputPanelEx
        '
        Me.ConversionInputPanelEx.BackColor = System.Drawing.Color.Transparent
        Me.ConversionInputPanelEx.Controls.Add(Me.ConversionInput)
        Me.ConversionInputPanelEx.Controls.Add(Me.LineNumbersForConversionInput)
        Me.ConversionInputPanelEx.Dock = System.Windows.Forms.DockStyle.Left
        Me.ConversionInputPanelEx.Location = New System.Drawing.Point(0, 0)
        Me.ConversionInputPanelEx.Margin = New System.Windows.Forms.Padding(0)
        Me.ConversionInputPanelEx.Name = "ConversionInputPanelEx"
        Me.ConversionInputPanelEx.Padding = New System.Windows.Forms.Padding(1)
        Me.ConversionInputPanelEx.Size = New System.Drawing.Size(950, 710)
        Me.ConversionInputPanelEx.TabIndex = 24
        '
        'ConversionInput
        '
        Me.ConversionInput.BorderStyle = System.Windows.Forms.BorderStyle.None
        Me.ConversionInput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionInput.DetectUrls = False
        Me.ConversionInput.Dock = System.Windows.Forms.DockStyle.Fill
        Me.ConversionInput.Font = New System.Drawing.Font("Consolas", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionInput.Location = New System.Drawing.Point(1, 1)
        Me.ConversionInput.Name = "ConversionInput"
        Me.ConversionInput.Size = New System.Drawing.Size(948, 708)
        Me.ConversionInput.TabIndex = 0
        Me.ConversionInput.Text = ""
        Me.ConversionInput.WordWrap = False
        '
        'LineNumbersForConversionInput
        '
        Me.LineNumbersForConversionInput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionInput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionInput.Location = New System.Drawing.Point(-23, 1)
        Me.LineNumbersForConversionInput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionInput.MarginLinesSide = CSharpToVBApp.LineNumbersForRichTextBox.LineNumberDockSides.Right
        Me.LineNumbersForConversionInput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Name = "LineNumbersForConversionInput"
        Me.LineNumbersForConversionInput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionInput.ParentRichTextBox = Me.ConversionInput
        Me.LineNumbersForConversionInput.Size = New System.Drawing.Size(23, 708)
        Me.LineNumbersForConversionInput.TabIndex = 1
        '
        'ConversionOutputPanelEx
        '
        Me.ConversionOutputPanelEx.BackColor = System.Drawing.Color.Transparent
        Me.ConversionOutputPanelEx.Controls.Add(Me.ConversionOutput)
        Me.ConversionOutputPanelEx.Controls.Add(Me.LineNumbersForConversionOutput)
        Me.ConversionOutputPanelEx.Dock = System.Windows.Forms.DockStyle.Right
        Me.ConversionOutputPanelEx.Location = New System.Drawing.Point(966, 0)
        Me.ConversionOutputPanelEx.Margin = New System.Windows.Forms.Padding(0)
        Me.ConversionOutputPanelEx.Name = "ConversionOutputPanelEx"
        Me.ConversionOutputPanelEx.Padding = New System.Windows.Forms.Padding(1)
        Me.ConversionOutputPanelEx.Size = New System.Drawing.Size(957, 710)
        Me.ConversionOutputPanelEx.TabIndex = 26
        '
        'ConversionOutput
        '
        Me.ConversionOutput.BorderStyle = System.Windows.Forms.BorderStyle.None
        Me.ConversionOutput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionOutput.DetectUrls = False
        Me.ConversionOutput.Dock = System.Windows.Forms.DockStyle.Fill
        Me.ConversionOutput.Font = New System.Drawing.Font("Consolas", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionOutput.Location = New System.Drawing.Point(1, 1)
        Me.ConversionOutput.Name = "ConversionOutput"
        Me.ConversionOutput.Size = New System.Drawing.Size(955, 708)
        Me.ConversionOutput.TabIndex = 1
        Me.ConversionOutput.Text = ""
        Me.ConversionOutput.WordWrap = False
        '
        'LineNumbersForConversionOutput
        '
        Me.LineNumbersForConversionOutput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionOutput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionOutput.Location = New System.Drawing.Point(-23, 1)
        Me.LineNumbersForConversionOutput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionOutput.MarginLinesSide = CSharpToVBApp.LineNumbersForRichTextBox.LineNumberDockSides.Right
        Me.LineNumbersForConversionOutput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.Name = "LineNumbersForConversionOutput"
        Me.LineNumbersForConversionOutput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionOutput.ParentRichTextBox = Me.ConversionOutput
        Me.LineNumbersForConversionOutput.Size = New System.Drawing.Size(23, 708)
        Me.LineNumbersForConversionOutput.TabIndex = 25
        '
        'FileListPanelEx
        '
        Me.FileListPanelEx.BackColor = System.Drawing.Color.Transparent
        Me.FileListPanelEx.Controls.Add(Me.FileListListBox)
        Me.FileListPanelEx.Dock = System.Windows.Forms.DockStyle.Left
        Me.FileListPanelEx.Location = New System.Drawing.Point(0, 0)
        Me.FileListPanelEx.Margin = New System.Windows.Forms.Padding(0)
        Me.FileListPanelEx.Name = "FileListPanelEx"
        Me.FileListPanelEx.Padding = New System.Windows.Forms.Padding(1)
        Me.FileListPanelEx.Size = New System.Drawing.Size(950, 39)
        Me.FileListPanelEx.TabIndex = 2
        '
        'FileListListBox
        '
        Me.FileListListBox.BorderStyle = System.Windows.Forms.BorderStyle.None
        Me.FileListListBox.ContextMenuStrip = Me.ContextMenuStrip1
        Me.FileListListBox.Dock = System.Windows.Forms.DockStyle.Fill
        Me.FileListListBox.Enabled = False
        Me.FileListListBox.ItemHeight = 15
        Me.FileListListBox.Location = New System.Drawing.Point(1, 1)
        Me.FileListListBox.Name = "FileListListBox"
        Me.FileListListBox.Size = New System.Drawing.Size(948, 37)
        Me.FileListListBox.TabIndex = 0
        '
        'ErrorListPanelEx
        '
        Me.ErrorListPanelEx.BackColor = System.Drawing.Color.Transparent
        Me.ErrorListPanelEx.Controls.Add(Me.ErrorListListBox)
        Me.ErrorListPanelEx.Dock = System.Windows.Forms.DockStyle.Right
        Me.ErrorListPanelEx.Location = New System.Drawing.Point(969, 0)
        Me.ErrorListPanelEx.Margin = New System.Windows.Forms.Padding(0)
        Me.ErrorListPanelEx.Name = "ErrorListPanelEx"
        Me.ErrorListPanelEx.Padding = New System.Windows.Forms.Padding(1)
        Me.ErrorListPanelEx.Size = New System.Drawing.Size(954, 39)
        Me.ErrorListPanelEx.TabIndex = 3
        '
        'ErrorListListBox
        '
        Me.ErrorListListBox.BorderStyle = System.Windows.Forms.BorderStyle.None
        Me.ErrorListListBox.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ErrorListListBox.Dock = System.Windows.Forms.DockStyle.Fill
        Me.ErrorListListBox.Enabled = False
        Me.ErrorListListBox.ItemHeight = 15
        Me.ErrorListListBox.Location = New System.Drawing.Point(1, 1)
        Me.ErrorListListBox.Name = "ErrorListListBox"
        Me.ErrorListListBox.Size = New System.Drawing.Size(952, 37)
        Me.ErrorListListBox.TabIndex = 1
        '
        'StatusStrip1
        '
        Me.StatusStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.StatusStripElapasedTimeLabel, Me.StatusStripCurrentFileName, Me.StatusStripSpacer, Me.StatusStripConversionProgressBar, Me.StatusStripConversionFileProgressLabel, Me.StatusStripUpdateAvailable, Me.StatusStripUpdateNotAvailable})
        Me.StatusStrip1.Location = New System.Drawing.Point(0, 800)
        Me.StatusStrip1.Name = "StatusStrip1"
        Me.StatusStrip1.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional
        Me.StatusStrip1.ShowItemToolTips = True
        Me.StatusStrip1.Size = New System.Drawing.Size(1923, 22)
        Me.StatusStrip1.TabIndex = 6
        Me.StatusStrip1.Text = "StatusStrip1"
        '
        'StatusStripElapasedTimeLabel
        '
        Me.StatusStripElapasedTimeLabel.AutoSize = False
        Me.StatusStripElapasedTimeLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripElapasedTimeLabel.Name = "StatusStripElapasedTimeLabel"
        Me.StatusStripElapasedTimeLabel.Size = New System.Drawing.Size(150, 17)
        '
        'StatusStripCurrentFileName
        '
        Me.StatusStripCurrentFileName.AutoSize = False
        Me.StatusStripCurrentFileName.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripCurrentFileName.Name = "StatusStripCurrentFileName"
        Me.StatusStripCurrentFileName.Size = New System.Drawing.Size(500, 17)
        Me.StatusStripCurrentFileName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'StatusStripSpacer
        '
        Me.StatusStripSpacer.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripSpacer.Name = "StatusStripSpacer"
        Me.StatusStripSpacer.Size = New System.Drawing.Size(840, 17)
        Me.StatusStripSpacer.Spring = True
        '
        'StatusStripConversionProgressBar
        '
        Me.StatusStripConversionProgressBar.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right
        Me.StatusStripConversionProgressBar.AutoSize = False
        Me.StatusStripConversionProgressBar.DisplayIncrement = 10
        Me.StatusStripConversionProgressBar.Name = "StatusStripConversionProgressBar"
        Me.StatusStripConversionProgressBar.Size = New System.Drawing.Size(200, 16)
        Me.StatusStripConversionProgressBar.Step = 1
        Me.StatusStripConversionProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous
        Me.StatusStripConversionProgressBar.TextImageRelation = System.Windows.Forms.TextImageRelation.Overlay
        '
        'StatusStripConversionFileProgressLabel
        '
        Me.StatusStripConversionFileProgressLabel.AutoSize = False
        Me.StatusStripConversionFileProgressLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Left
        Me.StatusStripConversionFileProgressLabel.Name = "StatusStripConversionFileProgressLabel"
        Me.StatusStripConversionFileProgressLabel.Size = New System.Drawing.Size(200, 17)
        '
        'StatusStripUpdateAvailable
        '
        Me.StatusStripUpdateAvailable.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
        Me.StatusStripUpdateAvailable.Image = CType(resources.GetObject("StatusStripUpdateAvailable.Image"), System.Drawing.Image)
        Me.StatusStripUpdateAvailable.ImageTransparentColor = System.Drawing.Color.White
        Me.StatusStripUpdateAvailable.Name = "StatusStripUpdateAvailable"
        Me.StatusStripUpdateAvailable.Size = New System.Drawing.Size(16, 17)
        Me.StatusStripUpdateAvailable.ToolTipText = "Update Available"
        Me.StatusStripUpdateAvailable.Visible = False
        '
        'StatusStripUpdateNotAvailable
        '
        Me.StatusStripUpdateNotAvailable.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image
        Me.StatusStripUpdateNotAvailable.Image = CType(resources.GetObject("StatusStripUpdateNotAvailable.Image"), System.Drawing.Image)
        Me.StatusStripUpdateNotAvailable.ImageTransparentColor = System.Drawing.Color.White
        Me.StatusStripUpdateNotAvailable.Name = "StatusStripUpdateNotAvailable"
        Me.StatusStripUpdateNotAvailable.Size = New System.Drawing.Size(16, 17)
        Me.StatusStripUpdateNotAvailable.ToolTipText = "Update Not Available"
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'ProjectConversionInitProgressBar
        '
        Me.ProjectConversionInitProgressBar.Location = New System.Drawing.Point(385, 206)
        Me.ProjectConversionInitProgressBar.Name = "ProjectConversionInitProgressBar"
        Me.ProjectConversionInitProgressBar.Size = New System.Drawing.Size(100, 23)
        Me.ProjectConversionInitProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Marquee
        Me.ProjectConversionInitProgressBar.TabIndex = 1
        '
        'ProjectConversionInitProgressLabel
        '
        Me.ProjectConversionInitProgressLabel.AutoSize = True
        Me.ProjectConversionInitProgressLabel.Location = New System.Drawing.Point(385, 183)
        Me.ProjectConversionInitProgressLabel.Name = "ProjectConversionInitProgressLabel"
        Me.ProjectConversionInitProgressLabel.Size = New System.Drawing.Size(30, 15)
        Me.ProjectConversionInitProgressLabel.TabIndex = 1
        Me.ProjectConversionInitProgressLabel.Text = "Step"
        Me.ProjectConversionInitProgressLabel.Visible = False
        '
        'ToolTipFileList
        '
        Me.ToolTipFileList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'ToolTipErrorList
        '
        Me.ToolTipErrorList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1923, 822)
        Me.Controls.Add(Me.ProjectConversionInitProgressBar)
        Me.Controls.Add(Me.ProjectConversionInitProgressLabel)
        Me.Controls.Add(Me.LabelErrorCount)
        Me.Controls.Add(Me.ButtonStopConversion)
        Me.Controls.Add(Me.SplitContainer1)
        Me.Controls.Add(Me.TSFindToolStrip)
        Me.Controls.Add(Me.MenuStrip1)
        Me.Controls.Add(Me.StatusStrip1)
        Me.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.KeyPreview = True
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Name = "Form1"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Convert C# to Visual Basic"
        Me.MenuStrip1.ResumeLayout(False)
        Me.MenuStrip1.PerformLayout()
        Me.TSFindToolStrip.ResumeLayout(False)
        Me.TSFindToolStrip.PerformLayout()
        Me.ContextMenuStrip1.ResumeLayout(False)
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        Me.ConversionInputPanelEx.ResumeLayout(False)
        Me.ConversionOutputPanelEx.ResumeLayout(False)
        Me.FileListPanelEx.ResumeLayout(False)
        Me.ErrorListPanelEx.ResumeLayout(False)
        Me.StatusStrip1.ResumeLayout(False)
        Me.StatusStrip1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents ButtonStopConversion As Button
    Friend WithEvents ContextMenuCopy As ToolStripMenuItem
    Friend WithEvents ContextMenuCut As ToolStripMenuItem
    Friend WithEvents ContextMenuPaste As ToolStripMenuItem
    Friend WithEvents ContextMenuRedo As ToolStripMenuItem
    Friend WithEvents ContextMenuSelectAll As ToolStripMenuItem
    Friend WithEvents ContextMenuSeparator1 As ToolStripSeparator
    Friend WithEvents ContextMenuStrip1 As ContextMenuStrip
    Friend WithEvents ContextMenuUndo As ToolStripMenuItem
    Friend WithEvents ConversionInput As RichTextBox
    Friend WithEvents ConversionInputPanelEx As PanelEx
    Friend WithEvents ConversionOutput As RichTextBox
    Friend WithEvents ConversionOutputPanelEx As PanelEx
    Friend WithEvents ErrorListListBox As ListBox
    Friend WithEvents FileListListBox As ListBox
    Friend WithEvents InputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents LabelErrorCount As Label
    Friend WithEvents LineNumbersForConversionInput As LineNumbersForRichTextBox
    Friend WithEvents LineNumbersForConversionOutput As LineNumbersForRichTextBox
    Friend WithEvents MenuCompile As ToolStripMenuItem
    Friend WithEvents MenuConvert As ToolStripMenuItem
    Friend WithEvents MenuConvertConvertFolder As ToolStripMenuItem
    Friend WithEvents MenuConvertConvertSnippet As ToolStripMenuItem
    Friend WithEvents MenuConvertConvertTopLevelStmts As ToolStripMenuItem
    Friend WithEvents MenuConvertSep1 As ToolStripSeparator
    Friend WithEvents MenuConvertStartFolderConvertFromLastFile As ToolStripMenuItem
    Friend WithEvents MenuEdit As ToolStripMenuItem
    Friend WithEvents MenuEditCopy As ToolStripMenuItem
    Friend WithEvents MenuEditCut As ToolStripMenuItem
    Friend WithEvents MenuEditFind As ToolStripMenuItem
    Friend WithEvents MenuEditPaste As ToolStripMenuItem
    Friend WithEvents MenuEditRedo As ToolStripMenuItem
    Friend WithEvents MenuEditSelectAll As ToolStripMenuItem
    Friend WithEvents MenuEditSep1 As ToolStripSeparator
    Friend WithEvents MenuEditSep2 As ToolStripSeparator
    Friend WithEvents MenuEditUndo As ToolStripMenuItem
    Friend WithEvents MenuFile As ToolStripMenuItem
    Friend WithEvents MenuFileConvertProject As ToolStripMenuItem
    Friend WithEvents MenuFileExit As ToolStripMenuItem
    Friend WithEvents MenuFileLabelLastFolder As ToolStripMenuItem
    Friend WithEvents MenuFileLastFolder As ToolStripMenuItem
    Friend WithEvents MenuFileLastProject As ToolStripMenuItem
    Friend WithEvents MenuFileLastSolution As ToolStripMenuItem
    Friend WithEvents MenuFileLoadLastSnippet As ToolStripMenuItem
    Friend WithEvents MenuFileOpen As ToolStripMenuItem
    Friend WithEvents MenuFileSaveAs As ToolStripMenuItem
    Friend WithEvents MenuFileSaveSnippet As ToolStripMenuItem
    Friend WithEvents MenuFileSep1 As ToolStripSeparator
    Friend WithEvents MenuFileSep2 As ToolStripSeparator
    Friend WithEvents MenuFileSep3 As ToolStripSeparator
    Friend WithEvents MenuFileSep4 As ToolStripSeparator
    Friend WithEvents MenuHelp As ToolStripMenuItem
    Friend WithEvents MenuHelpAboutMenuItem As ToolStripMenuItem
    Friend WithEvents MenuHelpCheckForUpdatesMenuItem As ToolStripMenuItem
    Friend WithEvents MenuHelpReportIssueMenuItem As ToolStripMenuItem
    Friend WithEvents MenuOptions As ToolStripMenuItem
    Friend WithEvents MenuOptionsAddFilesToIgnoreFilesEithErrorsList As ToolStripMenuItem
    Friend WithEvents MenuOptionsAdvanced As ToolStripMenuItem
    Friend WithEvents MenuOptionsColorizeResult As ToolStripMenuItem
    Friend WithEvents MenuOptionsColorizeSource As ToolStripMenuItem
    Friend WithEvents MenuOptionsDefaultFramework As ToolStripMenuItem
    Friend WithEvents MenuOptionsDefaultFrameworkCore As ToolStripMenuItem
    Friend WithEvents MenuOptionsDefaultFrameworkFull As ToolStripMenuItem
    Friend WithEvents MenuOptionsDefaultFrameworkFullAnyCore As ToolStripMenuItem
    Friend WithEvents MenuOptionsDefaultFrameworkFullAnyFull As ToolStripMenuItem
    Friend WithEvents MenuOptionsDelayBetweenConversions As ToolStripComboBox
    Friend WithEvents MenuOptionsEditIgnoreFilesWithErrorsList As ToolStripMenuItem
    Friend WithEvents MenuOptionsFolderConversionsOptions As ToolStripMenuItem
    Friend WithEvents MenuOptionsFolderConversionsOptionsSkipAutoGenerated As ToolStripMenuItem
    Friend WithEvents MenuOptionsFolderConversionsOptionsSkipBinAndObjFolders As ToolStripMenuItem
    Friend WithEvents MenuOptionsFolderConversionsOptionsSkipTestResourceFiles As ToolStripMenuItem
    Friend WithEvents MenuOptionsPauseConvertOnSuccess As ToolStripMenuItem
    Friend WithEvents MenuOptionsSep1 As ToolStripSeparator
    Friend WithEvents MenuOptionsSep2 As ToolStripSeparator
    Friend WithEvents MenuOptionsSep3 As ToolStripSeparator
    Friend WithEvents MenuStrip1 As MenuStrip
    Friend WithEvents MenuView As ToolStripMenuItem
    Friend WithEvents MenuViewShowDestinationLineNumbers As ToolStripMenuItem
    Friend WithEvents MenuViewShowSourceLineNumbers As ToolStripMenuItem
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents ProjectConversionInitProgressBar As ProgressBar
    Friend WithEvents ProjectConversionInitProgressLabel As Label
    Friend WithEvents SaveFileDialog1 As SaveFileDialog
    Friend WithEvents SplitContainer1 As SplitContainer
    Friend WithEvents StatusStrip1 As StatusStrip
    Friend WithEvents StatusStripConversionFileProgressLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripConversionProgressBar As ToolStripTextProgressBar
    Friend WithEvents StatusStripCurrentFileName As ToolStripStatusLabel
    Friend WithEvents StatusStripElapasedTimeLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripSpacer As ToolStripStatusLabel
    Friend WithEvents StatusStripUpdateAvailable As ToolStripStatusLabel
    Friend WithEvents ToolTipErrorList As ToolTip
    Friend WithEvents ToolTipFileList As ToolTip
    Friend WithEvents TSFindClearHighlightsButton As ToolStripButton
    Friend WithEvents TSFindFindNextButton As ToolStripButton
    Friend WithEvents TSFindFindPreviousButton As ToolStripButton
    Friend WithEvents TSFindFindWhatComboBox As ToolStripComboBox
    Friend WithEvents TSFindLookInComboBox As ToolStripComboBox
    Friend WithEvents TSFindLookInLabel As ToolStripLabel
    Friend WithEvents TSFindMatchCaseCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindMatchWholeWordCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindSeparator1 As ToolStripSeparator
    Friend WithEvents TSFindSeparator2 As ToolStripSeparator
    Friend WithEvents TSFindSeparator3 As ToolStripSeparator
    Friend WithEvents TSFindSeparator4 As ToolStripSeparator
    Friend WithEvents TSFindSeparator5 As ToolStripSeparator
    Friend WithEvents TSFindToolStrip As ToolStrip
    Friend WithEvents TSThemeButton As ToolStripButton
    Friend WithEvents FileListPanelEx As PanelEx
    Friend WithEvents ErrorListPanelEx As PanelEx
    Friend WithEvents StatusStripUpdateNotAvailable As ToolStripStatusLabel
End Class
