<CompilerServices.DesignerGenerated()>
Partial Class Form1
    Inherits Form

    'Form overrides dispose to clean up the component list.
    <DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(disposing As Boolean)
        Try
            If disposing Then
                If components IsNot Nothing Then
                    components.Dispose()
                End If
                If _cancellationTokenSource IsNot Nothing Then
                    _cancellationTokenSource.Dispose()
                End If
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    '<System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New ComponentModel.Container()
        Dim resources As ComponentModel.ComponentResourceManager = New ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.MenuStrip1 = New MenuStrip()
        Me.mnuFile = New ToolStripMenuItem()
        Me.mnuFileOpen = New ToolStripMenuItem()
        Me.mnuFileLoadLastSnippet = New ToolStripMenuItem()
        Me.mnuFileSaveSnippet = New ToolStripMenuItem()
        Me.mnuFileSep1 = New ToolStripSeparator()
        Me.mnuFileSep2 = New ToolStripSeparator()
        Me.mnuFileLabelLastFolder = New ToolStripMenuItem()
        Me.mnuFileLastFolder = New ToolStripMenuItem()
        Me.mnuFileSep3 = New ToolStripSeparator()
        Me.mnuFileConvertProject = New ToolStripMenuItem()
        Me.mnuFileLastProject = New ToolStripMenuItem()
        Me.mnuFileLastSolution = New ToolStripMenuItem()
        Me.mnuFileSaveAs = New ToolStripMenuItem()
        Me.mnuFileSep4 = New ToolStripSeparator()
        Me.mnuFileExit = New ToolStripMenuItem()
        Me.mnuEdit = New ToolStripMenuItem()
        Me.mnuEditFind = New ToolStripMenuItem()
        Me.mnuEditSep1 = New ToolStripSeparator()
        Me.mnuEditUndo = New ToolStripMenuItem()
        Me.mnuEditRedo = New ToolStripMenuItem()
        Me.mnuEditSep2 = New ToolStripSeparator()
        Me.mnuEditCut = New ToolStripMenuItem()
        Me.mnuEditCopy = New ToolStripMenuItem()
        Me.mnuEditPaste = New ToolStripMenuItem()
        Me.mnuEditSelectAll = New ToolStripMenuItem()
        Me.mnuCompile = New ToolStripMenuItem()
        Me.mnuConvert = New ToolStripMenuItem()
        Me.mnuConvertConvertFolder = New ToolStripMenuItem()
        Me.mnuConvertConvertSnippet = New ToolStripMenuItem()
        Me.mnuConvertConvertTopLevelStmts = New ToolStripMenuItem()
        Me.mnuConvertSep1 = New ToolStripSeparator()
        Me.mnuConvertStartFolderConvertFromLastFile = New ToolStripMenuItem()
        Me.mnuOptions = New ToolStripMenuItem()
        Me.mnuOptionsColorizeResult = New ToolStripMenuItem()
        Me.mnuOptionsColorizeSource = New ToolStripMenuItem()
        Me.mnuOptionsDelayBetweenConversions = New ToolStripComboBox()
        Me.mnuOptionsSep1 = New ToolStripSeparator()
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList = New ToolStripMenuItem()
        Me.mnuOptionsEditIgnoreFilesWithErrorsList = New ToolStripMenuItem()
        Me.mnuOptionsSep2 = New ToolStripSeparator()
        Me.mnuOptionsFolderConversionsOptions = New ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated = New ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders = New ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles = New ToolStripMenuItem()
        Me.mnuOptionsPauseConvertOnSuccess = New ToolStripMenuItem()
        Me.mnuOptionsSep3 = New ToolStripSeparator()
        Me.mnuOptionsDefaultFramework = New ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkCore = New ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFullAnyCore = New ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFull = New ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFullAnyFull = New ToolStripMenuItem()
        Me.mnuOptionsAdvanced = New ToolStripMenuItem()
        Me.mnuView = New ToolStripMenuItem()
        Me.mnuViewShowSourceLineNumbers = New ToolStripMenuItem()
        Me.mnuViewShowDestinationLineNumbers = New ToolStripMenuItem()
        Me.mnuHelp = New ToolStripMenuItem()
        Me.mnuHelpReportIssueMenuItem = New ToolStripMenuItem()
        Me.mnuHelpCheckForUpdatesMenuItem = New ToolStripMenuItem()
        Me.mnuHelpAboutMenuItem = New ToolStripMenuItem()
        Me.TSFindToolStrip = New ToolStrip()
        Me.TSFindFindWhatComboBox = New ToolStripComboBox()
        Me.TSFindSeparator1 = New ToolStripSeparator()
        Me.TSFindLookInLabel = New ToolStripLabel()
        Me.TSFindLookInComboBox = New ToolStripComboBox()
        Me.TSFindSeparator2 = New ToolStripSeparator()
        Me.TSFindFindPreviousButton = New ToolStripButton()
        Me.TSFindFindNextButton = New ToolStripButton()
        Me.TSFindSeparator3 = New ToolStripSeparator()
        Me.TSFindMatchCaseCheckBox = New ToolStripCheckBox()
        Me.TSFindMatchWholeWordCheckBox = New ToolStripCheckBox()
        Me.TSFindSeparator4 = New ToolStripSeparator()
        Me.TSFindClearHighlightsButton = New ToolStripButton()
        Me.TSFindSeparator5 = New ToolStripSeparator()
        Me.TSThemeButton = New ToolStripButton()
        Me.SaveFileDialog1 = New SaveFileDialog()
        Me.ContextMenuStrip1 = New ContextMenuStrip(Me.components)
        Me.ContextMenuUndo = New ToolStripMenuItem()
        Me.ContextMenuRedo = New ToolStripMenuItem()
        Me.ContextMenuSeparator1 = New ToolStripSeparator()
        Me.ContextMenuCut = New ToolStripMenuItem()
        Me.ContextMenuCopy = New ToolStripMenuItem()
        Me.ContextMenuPaste = New ToolStripMenuItem()
        Me.ContextMenuSelectAll = New ToolStripMenuItem()
        Me.InputFolderBrowserDialog1 = New FolderBrowserDialog()
        Me.ButtonStopConversion = New Button()
        Me.LabelErrorCount = New Label()
        Me.SplitContainer1 = New SplitContainer()
        Me.ConversionInput = New RichTextBox()
        Me.LineNumbersForConversionInput = New LineNumbersForRichTextBox()
        Me.ConversionOutput = New RichTextBox()
        Me.LineNumbersForConversionOutput = New LineNumbersForRichTextBox()
        Me.ListBoxFileList = New ListBox()
        Me.ListBoxErrorList = New ListBox()
        Me.StatusStrip1 = New StatusStrip()
        Me.StatusStripElapasedTimeLabel = New ToolStripStatusLabel()
        Me.StatusStripCurrentFileName = New ToolStripStatusLabel()
        Me.StatusStripSpacer = New ToolStripStatusLabel()
        Me.StatusStripConversionProgressBar = New ToolStripTextProgressBar()
        Me.StatusStripConversionFileProgressLabel = New ToolStripStatusLabel()
        Me.StatusStripUpdateAvailable = New ToolStripStatusLabel()
        Me.OpenFileDialog1 = New OpenFileDialog()
        Me.ProjectConversionInitProgressBar = New ProgressBar()
        Me.ProjectConversionInitProgressLabel = New Label()
        Me.ToolTipFileList = New ToolTip(Me.components)
        Me.ToolTipErrorList = New ToolTip(Me.components)
        Me.MenuStrip1.SuspendLayout()
        Me.TSFindToolStrip.SuspendLayout()
        Me.ContextMenuStrip1.SuspendLayout()
        CType(Me.SplitContainer1, ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        Me.StatusStrip1.SuspendLayout()
        Me.SuspendLayout()
        '
        'MenuStrip1
        '
        Me.MenuStrip1.ImageScalingSize = New Size(36, 36)
        Me.MenuStrip1.Items.AddRange(New ToolStripItem() {Me.mnuFile, Me.mnuEdit, Me.mnuCompile, Me.mnuConvert, Me.mnuOptions, Me.mnuView, Me.mnuHelp})
        Me.MenuStrip1.Location = New Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Padding = New Padding(7, 2, 0, 2)
        Me.MenuStrip1.RenderMode = ToolStripRenderMode.Professional
        Me.MenuStrip1.Size = New Size(1923, 24)
        Me.MenuStrip1.TabIndex = 0
        '
        'mnuFile
        '
        Me.mnuFile.DropDownItems.AddRange(New ToolStripItem() {Me.mnuFileOpen, Me.mnuFileLoadLastSnippet, Me.mnuFileSaveSnippet, Me.mnuFileSep1, Me.mnuFileSep2, Me.mnuFileLabelLastFolder, Me.mnuFileLastFolder, Me.mnuFileSep3, Me.mnuFileConvertProject, Me.mnuFileLastProject, Me.mnuFileLastSolution, Me.mnuFileSaveAs, Me.mnuFileSep4, Me.mnuFileExit})
        Me.mnuFile.Name = "mnuFile"
        Me.mnuFile.ShortcutKeys = CType((Keys.Alt Or Keys.F), Keys)
        Me.mnuFile.Size = New Size(37, 20)
        Me.mnuFile.Text = "&File"
        '
        'mnuFileOpen
        '
        Me.mnuFileOpen.Image = CType(resources.GetObject("mnuFileOpen.Image"), Image)
        Me.mnuFileOpen.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuFileOpen.Name = "mnuFileOpen"
        Me.mnuFileOpen.ShortcutKeys = CType((Keys.Control Or Keys.O), Keys)
        Me.mnuFileOpen.Size = New Size(289, 22)
        Me.mnuFileOpen.Text = "Open C# File..."
        '
        'mnuFileLoadLastSnippet
        '
        Me.mnuFileLoadLastSnippet.Enabled = False
        Me.mnuFileLoadLastSnippet.Name = "mnuFileLoadLastSnippet"
        Me.mnuFileLoadLastSnippet.Size = New Size(289, 22)
        Me.mnuFileLoadLastSnippet.Text = "Load Last Snippet"
        '
        'mnuFileSaveSnippet
        '
        Me.mnuFileSaveSnippet.Enabled = False
        Me.mnuFileSaveSnippet.Name = "mnuFileSaveSnippet"
        Me.mnuFileSaveSnippet.Size = New Size(289, 22)
        Me.mnuFileSaveSnippet.Text = "Save Snippet"
        '
        'mnuFileSep1
        '
        Me.mnuFileSep1.Name = "mnuFileSep1"
        Me.mnuFileSep1.Size = New Size(286, 6)
        '
        'mnuFileSep2
        '
        Me.mnuFileSep2.Name = "mnuFileSep2"
        Me.mnuFileSep2.Size = New Size(286, 6)
        '
        'mnuFileLabelLastFolder
        '
        Me.mnuFileLabelLastFolder.Enabled = False
        Me.mnuFileLabelLastFolder.Name = "mnuFileLabelLastFolder"
        Me.mnuFileLabelLastFolder.Size = New Size(289, 22)
        Me.mnuFileLabelLastFolder.Text = "Last Converted Folder"
        '
        'mnuFileLastFolder
        '
        Me.mnuFileLastFolder.Name = "mnuFileLastFolder"
        Me.mnuFileLastFolder.Size = New Size(289, 22)
        Me.mnuFileLastFolder.Visible = False
        '
        'mnuFileSep3
        '
        Me.mnuFileSep3.Name = "mnuFileSep3"
        Me.mnuFileSep3.Size = New Size(286, 6)
        '
        'mnuFileConvertProject
        '
        Me.mnuFileConvertProject.Image = CType(resources.GetObject("mnuFileConvertProject.Image"), Image)
        Me.mnuFileConvertProject.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuFileConvertProject.Name = "mnuFileConvertProject"
        Me.mnuFileConvertProject.ShortcutKeys = CType(((Keys.Control Or Keys.Shift) _
            Or Keys.O), Keys)
        Me.mnuFileConvertProject.Size = New Size(289, 22)
        Me.mnuFileConvertProject.Text = "Convert Project/Solution..."
        '
        'mnuFileLastProject
        '
        Me.mnuFileLastProject.Enabled = False
        Me.mnuFileLastProject.Name = "mnuFileLastProject"
        Me.mnuFileLastProject.Size = New Size(289, 22)
        Me.mnuFileLastProject.Text = "Open Last Project"
        '
        'mnuFileLastSolution
        '
        Me.mnuFileLastSolution.Enabled = False
        Me.mnuFileLastSolution.Name = "mnuFileLastSolution"
        Me.mnuFileLastSolution.Size = New Size(289, 22)
        Me.mnuFileLastSolution.Text = "Open Last Solution"
        '
        'mnuFileSaveAs
        '
        Me.mnuFileSaveAs.Enabled = False
        Me.mnuFileSaveAs.Image = CType(resources.GetObject("mnuFileSaveAs.Image"), Image)
        Me.mnuFileSaveAs.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuFileSaveAs.Name = "mnuFileSaveAs"
        Me.mnuFileSaveAs.ShortcutKeys = CType((Keys.Alt Or Keys.A), Keys)
        Me.mnuFileSaveAs.Size = New Size(289, 22)
        Me.mnuFileSaveAs.Text = "Save Visual Basic File &As..."
        '
        'mnuFileSep4
        '
        Me.mnuFileSep4.Name = "mnuFileSep4"
        Me.mnuFileSep4.Size = New Size(286, 6)
        '
        'mnuFileExit
        '
        Me.mnuFileExit.Name = "mnuFileExit"
        Me.mnuFileExit.ShortcutKeys = CType((Keys.Alt Or Keys.X), Keys)
        Me.mnuFileExit.Size = New Size(289, 22)
        Me.mnuFileExit.Text = "E&xit"
        '
        'mnuEdit
        '
        Me.mnuEdit.DropDownItems.AddRange(New ToolStripItem() {Me.mnuEditFind, Me.mnuEditSep1, Me.mnuEditUndo, Me.mnuEditRedo, Me.mnuEditSep2, Me.mnuEditCut, Me.mnuEditCopy, Me.mnuEditPaste, Me.mnuEditSelectAll})
        Me.mnuEdit.Name = "mnuEdit"
        Me.mnuEdit.ShortcutKeys = CType((Keys.Alt Or Keys.E), Keys)
        Me.mnuEdit.Size = New Size(39, 20)
        Me.mnuEdit.Text = "&Edit"
        '
        'mnuEditFind
        '
        Me.mnuEditFind.Image = CType(resources.GetObject("mnuEditFind.Image"), Image)
        Me.mnuEditFind.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditFind.Name = "mnuEditFind"
        Me.mnuEditFind.ShortcutKeys = CType((Keys.Control Or Keys.F), Keys)
        Me.mnuEditFind.Size = New Size(164, 22)
        Me.mnuEditFind.Text = "&Find..."
        '
        'mnuEditSep1
        '
        Me.mnuEditSep1.Name = "mnuEditSep1"
        Me.mnuEditSep1.Size = New Size(161, 6)
        '
        'mnuEditUndo
        '
        Me.mnuEditUndo.Image = CType(resources.GetObject("mnuEditUndo.Image"), Image)
        Me.mnuEditUndo.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditUndo.Name = "mnuEditUndo"
        Me.mnuEditUndo.ShortcutKeyDisplayString = "Ctrl+Z"
        Me.mnuEditUndo.ShortcutKeys = CType((Keys.Control Or Keys.Z), Keys)
        Me.mnuEditUndo.Size = New Size(164, 22)
        Me.mnuEditUndo.Text = "Undo"
        '
        'mnuEditRedo
        '
        Me.mnuEditRedo.Image = CType(resources.GetObject("mnuEditRedo.Image"), Image)
        Me.mnuEditRedo.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditRedo.Name = "mnuEditRedo"
        Me.mnuEditRedo.ShortcutKeyDisplayString = "Ctrl+Y"
        Me.mnuEditRedo.ShortcutKeys = CType((Keys.Control Or Keys.Y), Keys)
        Me.mnuEditRedo.Size = New Size(164, 22)
        Me.mnuEditRedo.Text = "Redo"
        '
        'mnuEditSep2
        '
        Me.mnuEditSep2.Name = "mnuEditSep2"
        Me.mnuEditSep2.Size = New Size(161, 6)
        '
        'mnuEditCut
        '
        Me.mnuEditCut.Image = CType(resources.GetObject("mnuEditCut.Image"), Image)
        Me.mnuEditCut.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditCut.Name = "mnuEditCut"
        Me.mnuEditCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.mnuEditCut.ShortcutKeys = CType((Keys.Control Or Keys.X), Keys)
        Me.mnuEditCut.Size = New Size(164, 22)
        Me.mnuEditCut.Text = "Cut"
        '
        'mnuEditCopy
        '
        Me.mnuEditCopy.Image = CType(resources.GetObject("mnuEditCopy.Image"), Image)
        Me.mnuEditCopy.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditCopy.Name = "mnuEditCopy"
        Me.mnuEditCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.mnuEditCopy.ShortcutKeys = CType((Keys.Control Or Keys.C), Keys)
        Me.mnuEditCopy.Size = New Size(164, 22)
        Me.mnuEditCopy.Text = "Copy"
        '
        'mnuEditPaste
        '
        Me.mnuEditPaste.Image = CType(resources.GetObject("mnuEditPaste.Image"), Image)
        Me.mnuEditPaste.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditPaste.Name = "mnuEditPaste"
        Me.mnuEditPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.mnuEditPaste.ShortcutKeys = CType((Keys.Control Or Keys.V), Keys)
        Me.mnuEditPaste.Size = New Size(164, 22)
        Me.mnuEditPaste.Text = "Paste"
        '
        'mnuEditSelectAll
        '
        Me.mnuEditSelectAll.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuEditSelectAll.Name = "mnuEditSelectAll"
        Me.mnuEditSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.mnuEditSelectAll.ShortcutKeys = CType((Keys.Control Or Keys.A), Keys)
        Me.mnuEditSelectAll.Size = New Size(164, 22)
        Me.mnuEditSelectAll.Text = "Select All"
        '
        'mnuCompile
        '
        Me.mnuCompile.Enabled = False
        Me.mnuCompile.Name = "mnuCompile"
        Me.mnuCompile.Size = New Size(64, 20)
        Me.mnuCompile.Text = "Compile"
        '
        'mnuConvert
        '
        Me.mnuConvert.DropDownItems.AddRange(New ToolStripItem() {Me.mnuConvertConvertFolder, Me.mnuConvertConvertSnippet, Me.mnuConvertConvertTopLevelStmts, Me.mnuConvertSep1, Me.mnuConvertStartFolderConvertFromLastFile})
        Me.mnuConvert.Name = "mnuConvert"
        Me.mnuConvert.Size = New Size(61, 20)
        Me.mnuConvert.Text = "Convert"
        '
        'mnuConvertConvertFolder
        '
        Me.mnuConvertConvertFolder.Image = CType(resources.GetObject("mnuConvertConvertFolder.Image"), Image)
        Me.mnuConvertConvertFolder.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuConvertConvertFolder.Name = "mnuConvertConvertFolder"
        Me.mnuConvertConvertFolder.ShortcutKeys = CType((Keys.Control Or Keys.F), Keys)
        Me.mnuConvertConvertFolder.Size = New Size(237, 22)
        Me.mnuConvertConvertFolder.Text = "Convert Folder"
        '
        'mnuConvertConvertSnippet
        '
        Me.mnuConvertConvertSnippet.Enabled = False
        Me.mnuConvertConvertSnippet.Image = CType(resources.GetObject("mnuConvertConvertSnippet.Image"), Image)
        Me.mnuConvertConvertSnippet.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuConvertConvertSnippet.Name = "mnuConvertConvertSnippet"
        Me.mnuConvertConvertSnippet.ShortcutKeys = CType((Keys.Control Or Keys.S), Keys)
        Me.mnuConvertConvertSnippet.Size = New Size(237, 22)
        Me.mnuConvertConvertSnippet.Text = "Convert Snippet"
        '
        'mnuConvertConvertTopLevelStmts
        '
        Me.mnuConvertConvertTopLevelStmts.Enabled = False
        Me.mnuConvertConvertTopLevelStmts.Image = CType(resources.GetObject("mnuConvertConvertSnippet.Image"), Image)
        Me.mnuConvertConvertTopLevelStmts.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuConvertConvertTopLevelStmts.Name = "mnuConvertConvertTopLevelStmts"
        Me.mnuConvertConvertTopLevelStmts.Size = New Size(237, 22)
        Me.mnuConvertConvertTopLevelStmts.Text = "Convert Top Level Statements"
        '
        'mnuConvertSep1
        '
        Me.mnuConvertSep1.Name = "mnuConvertSep1"
        Me.mnuConvertSep1.Size = New Size(234, 6)
        '
        'mnuConvertStartFolderConvertFromLastFile
        '
        Me.mnuConvertStartFolderConvertFromLastFile.Checked = True
        Me.mnuConvertStartFolderConvertFromLastFile.CheckOnClick = True
        Me.mnuConvertStartFolderConvertFromLastFile.CheckState = CheckState.Checked
        Me.mnuConvertStartFolderConvertFromLastFile.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuConvertStartFolderConvertFromLastFile.Name = "mnuConvertStartFolderConvertFromLastFile"
        Me.mnuConvertStartFolderConvertFromLastFile.Size = New Size(237, 22)
        Me.mnuConvertStartFolderConvertFromLastFile.Text = "Start Conversion From Last File"
        '
        'mnuOptions
        '
        Me.mnuOptions.DropDownItems.AddRange(New ToolStripItem() {Me.mnuOptionsColorizeResult, Me.mnuOptionsColorizeSource, Me.mnuOptionsDelayBetweenConversions, Me.mnuOptionsSep1, Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList, Me.mnuOptionsEditIgnoreFilesWithErrorsList, Me.mnuOptionsSep2, Me.mnuOptionsFolderConversionsOptions, Me.mnuOptionsPauseConvertOnSuccess, Me.mnuOptionsSep3, Me.mnuOptionsDefaultFramework, Me.mnuOptionsAdvanced})
        Me.mnuOptions.Name = "mnuOptions"
        Me.mnuOptions.ShortcutKeys = CType((Keys.Alt Or Keys.O), Keys)
        Me.mnuOptions.Size = New Size(61, 20)
        Me.mnuOptions.Text = "&Options"
        '
        'mnuOptionsColorizeResult
        '
        Me.mnuOptionsColorizeResult.CheckOnClick = True
        Me.mnuOptionsColorizeResult.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeResult.Name = "mnuOptionsColorizeResult"
        Me.mnuOptionsColorizeResult.Size = New Size(360, 22)
        Me.mnuOptionsColorizeResult.Text = "Colorize Result"
        '
        'mnuOptionsColorizeSource
        '
        Me.mnuOptionsColorizeSource.CheckOnClick = True
        Me.mnuOptionsColorizeSource.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeSource.Name = "mnuOptionsColorizeSource"
        Me.mnuOptionsColorizeSource.Size = New Size(360, 22)
        Me.mnuOptionsColorizeSource.Text = "Colorize Source"
        '
        'mnuOptionsDelayBetweenConversions
        '
        Me.mnuOptionsDelayBetweenConversions.DropDownStyle = ComboBoxStyle.DropDownList
        Me.mnuOptionsDelayBetweenConversions.Items.AddRange(New Object() {"Delay Between Conversions = None", "Delay Between Conversions = 5 Seconds", "Delay Between Conversions = 10 Seconds"})
        Me.mnuOptionsDelayBetweenConversions.MaxDropDownItems = 3
        Me.mnuOptionsDelayBetweenConversions.Name = "mnuOptionsDelayBetweenConversions"
        Me.mnuOptionsDelayBetweenConversions.Size = New Size(300, 23)
        '
        'mnuOptionsSep1
        '
        Me.mnuOptionsSep1.Name = "mnuOptionsSep1"
        Me.mnuOptionsSep1.Size = New Size(357, 6)
        '
        'mnuOptionsAddFilesToIgnoreFilesEithErrorsList
        '
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image = CType(resources.GetObject("mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image"), Image)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Name = "mnuOptionsAddFilesToIgnoreFilesEithErrorsList"
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Size = New Size(360, 22)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Text = "Add File to the ""Ignore files with errors list"""
        '
        'mnuOptionsEditIgnoreFilesWithErrorsList
        '
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Name = "mnuOptionsEditIgnoreFilesWithErrorsList"
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Size = New Size(360, 22)
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Text = "Show/Edit the ""Ignore files with errors"" list..."
        '
        'mnuOptionsSep2
        '
        Me.mnuOptionsSep2.Name = "mnuOptionsSep2"
        Me.mnuOptionsSep2.Size = New Size(357, 6)
        '
        'mnuOptionsFolderConversionsOptions
        '
        Me.mnuOptionsFolderConversionsOptions.DropDownItems.AddRange(New ToolStripItem() {Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated, Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders, Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles})
        Me.mnuOptionsFolderConversionsOptions.Name = "mnuOptionsFolderConversionsOptions"
        Me.mnuOptionsFolderConversionsOptions.Size = New Size(360, 22)
        Me.mnuOptionsFolderConversionsOptions.Text = "Folder Conversions Options"
        '
        'mnuOptionsFolderConversionsOptionsSkipAutoGenerated
        '
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckState = CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Name = "mnuOptionsFolderConversionsOptionsSkipAutoGenerated"
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Size = New Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Text = "Skip Auto Generated"
        '
        'mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders
        '
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckState = CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Name = "mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders"
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Size = New Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Text = "Skip Bin and Obj Folders"
        '
        'mnuOptionsFolderConversionsOptionsSkipTestResourceFiles
        '
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckState = CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Name = "mnuOptionsFolderConversionsOptionsSkipTestResourceFiles"
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Size = New Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Text = "Skip Test/Resource Files"
        '
        'mnuOptionsPauseConvertOnSuccess
        '
        Me.mnuOptionsPauseConvertOnSuccess.CheckOnClick = True
        Me.mnuOptionsPauseConvertOnSuccess.Image = CType(resources.GetObject("mnuOptionsPauseConvertOnSuccess.Image"), Image)
        Me.mnuOptionsPauseConvertOnSuccess.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsPauseConvertOnSuccess.Name = "mnuOptionsPauseConvertOnSuccess"
        Me.mnuOptionsPauseConvertOnSuccess.Size = New Size(360, 22)
        Me.mnuOptionsPauseConvertOnSuccess.Text = "Pause Conversion on Success"
        '
        'mnuOptionsSep3
        '
        Me.mnuOptionsSep3.Name = "mnuOptionsSep3"
        Me.mnuOptionsSep3.Size = New Size(357, 6)
        '
        'mnuOptionsDefaultFramework
        '
        Me.mnuOptionsDefaultFramework.DropDownItems.AddRange(New ToolStripItem() {Me.mnuOptionsDefaultFrameworkCore, Me.mnuOptionsDefaultFrameworkFull})
        Me.mnuOptionsDefaultFramework.Name = "mnuOptionsDefaultFramework"
        Me.mnuOptionsDefaultFramework.Size = New Size(360, 22)
        Me.mnuOptionsDefaultFramework.Text = "Default Framework For Conversion"
        '
        'mnuOptionsDefaultFrameworkCore
        '
        Me.mnuOptionsDefaultFrameworkCore.Checked = True
        Me.mnuOptionsDefaultFrameworkCore.CheckState = CheckState.Checked
        Me.mnuOptionsDefaultFrameworkCore.DropDownItems.AddRange(New ToolStripItem() {Me.mnuOptionsDefaultFrameworkFullAnyCore})
        Me.mnuOptionsDefaultFrameworkCore.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkCore.Name = "mnuOptionsDefaultFrameworkCore"
        Me.mnuOptionsDefaultFrameworkCore.Size = New Size(180, 22)
        Me.mnuOptionsDefaultFrameworkCore.Text = ".Net Core"
        '
        'mnuOptionsDefaultFrameworkFullAnyCore
        '
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Checked = True
        Me.mnuOptionsDefaultFrameworkFullAnyCore.CheckOnClick = True
        Me.mnuOptionsDefaultFrameworkFullAnyCore.CheckState = CheckState.Checked
        Me.mnuOptionsDefaultFrameworkFullAnyCore.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Name = "mnuOptionsDefaultFrameworkFullAnyCore"
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Size = New Size(146, 22)
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Text = "NETCOREAPP"
        '
        'mnuOptionsDefaultFrameworkFull
        '
        Me.mnuOptionsDefaultFrameworkFull.DropDownItems.AddRange(New ToolStripItem() {Me.mnuOptionsDefaultFrameworkFullAnyFull})
        Me.mnuOptionsDefaultFrameworkFull.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFull.Name = "mnuOptionsDefaultFrameworkFull"
        Me.mnuOptionsDefaultFrameworkFull.Size = New Size(180, 22)
        Me.mnuOptionsDefaultFrameworkFull.Text = ".Net Full Framework"
        '
        'mnuOptionsDefaultFrameworkFullAnyFull
        '
        Me.mnuOptionsDefaultFrameworkFullAnyFull.CheckOnClick = True
        Me.mnuOptionsDefaultFrameworkFullAnyFull.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Name = "mnuOptionsDefaultFrameworkFullAnyFull"
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Size = New Size(167, 22)
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Text = "NETFRAMEWORK"
        '
        'mnuOptionsAdvanced
        '
        Me.mnuOptionsAdvanced.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuOptionsAdvanced.Name = "mnuOptionsAdvanced"
        Me.mnuOptionsAdvanced.Size = New Size(360, 22)
        Me.mnuOptionsAdvanced.Text = "Advanced Options..."
        '
        'mnuView
        '
        Me.mnuView.CheckOnClick = True
        Me.mnuView.DropDownItems.AddRange(New ToolStripItem() {Me.mnuViewShowSourceLineNumbers, Me.mnuViewShowDestinationLineNumbers})
        Me.mnuView.Name = "mnuView"
        Me.mnuView.ShortcutKeys = CType((Keys.Alt Or Keys.V), Keys)
        Me.mnuView.Size = New Size(44, 20)
        Me.mnuView.Text = "&View"
        '
        'mnuViewShowSourceLineNumbers
        '
        Me.mnuViewShowSourceLineNumbers.CheckOnClick = True
        Me.mnuViewShowSourceLineNumbers.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuViewShowSourceLineNumbers.Name = "mnuViewShowSourceLineNumbers"
        Me.mnuViewShowSourceLineNumbers.Size = New Size(243, 22)
        Me.mnuViewShowSourceLineNumbers.Text = "Show Source Line Numbers"
        '
        'mnuViewShowDestinationLineNumbers
        '
        Me.mnuViewShowDestinationLineNumbers.CheckOnClick = True
        Me.mnuViewShowDestinationLineNumbers.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuViewShowDestinationLineNumbers.Name = "mnuViewShowDestinationLineNumbers"
        Me.mnuViewShowDestinationLineNumbers.Size = New Size(243, 22)
        Me.mnuViewShowDestinationLineNumbers.Text = "Show Destination Line Numbers"
        '
        'mnuHelp
        '
        Me.mnuHelp.DropDownItems.AddRange(New ToolStripItem() {Me.mnuHelpReportIssueMenuItem, Me.mnuHelpCheckForUpdatesMenuItem, Me.mnuHelpAboutMenuItem})
        Me.mnuHelp.Name = "mnuHelp"
        Me.mnuHelp.ShortcutKeys = CType((Keys.Alt Or Keys.H), Keys)
        Me.mnuHelp.Size = New Size(44, 20)
        Me.mnuHelp.Text = "&Help"
        '
        'mnuHelpReportIssueMenuItem
        '
        Me.mnuHelpReportIssueMenuItem.Image = CType(resources.GetObject("mnuHelpReportIssueMenuItem.Image"), Image)
        Me.mnuHelpReportIssueMenuItem.ImageScaling = ToolStripItemImageScaling.None
        Me.mnuHelpReportIssueMenuItem.Name = "mnuHelpReportIssueMenuItem"
        Me.mnuHelpReportIssueMenuItem.Size = New Size(177, 22)
        Me.mnuHelpReportIssueMenuItem.Text = "Report A Problem..."
        '
        'mnuHelpCheckForUpdatesMenuItem
        '
        Me.mnuHelpCheckForUpdatesMenuItem.Name = "mnuHelpCheckForUpdatesMenuItem"
        Me.mnuHelpCheckForUpdatesMenuItem.Size = New Size(177, 22)
        Me.mnuHelpCheckForUpdatesMenuItem.Text = "Check For Updates"
        '
        'mnuHelpAboutMenuItem
        '
        Me.mnuHelpAboutMenuItem.Name = "mnuHelpAboutMenuItem"
        Me.mnuHelpAboutMenuItem.Size = New Size(177, 22)
        Me.mnuHelpAboutMenuItem.Text = "About"
        '
        'TSFindToolStrip
        '
        Me.TSFindToolStrip.Items.AddRange(New ToolStripItem() {Me.TSFindFindWhatComboBox, Me.TSFindSeparator1, Me.TSFindLookInLabel, Me.TSFindLookInComboBox, Me.TSFindSeparator2, Me.TSFindFindPreviousButton, Me.TSFindFindNextButton, Me.TSFindSeparator3, Me.TSFindMatchCaseCheckBox, Me.TSFindMatchWholeWordCheckBox, Me.TSFindSeparator4, Me.TSFindClearHighlightsButton, Me.TSFindSeparator5, Me.TSThemeButton})
        Me.TSFindToolStrip.Location = New Point(0, 24)
        Me.TSFindToolStrip.Name = "TSFindToolStrip"
        Me.TSFindToolStrip.RenderMode = ToolStripRenderMode.Professional
        Me.TSFindToolStrip.Size = New Size(1923, 25)
        Me.TSFindToolStrip.TabIndex = 2
        Me.TSFindToolStrip.Text = "ToolStrip1"
        '
        'TSFindFindWhatComboBox
        '
        Me.TSFindFindWhatComboBox.AutoSize = False
        Me.TSFindFindWhatComboBox.ForeColor = SystemColors.GrayText
        Me.TSFindFindWhatComboBox.Name = "TSFindFindWhatComboBox"
        Me.TSFindFindWhatComboBox.Size = New Size(400, 23)
        Me.TSFindFindWhatComboBox.Text = "Search..."
        '
        'TSFindSeparator1
        '
        Me.TSFindSeparator1.Margin = New Padding(5, 0, 5, 0)
        Me.TSFindSeparator1.Name = "TSFindSeparator1"
        Me.TSFindSeparator1.Size = New Size(6, 25)
        '
        'TSFindLookInLabel
        '
        Me.TSFindLookInLabel.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindLookInLabel.Name = "TSFindLookInLabel"
        Me.TSFindLookInLabel.Size = New Size(49, 25)
        Me.TSFindLookInLabel.Text = "Look In:"
        '
        'TSFindLookInComboBox
        '
        Me.TSFindLookInComboBox.AutoCompleteSource = AutoCompleteSource.ListItems
        Me.TSFindLookInComboBox.Items.AddRange(New Object() {"C# Source", "Visual Basic Output", "Both"})
        Me.TSFindLookInComboBox.MaxDropDownItems = 3
        Me.TSFindLookInComboBox.Name = "TSFindLookInComboBox"
        Me.TSFindLookInComboBox.Size = New Size(130, 25)
        '
        'TSFindSeparator2
        '
        Me.TSFindSeparator2.Margin = New Padding(5, 0, 5, 0)
        Me.TSFindSeparator2.Name = "TSFindSeparator2"
        Me.TSFindSeparator2.Size = New Size(6, 25)
        '
        'TSFindFindPreviousButton
        '
        Me.TSFindFindPreviousButton.DisplayStyle = ToolStripItemDisplayStyle.Text
        Me.TSFindFindPreviousButton.ImageTransparentColor = Color.Magenta
        Me.TSFindFindPreviousButton.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindFindPreviousButton.Name = "TSFindFindPreviousButton"
        Me.TSFindFindPreviousButton.Size = New Size(82, 25)
        Me.TSFindFindPreviousButton.Text = "Find Previous"
        '
        'TSFindFindNextButton
        '
        Me.TSFindFindNextButton.DisplayStyle = ToolStripItemDisplayStyle.Text
        Me.TSFindFindNextButton.ImageTransparentColor = Color.Magenta
        Me.TSFindFindNextButton.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindFindNextButton.Name = "TSFindFindNextButton"
        Me.TSFindFindNextButton.Size = New Size(62, 25)
        Me.TSFindFindNextButton.Text = "Find Next"
        '
        'TSFindSeparator3
        '
        Me.TSFindSeparator3.Margin = New Padding(5, 0, 5, 0)
        Me.TSFindSeparator3.Name = "TSFindSeparator3"
        Me.TSFindSeparator3.Size = New Size(6, 25)
        '
        'TSFindMatchCaseCheckBox
        '
        Me.TSFindMatchCaseCheckBox.Checked = False
        Me.TSFindMatchCaseCheckBox.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindMatchCaseCheckBox.Name = "TSFindMatchCaseCheckBox"
        Me.TSFindMatchCaseCheckBox.Size = New Size(88, 25)
        Me.TSFindMatchCaseCheckBox.Text = "Match Case"
        '
        'TSFindMatchWholeWordCheckBox
        '
        Me.TSFindMatchWholeWordCheckBox.Checked = False
        Me.TSFindMatchWholeWordCheckBox.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindMatchWholeWordCheckBox.Name = "TSFindMatchWholeWordCheckBox"
        Me.TSFindMatchWholeWordCheckBox.Size = New Size(129, 25)
        Me.TSFindMatchWholeWordCheckBox.Text = "Match Whole Word"
        '
        'TSFindSeparator4
        '
        Me.TSFindSeparator4.Margin = New Padding(5, 0, 5, 0)
        Me.TSFindSeparator4.Name = "TSFindSeparator4"
        Me.TSFindSeparator4.Size = New Size(6, 25)
        '
        'TSFindClearHighlightsButton
        '
        Me.TSFindClearHighlightsButton.DisplayStyle = ToolStripItemDisplayStyle.Text
        Me.TSFindClearHighlightsButton.ImageTransparentColor = Color.Magenta
        Me.TSFindClearHighlightsButton.Margin = New Padding(1, 0, 1, 0)
        Me.TSFindClearHighlightsButton.Name = "TSFindClearHighlightsButton"
        Me.TSFindClearHighlightsButton.Size = New Size(96, 25)
        Me.TSFindClearHighlightsButton.Text = "Clear Highlights"
        '
        'TSFindSeparator5
        '
        Me.TSFindSeparator5.Margin = New Padding(5, 0, 5, 0)
        Me.TSFindSeparator5.Name = "TSFindSeparator5"
        Me.TSFindSeparator5.Size = New Size(6, 25)
        '
        'TSThemeButton
        '
        Me.TSThemeButton.DisplayStyle = ToolStripItemDisplayStyle.Text
        Me.TSThemeButton.ImageTransparentColor = Color.Magenta
        Me.TSThemeButton.Margin = New Padding(1, 0, 1, 0)
        Me.TSThemeButton.Name = "TSThemeButton"
        Me.TSThemeButton.Size = New Size(77, 25)
        Me.TSThemeButton.Text = "Light Mode"
        '
        'ContextMenuStrip1
        '
        Me.ContextMenuStrip1.ImageScalingSize = New Size(36, 36)
        Me.ContextMenuStrip1.Items.AddRange(New ToolStripItem() {Me.ContextMenuUndo, Me.ContextMenuRedo, Me.ContextMenuSeparator1, Me.ContextMenuCut, Me.ContextMenuCopy, Me.ContextMenuPaste, Me.ContextMenuSelectAll})
        Me.ContextMenuStrip1.Name = "ContextMenuStrip1"
        Me.ContextMenuStrip1.RenderMode = ToolStripRenderMode.Professional
        Me.ContextMenuStrip1.Size = New Size(165, 142)
        '
        'ContextMenuUndo
        '
        Me.ContextMenuUndo.Image = CType(resources.GetObject("ContextMenuUndo.Image"), Image)
        Me.ContextMenuUndo.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuUndo.Name = "ContextMenuUndo"
        Me.ContextMenuUndo.ShortcutKeys = CType((Keys.Control Or Keys.Z), Keys)
        Me.ContextMenuUndo.Size = New Size(164, 22)
        Me.ContextMenuUndo.Text = "Undo"
        '
        'ContextMenuRedo
        '
        Me.ContextMenuRedo.Image = CType(resources.GetObject("ContextMenuRedo.Image"), Image)
        Me.ContextMenuRedo.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuRedo.Name = "ContextMenuRedo"
        Me.ContextMenuRedo.ShortcutKeys = CType((Keys.Control Or Keys.Y), Keys)
        Me.ContextMenuRedo.Size = New Size(164, 22)
        Me.ContextMenuRedo.Text = "Redo"
        '
        'ContextMenuSeparator1
        '
        Me.ContextMenuSeparator1.Name = "ContextMenuSeparator1"
        Me.ContextMenuSeparator1.Size = New Size(161, 6)
        '
        'ContextMenuCut
        '
        Me.ContextMenuCut.Image = CType(resources.GetObject("ContextMenuCut.Image"), Image)
        Me.ContextMenuCut.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuCut.Name = "ContextMenuCut"
        Me.ContextMenuCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.ContextMenuCut.ShortcutKeys = CType((Keys.Control Or Keys.X), Keys)
        Me.ContextMenuCut.Size = New Size(164, 22)
        Me.ContextMenuCut.Text = "Cut"
        '
        'ContextMenuCopy
        '
        Me.ContextMenuCopy.Image = CType(resources.GetObject("ContextMenuCopy.Image"), Image)
        Me.ContextMenuCopy.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuCopy.Name = "ContextMenuCopy"
        Me.ContextMenuCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.ContextMenuCopy.ShortcutKeys = CType((Keys.Control Or Keys.C), Keys)
        Me.ContextMenuCopy.Size = New Size(164, 22)
        Me.ContextMenuCopy.Text = "Copy"
        '
        'ContextMenuPaste
        '
        Me.ContextMenuPaste.Image = CType(resources.GetObject("ContextMenuPaste.Image"), Image)
        Me.ContextMenuPaste.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuPaste.Name = "ContextMenuPaste"
        Me.ContextMenuPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.ContextMenuPaste.ShortcutKeys = CType((Keys.Control Or Keys.V), Keys)
        Me.ContextMenuPaste.Size = New Size(164, 22)
        Me.ContextMenuPaste.Text = "Paste"
        '
        'ContextMenuSelectAll
        '
        Me.ContextMenuSelectAll.ImageScaling = ToolStripItemImageScaling.None
        Me.ContextMenuSelectAll.Name = "ContextMenuSelectAll"
        Me.ContextMenuSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.ContextMenuSelectAll.ShortcutKeys = CType((Keys.Control Or Keys.A), Keys)
        Me.ContextMenuSelectAll.Size = New Size(164, 22)
        Me.ContextMenuSelectAll.Text = "Select All"
        '
        'InputFolderBrowserDialog1
        '
        Me.InputFolderBrowserDialog1.RootFolder = Environment.SpecialFolder.CommonDocuments
        Me.InputFolderBrowserDialog1.ShowNewFolderButton = False
        '
        'ButtonStopConversion
        '
        Me.ButtonStopConversion.Location = New Point(1250, 0)
        Me.ButtonStopConversion.Name = "ButtonStopConversion"
        Me.ButtonStopConversion.Size = New Size(110, 23)
        Me.ButtonStopConversion.TabIndex = 5
        Me.ButtonStopConversion.Text = "Stop Conversion"
        Me.ButtonStopConversion.UseVisualStyleBackColor = True
        Me.ButtonStopConversion.Visible = False
        '
        'LabelErrorCount
        '
        Me.LabelErrorCount.AutoSize = True
        Me.LabelErrorCount.Location = New Point(1463, 4)
        Me.LabelErrorCount.Name = "LabelErrorCount"
        Me.LabelErrorCount.Size = New Size(110, 15)
        Me.LabelErrorCount.TabIndex = 5
        Me.LabelErrorCount.Text = "Number of Errors: 0"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.BackColor = SystemColors.Control
        Me.SplitContainer1.Dock = DockStyle.Fill
        Me.SplitContainer1.FixedPanel = FixedPanel.Panel2
        Me.SplitContainer1.Location = New Point(0, 49)
        Me.SplitContainer1.Name = "SplitContainer1"
        Me.SplitContainer1.Orientation = Orientation.Horizontal
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionOutput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionOutput)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxFileList)
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxErrorList)
        Me.SplitContainer1.Size = New Size(1923, 566)
        Me.SplitContainer1.SplitterDistance = 509
        Me.SplitContainer1.SplitterWidth = 2
        Me.SplitContainer1.TabIndex = 22
        '
        'ConversionInput
        '
        Me.ConversionInput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionInput.DetectUrls = False
        Me.ConversionInput.Dock = DockStyle.Left
        Me.ConversionInput.Font = New Font("Consolas", 11.0!, FontStyle.Regular, GraphicsUnit.Point)
        Me.ConversionInput.Location = New Point(0, 0)
        Me.ConversionInput.Name = "ConversionInput"
        Me.ConversionInput.ShortcutsEnabled = True
        Me.ConversionInput.Size = New Size(950, 509)
        Me.ConversionInput.TabIndex = 0
        Me.ConversionInput.Text = ""
        Me.ConversionInput.WordWrap = False
        '
        'ConversionOutput
        '
        Me.ConversionOutput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionOutput.DetectUrls = False
        Me.ConversionOutput.Dock = DockStyle.Right
        Me.ConversionOutput.Font = New Font("Consolas", 11.0!, FontStyle.Regular, GraphicsUnit.Point)
        Me.ConversionOutput.Location = New Point(999, 0)
        Me.ConversionOutput.Name = "ConversionOutput"
        Me.ConversionOutput.ShortcutsEnabled = True
        Me.ConversionOutput.Size = New Size(924, 509)
        Me.ConversionOutput.TabIndex = 1
        Me.ConversionOutput.Text = ""
        Me.ConversionOutput.WordWrap = False
        '
        'LineNumbersForConversionInput
        '
        Me.LineNumbersForConversionInput.BackgroundGradientAlphaColor = Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionInput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Dock = DockStyle.Left
        Me.LineNumbersForConversionInput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.LineNrsOffset = New Size(0, 0)
        Me.LineNumbersForConversionInput.Location = New Point(0, 0)
        Me.LineNumbersForConversionInput.Margin = New Padding(0)
        Me.LineNumbersForConversionInput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Name = "LineNumbersForConversionInput"
        Me.LineNumbersForConversionInput.Padding = New Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionInput.ParentRichTextBox = Me.ConversionInput
        Me.LineNumbersForConversionInput.Size = New Size(23, 491)
        Me.LineNumbersForConversionInput.TabIndex = 23
        Me.LineNumbersForConversionInput.Visible = False
        '
        'LineNumbersForConversionOutput
        '
        Me.LineNumbersForConversionOutput.BackgroundGradientAlphaColor = Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionOutput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.LineNrsOffset = New Size(0, 0)
        Me.LineNumbersForConversionOutput.Location = New Point(977, 0)
        Me.LineNumbersForConversionOutput.Margin = New Padding(0)
        Me.LineNumbersForConversionOutput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.Name = "LineNumbersForConversionOutput"
        Me.LineNumbersForConversionOutput.Padding = New Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionOutput.ParentRichTextBox = Me.ConversionOutput
        Me.LineNumbersForConversionOutput.Size = New Size(21, 491)
        Me.LineNumbersForConversionOutput.TabIndex = 22
        Me.LineNumbersForConversionOutput.Visible = False
        '
        'ListBoxFileList
        '
        Me.ListBoxFileList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxFileList.Enabled = False
        Me.ListBoxFileList.ItemHeight = 15
        Me.ListBoxFileList.Location = New Point(0, 5)
        Me.ListBoxFileList.Name = "ListBoxFileList"
        Me.ListBoxFileList.Size = New Size(971, 94)
        Me.ListBoxFileList.TabIndex = 0
        '
        'ListBoxErrorList
        '
        Me.ListBoxErrorList.Anchor = CType((AnchorStyles.Top Or AnchorStyles.Right), AnchorStyles)
        Me.ListBoxErrorList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxErrorList.Enabled = False
        Me.ListBoxErrorList.ItemHeight = 15
        Me.ListBoxErrorList.Location = New Point(977, 5)
        Me.ListBoxErrorList.Name = "ListBoxErrorList"
        Me.ListBoxErrorList.Size = New Size(958, 94)
        Me.ListBoxErrorList.TabIndex = 1
        '
        'StatusStrip1
        '
        Me.StatusStrip1.Items.AddRange(New ToolStripItem() {Me.StatusStripElapasedTimeLabel, Me.StatusStripCurrentFileName, Me.StatusStripSpacer, Me.StatusStripConversionProgressBar, Me.StatusStripConversionFileProgressLabel, Me.StatusStripUpdateAvailable})
        Me.StatusStrip1.Location = New Point(0, 615)
        Me.StatusStrip1.Name = "StatusStrip1"
        Me.StatusStrip1.RenderMode = ToolStripRenderMode.Professional
        Me.StatusStrip1.ShowItemToolTips = True
        Me.StatusStrip1.Size = New Size(1923, 22)
        Me.StatusStrip1.TabIndex = 6
        Me.StatusStrip1.Text = "StatusStrip1"
        '
        'StatusStripElapasedTimeLabel
        '
        Me.StatusStripElapasedTimeLabel.AutoSize = False
        Me.StatusStripElapasedTimeLabel.BorderSides = ToolStripStatusLabelBorderSides.Right
        Me.StatusStripElapasedTimeLabel.Name = "StatusStripElapasedTimeLabel"
        Me.StatusStripElapasedTimeLabel.Size = New Size(150, 17)
        '
        'StatusStripCurrentFileName
        '
        Me.StatusStripCurrentFileName.AutoSize = False
        Me.StatusStripCurrentFileName.BorderSides = ToolStripStatusLabelBorderSides.Right
        Me.StatusStripCurrentFileName.Name = "StatusStripCurrentFileName"
        Me.StatusStripCurrentFileName.Size = New Size(500, 17)
        Me.StatusStripCurrentFileName.TextAlign = ContentAlignment.MiddleLeft
        '
        'StatusStripSpacer
        '
        Me.StatusStripSpacer.BorderSides = ToolStripStatusLabelBorderSides.Right
        Me.StatusStripSpacer.Name = "StatusStripSpacer"
        Me.StatusStripSpacer.Size = New Size(856, 17)
        Me.StatusStripSpacer.Spring = True
        '
        'StatusStripConversionProgressBar
        '
        Me.StatusStripConversionProgressBar.Alignment = ToolStripItemAlignment.Right
        Me.StatusStripConversionProgressBar.AutoSize = False
        Me.StatusStripConversionProgressBar.DisplayIncrement = 10
        Me.StatusStripConversionProgressBar.Name = "StatusStripConversionProgressBar"
        Me.StatusStripConversionProgressBar.Size = New Size(200, 16)
        Me.StatusStripConversionProgressBar.Step = 1
        Me.StatusStripConversionProgressBar.Style = ProgressBarStyle.Continuous
        Me.StatusStripConversionProgressBar.TextImageRelation = TextImageRelation.Overlay
        '
        'StatusStripConversionFileProgressLabel
        '
        Me.StatusStripConversionFileProgressLabel.AutoSize = False
        Me.StatusStripConversionFileProgressLabel.BorderSides = ToolStripStatusLabelBorderSides.Left
        Me.StatusStripConversionFileProgressLabel.Name = "StatusStripConversionFileProgressLabel"
        Me.StatusStripConversionFileProgressLabel.Size = New Size(200, 17)
        '
        'StatusStripUpdateAvailable
        '
        Me.StatusStripUpdateAvailable.DisplayStyle = ToolStripItemDisplayStyle.Image
        Me.StatusStripUpdateAvailable.Image = CType(resources.GetObject("StatusStripUpdateAvailable.Image"), Image)
        Me.StatusStripUpdateAvailable.Name = "StatusStripUpdateAvailable"
        Me.StatusStripUpdateAvailable.Size = New Size(16, 17)
        Me.StatusStripUpdateAvailable.ToolTipText = "Update Available"
        Me.StatusStripUpdateAvailable.Visible = False
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'ProjectConversionInitProgressBar
        '
        Me.ProjectConversionInitProgressBar.Location = New Point(385, 206)
        Me.ProjectConversionInitProgressBar.Name = "ProjectConversionInitProgressBar"
        Me.ProjectConversionInitProgressBar.Size = New Size(100, 23)
        Me.ProjectConversionInitProgressBar.Style = ProgressBarStyle.Marquee
        Me.ProjectConversionInitProgressBar.TabIndex = 1
        '
        'ProjectConversionInitProgressLabel
        '
        Me.ProjectConversionInitProgressLabel.AutoSize = True
        Me.ProjectConversionInitProgressLabel.Location = New Point(385, 196)
        Me.ProjectConversionInitProgressLabel.Name = "ProjectConversionInitProgressLabel"
        Me.ProjectConversionInitProgressLabel.Size = New Size(30, 15)
        Me.ProjectConversionInitProgressLabel.TabIndex = 1
        Me.ProjectConversionInitProgressLabel.Text = "Step"
        Me.ProjectConversionInitProgressLabel.Visible = False
        '
        'ToolTipFileList
        '
        Me.ToolTipFileList.ToolTipIcon = ToolTipIcon.Info
        '
        'ToolTipErrorList
        '
        Me.ToolTipErrorList.ToolTipIcon = ToolTipIcon.Info
        '
        'Form1
        '
        Me.AutoScaleDimensions = New SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = AutoScaleMode.Font
        Me.ClientSize = New Size(1923, 637)
        Me.Controls.Add(Me.ProjectConversionInitProgressBar)
        Me.Controls.Add(Me.ProjectConversionInitProgressLabel)
        Me.Controls.Add(Me.LabelErrorCount)
        Me.Controls.Add(Me.ButtonStopConversion)
        Me.Controls.Add(Me.SplitContainer1)
        Me.Controls.Add(Me.TSFindToolStrip)
        Me.Controls.Add(Me.MenuStrip1)
        Me.Controls.Add(Me.StatusStrip1)
        Me.Font = New Font("Segoe UI", 9.0!, FontStyle.Regular, GraphicsUnit.Point)
        Me.Icon = CType(resources.GetObject("$this.Icon"), Icon)
        Me.KeyPreview = True
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Name = "Form1"
        Me.StartPosition = FormStartPosition.CenterScreen
        Me.Text = "Convert C# to Visual Basic"
        Me.MenuStrip1.ResumeLayout(False)
        Me.MenuStrip1.PerformLayout()
        Me.TSFindToolStrip.ResumeLayout(False)
        Me.TSFindToolStrip.PerformLayout()
        Me.ContextMenuStrip1.ResumeLayout(False)
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        Me.StatusStrip1.ResumeLayout(False)
        Me.StatusStrip1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents ButtonStopConversion As Button
    Friend WithEvents ContextMenuCopy As ToolStripMenuItem
    Friend WithEvents ContextMenuCut As ToolStripMenuItem
    Friend WithEvents ContextMenuPaste As ToolStripMenuItem
    Friend WithEvents ContextMenuRedo As ToolStripMenuItem
    Friend WithEvents ContextMenuSelectAll As ToolStripMenuItem
    Friend WithEvents ContextMenuSeparator1 As ToolStripSeparator
    Friend WithEvents ContextMenuStrip1 As ContextMenuStrip
    Friend WithEvents ContextMenuUndo As ToolStripMenuItem
    Friend WithEvents ConversionInput As RichTextBox
    Friend WithEvents ConversionOutput As RichTextBox
    Friend WithEvents InputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents LabelErrorCount As Label
    Friend WithEvents LineNumbersForConversionInput As LineNumbersForRichTextBox
    Friend WithEvents LineNumbersForConversionOutput As LineNumbersForRichTextBox
    Friend WithEvents ListBoxErrorList As ListBox
    Friend WithEvents ListBoxFileList As ListBox
    Friend WithEvents MenuStrip1 As MenuStrip
    Friend WithEvents mnuCompile As ToolStripMenuItem
    Friend WithEvents mnuConvert As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertFolder As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertSnippet As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertTopLevelStmts As ToolStripMenuItem
    Friend WithEvents mnuConvertSep1 As ToolStripSeparator
    Friend WithEvents mnuConvertStartFolderConvertFromLastFile As ToolStripMenuItem
    Friend WithEvents mnuEdit As ToolStripMenuItem
    Friend WithEvents mnuEditCopy As ToolStripMenuItem
    Friend WithEvents mnuEditCut As ToolStripMenuItem
    Friend WithEvents mnuEditFind As ToolStripMenuItem
    Friend WithEvents mnuEditPaste As ToolStripMenuItem
    Friend WithEvents mnuEditRedo As ToolStripMenuItem
    Friend WithEvents mnuEditSelectAll As ToolStripMenuItem
    Friend WithEvents mnuEditSep1 As ToolStripSeparator
    Friend WithEvents mnuEditSep2 As ToolStripSeparator
    Friend WithEvents mnuEditUndo As ToolStripMenuItem
    Friend WithEvents mnuFile As ToolStripMenuItem
    Friend WithEvents mnuFileConvertProject As ToolStripMenuItem
    Friend WithEvents mnuFileExit As ToolStripMenuItem
    Friend WithEvents mnuFileLabelLastFolder As ToolStripMenuItem
    Friend WithEvents mnuFileLastFolder As ToolStripMenuItem
    Friend WithEvents mnuFileLastProject As ToolStripMenuItem
    Friend WithEvents mnuFileLastSolution As ToolStripMenuItem
    Friend WithEvents mnuFileLoadLastSnippet As ToolStripMenuItem
    Friend WithEvents mnuFileOpen As ToolStripMenuItem
    Friend WithEvents mnuFileSaveAs As ToolStripMenuItem
    Friend WithEvents mnuFileSaveSnippet As ToolStripMenuItem
    Friend WithEvents mnuFileSep1 As ToolStripSeparator
    Friend WithEvents mnuFileSep2 As ToolStripSeparator
    Friend WithEvents mnuFileSep3 As ToolStripSeparator
    Friend WithEvents mnuFileSep4 As ToolStripSeparator
    Friend WithEvents mnuHelp As ToolStripMenuItem
    Friend WithEvents mnuHelpAboutMenuItem As ToolStripMenuItem
    Friend WithEvents mnuHelpCheckForUpdatesMenuItem As ToolStripMenuItem
    Friend WithEvents mnuHelpReportIssueMenuItem As ToolStripMenuItem
    Friend WithEvents mnuOptions As ToolStripMenuItem
    Friend WithEvents mnuOptionsAddFilesToIgnoreFilesEithErrorsList As ToolStripMenuItem
    Friend WithEvents mnuOptionsAdvanced As ToolStripMenuItem
    Friend WithEvents mnuOptionsColorizeResult As ToolStripMenuItem
    Friend WithEvents mnuOptionsColorizeSource As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFramework As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkCore As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFull As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFullAnyCore As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFullAnyFull As ToolStripMenuItem
    Friend WithEvents mnuOptionsDelayBetweenConversions As ToolStripComboBox
    Friend WithEvents mnuOptionsEditIgnoreFilesWithErrorsList As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptions As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipAutoGenerated As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipTestResourceFiles As ToolStripMenuItem
    Friend WithEvents mnuOptionsPauseConvertOnSuccess As ToolStripMenuItem
    Friend WithEvents mnuOptionsSep1 As ToolStripSeparator
    Friend WithEvents mnuOptionsSep2 As ToolStripSeparator
    Friend WithEvents mnuOptionsSep3 As ToolStripSeparator
    Friend WithEvents mnuView As ToolStripMenuItem
    Friend WithEvents mnuViewShowDestinationLineNumbers As ToolStripMenuItem
    Friend WithEvents mnuViewShowSourceLineNumbers As ToolStripMenuItem
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents ProjectConversionInitProgressBar As ProgressBar
    Friend WithEvents ProjectConversionInitProgressLabel As Label
    Friend WithEvents SaveFileDialog1 As SaveFileDialog
    Friend WithEvents SplitContainer1 As SplitContainer
    Friend WithEvents StatusStrip1 As StatusStrip
    Friend WithEvents StatusStripConversionFileProgressLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripConversionProgressBar As ToolStripTextProgressBar
    Friend WithEvents StatusStripCurrentFileName As ToolStripStatusLabel
    Friend WithEvents StatusStripElapasedTimeLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripSpacer As ToolStripStatusLabel
    Friend WithEvents StatusStripUpdateAvailable As ToolStripStatusLabel
    Friend WithEvents ToolTipErrorList As ToolTip
    Friend WithEvents ToolTipFileList As ToolTip
    Friend WithEvents TSFindClearHighlightsButton As ToolStripButton
    Friend WithEvents TSFindFindNextButton As ToolStripButton
    Friend WithEvents TSFindFindPreviousButton As ToolStripButton
    Friend WithEvents TSFindFindWhatComboBox As ToolStripComboBox
    Friend WithEvents TSFindLookInComboBox As ToolStripComboBox
    Friend WithEvents TSFindLookInLabel As ToolStripLabel
    Friend WithEvents TSFindMatchCaseCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindMatchWholeWordCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindSeparator1 As ToolStripSeparator
    Friend WithEvents TSFindSeparator2 As ToolStripSeparator
    Friend WithEvents TSFindSeparator3 As ToolStripSeparator
    Friend WithEvents TSFindSeparator4 As ToolStripSeparator
    Friend WithEvents TSFindSeparator5 As ToolStripSeparator
    Friend WithEvents TSFindToolStrip As ToolStrip
    Friend WithEvents TSThemeButton As ToolStripButton
End Class
