<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(disposing As Boolean)
        Try
            If disposing Then
                If components IsNot Nothing Then
                    components.Dispose()
                End If
                If _cancellationTokenSource IsNot Nothing Then
                    _cancellationTokenSource.Dispose()
                End If
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    '<System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
        Me.mnuFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileOpen = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLoadLastSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSaveSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileLabelLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep3 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileConvertProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastSolution = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSaveAs = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep4 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileExit = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEdit = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditFind = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuEditUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuEditCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditSelectAll = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuCompile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvert = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvertConvertFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvertConvertSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvertSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuConvertStartFolderConvertFromLastFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptions = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsColorizeResult = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsColorizeSource = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDelayBetweenConversions = New System.Windows.Forms.ToolStripComboBox()
        Me.mnuOptionsSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsEditIgnoreFilesWithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuOptionsFolderConversionsOptions = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsPauseConvertOnSuccess = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSep3 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuOptionsDefaultFramework = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkCore = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFullAnyCore = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFull = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDefaultFrameworkFullAnyFull = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsAdvanced = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuView = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuViewShowSourceLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuViewShowDestinationLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelp = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelpReportIssueMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelpCheckForUpdatesMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelpAboutMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.TSFindToolStrip = New System.Windows.Forms.ToolStrip()
        Me.TSFindFindWhatComboBox = New System.Windows.Forms.ToolStripComboBox()
        Me.TSFindSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindLookInLabel = New System.Windows.Forms.ToolStripLabel()
        Me.TSFindLookInComboBox = New System.Windows.Forms.ToolStripComboBox()
        Me.TSFindSeparator2 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindFindPreviousButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindFindNextButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindSeparator3 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindMatchCaseCheckBox = New ToolStripCheckBox()
        Me.TSFindMatchWholeWordCheckBox = New ToolStripCheckBox()
        Me.TSFindSeparator4 = New System.Windows.Forms.ToolStripSeparator()
        Me.TSFindClearHighlightsButton = New System.Windows.Forms.ToolStripButton()
        Me.TSFindSeparator5 = New System.Windows.Forms.ToolStripSeparator()
        Me.SaveFileDialog1 = New System.Windows.Forms.SaveFileDialog()
        Me.ContextMenuStrip1 = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.ContextMenuUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.ContextMenuCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuSelectAll = New System.Windows.Forms.ToolStripMenuItem()
        Me.InputFolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog()
        Me.ButtonStopConversion = New System.Windows.Forms.Button()
        Me.LabelErrorCount = New System.Windows.Forms.Label()
        Me.SplitContainer1 = New System.Windows.Forms.SplitContainer()
        Me.ConversionInput = New System.Windows.Forms.RichTextBox()
        Me.LineNumbersForConversionInput = New LineNumbersForRichTextBox()
        Me.ConversionOutput = New System.Windows.Forms.RichTextBox()
        Me.LineNumbersForConversionOutput = New LineNumbersForRichTextBox()
        Me.ListBoxFileList = New System.Windows.Forms.ListBox()
        Me.ListBoxErrorList = New System.Windows.Forms.ListBox()
        Me.StatusStrip1 = New System.Windows.Forms.StatusStrip()
        Me.StatusStripElapasedTimeLabel = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripCurrentFileName = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripSpacer = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripConversionProgressBar = New ToolStripTextProgressBar()
        Me.StatusStripConversionFileProgressLabel = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripUpdateAvailable = New System.Windows.Forms.ToolStripStatusLabel()
        Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
        Me.ProjectConversionInitProgressBar = New System.Windows.Forms.ProgressBar()
        Me.ProjectConversionInitProgressLabel = New System.Windows.Forms.Label()
        Me.ToolTipFileList = New System.Windows.Forms.ToolTip(Me.components)
        Me.ToolTipErrorList = New System.Windows.Forms.ToolTip(Me.components)
        Me.MenuStrip1.SuspendLayout()
        Me.TSFindToolStrip.SuspendLayout()
        Me.ContextMenuStrip1.SuspendLayout()
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        Me.StatusStrip1.SuspendLayout()
        Me.SuspendLayout()
        '
        'MenuStrip1
        '
        Me.MenuStrip1.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.MenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuFile, Me.mnuEdit, Me.mnuCompile, Me.mnuConvert, Me.mnuOptions, Me.mnuView, Me.mnuHelp})
        Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Padding = New System.Windows.Forms.Padding(7, 2, 0, 2)
        Me.MenuStrip1.Size = New System.Drawing.Size(1923, 24)
        Me.MenuStrip1.TabIndex = 0
        '
        'mnuFile
        '
        Me.mnuFile.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuFileOpen, Me.mnuFileLoadLastSnippet, Me.mnuFileSaveSnippet, Me.mnuFileSep1, Me.mnuFileSep2, Me.mnuFileLabelLastFolder, Me.mnuFileLastFolder, Me.mnuFileSep3, Me.mnuFileConvertProject, Me.mnuFileLastProject, Me.mnuFileLastSolution, Me.mnuFileSaveAs, Me.mnuFileSep4, Me.mnuFileExit})
        Me.mnuFile.Name = "mnuFile"
        Me.mnuFile.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuFile.Size = New System.Drawing.Size(37, 20)
        Me.mnuFile.Text = "&File"
        '
        'mnuFileOpen
        '
        Me.mnuFileOpen.Image = CType(resources.GetObject("mnuFileOpen.Image"), System.Drawing.Image)
        Me.mnuFileOpen.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileOpen.Name = "mnuFileOpen"
        Me.mnuFileOpen.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuFileOpen.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileOpen.Text = "Open C# File..."
        '
        'mnuFileLoadLastSnippet
        '
        Me.mnuFileLoadLastSnippet.Enabled = False
        Me.mnuFileLoadLastSnippet.Name = "mnuFileLoadLastSnippet"
        Me.mnuFileLoadLastSnippet.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLoadLastSnippet.Text = "Load Last Snippet"
        '
        'mnuFileSaveSnippet
        '
        Me.mnuFileSaveSnippet.Enabled = False
        Me.mnuFileSaveSnippet.Name = "mnuFileSaveSnippet"
        Me.mnuFileSaveSnippet.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileSaveSnippet.Text = "Save Snippet"
        '
        'mnuFileSep1
        '
        Me.mnuFileSep1.Name = "mnuFileSep1"
        Me.mnuFileSep1.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileSep2
        '
        Me.mnuFileSep2.Name = "mnuFileSep2"
        Me.mnuFileSep2.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileLabelLastFolder
        '
        Me.mnuFileLabelLastFolder.Enabled = False
        Me.mnuFileLabelLastFolder.Name = "mnuFileLabelLastFolder"
        Me.mnuFileLabelLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLabelLastFolder.Text = "Last Converted Folder"
        '
        'mnuFileLastFolder
        '
        Me.mnuFileLastFolder.Name = "mnuFileLastFolder"
        Me.mnuFileLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastFolder.Visible = False
        '
        'mnuFileSep3
        '
        Me.mnuFileSep3.Name = "mnuFileSep3"
        Me.mnuFileSep3.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileConvertProject
        '
        Me.mnuFileConvertProject.Image = CType(resources.GetObject("mnuFileConvertProject.Image"), System.Drawing.Image)
        Me.mnuFileConvertProject.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileConvertProject.Name = "mnuFileConvertProject"
        Me.mnuFileConvertProject.ShortcutKeys = CType(((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Shift) _
            Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuFileConvertProject.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileConvertProject.Text = "Convert Project/Solution..."
        '
        'mnuFileLastProject
        '
        Me.mnuFileLastProject.Enabled = False
        Me.mnuFileLastProject.Name = "mnuFileLastProject"
        Me.mnuFileLastProject.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastProject.Text = "Open Last Project"
        '
        'mnuFileLastSolution
        '
        Me.mnuFileLastSolution.Enabled = False
        Me.mnuFileLastSolution.Name = "mnuFileLastSolution"
        Me.mnuFileLastSolution.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastSolution.Text = "Open Last Solution"
        '
        'mnuFileSaveAs
        '
        Me.mnuFileSaveAs.Enabled = False
        Me.mnuFileSaveAs.Image = CType(resources.GetObject("mnuFileSaveAs.Image"), System.Drawing.Image)
        Me.mnuFileSaveAs.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileSaveAs.Name = "mnuFileSaveAs"
        Me.mnuFileSaveAs.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.mnuFileSaveAs.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileSaveAs.Text = "Save Visual Basic File &As..."
        '
        'mnuFileSep4
        '
        Me.mnuFileSep4.Name = "mnuFileSep4"
        Me.mnuFileSep4.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileExit
        '
        Me.mnuFileExit.Name = "mnuFileExit"
        Me.mnuFileExit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.mnuFileExit.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileExit.Text = "E&xit"
        '
        'mnuEdit
        '
        Me.mnuEdit.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuEditFind, Me.mnuEditSep1, Me.mnuEditUndo, Me.mnuEditRedo, Me.mnuEditSep2, Me.mnuEditCut, Me.mnuEditCopy, Me.mnuEditPaste, Me.mnuEditSelectAll})
        Me.mnuEdit.Name = "mnuEdit"
        Me.mnuEdit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.E), System.Windows.Forms.Keys)
        Me.mnuEdit.Size = New System.Drawing.Size(39, 20)
        Me.mnuEdit.Text = "&Edit"
        '
        'mnuEditFind
        '
        Me.mnuEditFind.Image = CType(resources.GetObject("mnuEditFind.Image"), System.Drawing.Image)
        Me.mnuEditFind.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditFind.Name = "mnuEditFind"
        Me.mnuEditFind.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuEditFind.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditFind.Text = "&Find..."
        '
        'mnuEditSep1
        '
        Me.mnuEditSep1.Name = "mnuEditSep1"
        Me.mnuEditSep1.Size = New System.Drawing.Size(161, 6)
        '
        'mnuEditUndo
        '
        Me.mnuEditUndo.Image = CType(resources.GetObject("mnuEditUndo.Image"), System.Drawing.Image)
        Me.mnuEditUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditUndo.Name = "mnuEditUndo"
        Me.mnuEditUndo.ShortcutKeyDisplayString = "Ctrl+Z"
        Me.mnuEditUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.mnuEditUndo.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditUndo.Text = "Undo"
        '
        'mnuEditRedo
        '
        Me.mnuEditRedo.Image = CType(resources.GetObject("mnuEditRedo.Image"), System.Drawing.Image)
        Me.mnuEditRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditRedo.Name = "mnuEditRedo"
        Me.mnuEditRedo.ShortcutKeyDisplayString = "Ctrl+Y"
        Me.mnuEditRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.mnuEditRedo.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditRedo.Text = "Redo"
        '
        'mnuEditSep2
        '
        Me.mnuEditSep2.Name = "mnuEditSep2"
        Me.mnuEditSep2.Size = New System.Drawing.Size(161, 6)
        '
        'mnuEditCut
        '
        Me.mnuEditCut.Image = CType(resources.GetObject("mnuEditCut.Image"), System.Drawing.Image)
        Me.mnuEditCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditCut.Name = "mnuEditCut"
        Me.mnuEditCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.mnuEditCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.mnuEditCut.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditCut.Text = "Cut"
        '
        'mnuEditCopy
        '
        Me.mnuEditCopy.Image = CType(resources.GetObject("mnuEditCopy.Image"), System.Drawing.Image)
        Me.mnuEditCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditCopy.Name = "mnuEditCopy"
        Me.mnuEditCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.mnuEditCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.mnuEditCopy.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditCopy.Text = "Copy"
        '
        'mnuEditPaste
        '
        Me.mnuEditPaste.Image = CType(resources.GetObject("mnuEditPaste.Image"), System.Drawing.Image)
        Me.mnuEditPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditPaste.Name = "mnuEditPaste"
        Me.mnuEditPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.mnuEditPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.mnuEditPaste.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditPaste.Text = "Paste"
        '
        'mnuEditSelectAll
        '
        Me.mnuEditSelectAll.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditSelectAll.Name = "mnuEditSelectAll"
        Me.mnuEditSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.mnuEditSelectAll.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.mnuEditSelectAll.Size = New System.Drawing.Size(164, 22)
        Me.mnuEditSelectAll.Text = "Select All"
        '
        'mnuCompile
        '
        Me.mnuCompile.Enabled = False
        Me.mnuCompile.Name = "mnuCompile"
        Me.mnuCompile.Size = New System.Drawing.Size(64, 20)
        Me.mnuCompile.Text = "Compile"
        '
        'mnuConvert
        '
        Me.mnuConvert.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuConvertConvertFolder, Me.mnuConvertConvertSnippet, Me.mnuConvertSep1, Me.mnuConvertStartFolderConvertFromLastFile})
        Me.mnuConvert.Name = "mnuConvert"
        Me.mnuConvert.Size = New System.Drawing.Size(61, 20)
        Me.mnuConvert.Text = "Convert"
        '
        'mnuConvertConvertFolder
        '
        Me.mnuConvertConvertFolder.Image = CType(resources.GetObject("mnuConvertConvertFolder.Image"), System.Drawing.Image)
        Me.mnuConvertConvertFolder.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuConvertConvertFolder.Name = "mnuConvertConvertFolder"
        Me.mnuConvertConvertFolder.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuConvertConvertFolder.Size = New System.Drawing.Size(237, 22)
        Me.mnuConvertConvertFolder.Text = "Convert Folder"
        '
        'mnuConvertConvertSnippet
        '
        Me.mnuConvertConvertSnippet.Enabled = False
        Me.mnuConvertConvertSnippet.Image = CType(resources.GetObject("mnuConvertConvertSnippet.Image"), System.Drawing.Image)
        Me.mnuConvertConvertSnippet.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuConvertConvertSnippet.Name = "mnuConvertConvertSnippet"
        Me.mnuConvertConvertSnippet.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.S), System.Windows.Forms.Keys)
        Me.mnuConvertConvertSnippet.Size = New System.Drawing.Size(237, 22)
        Me.mnuConvertConvertSnippet.Text = "Convert Snippet"
        '
        'mnuConvertSep1
        '
        Me.mnuConvertSep1.Name = "mnuConvertSep1"
        Me.mnuConvertSep1.Size = New System.Drawing.Size(234, 6)
        '
        'mnuConvertStartFolderConvertFromLastFile
        '
        Me.mnuConvertStartFolderConvertFromLastFile.Checked = True
        Me.mnuConvertStartFolderConvertFromLastFile.CheckOnClick = True
        Me.mnuConvertStartFolderConvertFromLastFile.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuConvertStartFolderConvertFromLastFile.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuConvertStartFolderConvertFromLastFile.Name = "mnuConvertStartFolderConvertFromLastFile"
        Me.mnuConvertStartFolderConvertFromLastFile.Size = New System.Drawing.Size(237, 22)
        Me.mnuConvertStartFolderConvertFromLastFile.Text = "Start Conversion From Last File"
        '
        'mnuOptions
        '
        Me.mnuOptions.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsColorizeResult, Me.mnuOptionsColorizeSource, Me.mnuOptionsDelayBetweenConversions, Me.mnuOptionsSep1, Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList, Me.mnuOptionsEditIgnoreFilesWithErrorsList, Me.mnuOptionsSep2, Me.mnuOptionsFolderConversionsOptions, Me.mnuOptionsPauseConvertOnSuccess, Me.mnuOptionsSep3, Me.mnuOptionsDefaultFramework, Me.mnuOptionsAdvanced})
        Me.mnuOptions.Name = "mnuOptions"
        Me.mnuOptions.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuOptions.Size = New System.Drawing.Size(61, 20)
        Me.mnuOptions.Text = "&Options"
        '
        'mnuOptionsColorizeResult
        '
        Me.mnuOptionsColorizeResult.CheckOnClick = True
        Me.mnuOptionsColorizeResult.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeResult.Name = "mnuOptionsColorizeResult"
        Me.mnuOptionsColorizeResult.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsColorizeResult.Text = "Colorize Result"
        '
        'mnuOptionsColorizeSource
        '
        Me.mnuOptionsColorizeSource.CheckOnClick = True
        Me.mnuOptionsColorizeSource.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeSource.Name = "mnuOptionsColorizeSource"
        Me.mnuOptionsColorizeSource.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsColorizeSource.Text = "Colorize Source"
        '
        'mnuOptionsDelayBetweenConversions
        '
        Me.mnuOptionsDelayBetweenConversions.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.mnuOptionsDelayBetweenConversions.Items.AddRange(New Object() {"Delay Between Conversions = None", "Delay Between Conversions = 5 Seconds", "Delay Between Conversions = 10 Seconds"})
        Me.mnuOptionsDelayBetweenConversions.MaxDropDownItems = 3
        Me.mnuOptionsDelayBetweenConversions.Name = "mnuOptionsDelayBetweenConversions"
        Me.mnuOptionsDelayBetweenConversions.Size = New System.Drawing.Size(300, 23)
        '
        'mnuOptionsSep1
        '
        Me.mnuOptionsSep1.Name = "mnuOptionsSep1"
        Me.mnuOptionsSep1.Size = New System.Drawing.Size(357, 6)
        '
        'mnuOptionsAddFilesToIgnoreFilesEithErrorsList
        '
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image = CType(resources.GetObject("mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image"), System.Drawing.Image)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Name = "mnuOptionsAddFilesToIgnoreFilesEithErrorsList"
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Text = "Add File to the ""Ignore files with errors list"""
        '
        'mnuOptionsEditIgnoreFilesWithErrorsList
        '
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Name = "mnuOptionsEditIgnoreFilesWithErrorsList"
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Text = "Show/Edit the ""Ignore files with errors"" list..."
        '
        'mnuOptionsSep2
        '
        Me.mnuOptionsSep2.Name = "mnuOptionsSep2"
        Me.mnuOptionsSep2.Size = New System.Drawing.Size(357, 6)
        '
        'mnuOptionsFolderConversionsOptions
        '
        Me.mnuOptionsFolderConversionsOptions.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated, Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders, Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles})
        Me.mnuOptionsFolderConversionsOptions.Name = "mnuOptionsFolderConversionsOptions"
        Me.mnuOptionsFolderConversionsOptions.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsFolderConversionsOptions.Text = "Folder Conversions Options"
        '
        'mnuOptionsFolderConversionsOptionsSkipAutoGenerated
        '
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Name = "mnuOptionsFolderConversionsOptionsSkipAutoGenerated"
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipAutoGenerated.Text = "Skip Auto Generated"
        '
        'mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders
        '
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Name = "mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders"
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders.Text = "Skip Bin and Obj Folders"
        '
        'mnuOptionsFolderConversionsOptionsSkipTestResourceFiles
        '
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Checked = True
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckOnClick = True
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Name = "mnuOptionsFolderConversionsOptionsSkipTestResourceFiles"
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsFolderConversionsOptionsSkipTestResourceFiles.Text = "Skip Test/Resource Files"
        '
        'mnuOptionsPauseConvertOnSuccess
        '
        Me.mnuOptionsPauseConvertOnSuccess.CheckOnClick = True
        Me.mnuOptionsPauseConvertOnSuccess.Image = CType(resources.GetObject("mnuOptionsPauseConvertOnSuccess.Image"), System.Drawing.Image)
        Me.mnuOptionsPauseConvertOnSuccess.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsPauseConvertOnSuccess.Name = "mnuOptionsPauseConvertOnSuccess"
        Me.mnuOptionsPauseConvertOnSuccess.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsPauseConvertOnSuccess.Text = "Pause Conversion on Success"
        '
        'mnuOptionsSep3
        '
        Me.mnuOptionsSep3.Name = "mnuOptionsSep3"
        Me.mnuOptionsSep3.Size = New System.Drawing.Size(357, 6)
        '
        'mnuOptionsDefaultFramework
        '
        Me.mnuOptionsDefaultFramework.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsDefaultFrameworkCore, Me.mnuOptionsDefaultFrameworkFull})
        Me.mnuOptionsDefaultFramework.Name = "mnuOptionsDefaultFramework"
        Me.mnuOptionsDefaultFramework.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsDefaultFramework.Text = "Default Framework For Conversion"
        '
        'mnuOptionsDefaultFrameworkCore
        '
        Me.mnuOptionsDefaultFrameworkCore.Checked = True
        Me.mnuOptionsDefaultFrameworkCore.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsDefaultFrameworkCore.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsDefaultFrameworkFullAnyCore})
        Me.mnuOptionsDefaultFrameworkCore.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkCore.Name = "mnuOptionsDefaultFrameworkCore"
        Me.mnuOptionsDefaultFrameworkCore.Size = New System.Drawing.Size(180, 22)
        Me.mnuOptionsDefaultFrameworkCore.Text = ".Net Core"
        '
        'mnuOptionsDefaultFrameworkFullAnyCore
        '
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Checked = True
        Me.mnuOptionsDefaultFrameworkFullAnyCore.CheckOnClick = True
        Me.mnuOptionsDefaultFrameworkFullAnyCore.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsDefaultFrameworkFullAnyCore.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Name = "mnuOptionsDefaultFrameworkFullAnyCore"
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Size = New System.Drawing.Size(146, 22)
        Me.mnuOptionsDefaultFrameworkFullAnyCore.Text = "NETCOREAPP"
        '
        'mnuOptionsDefaultFrameworkFull
        '
        Me.mnuOptionsDefaultFrameworkFull.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsDefaultFrameworkFullAnyFull})
        Me.mnuOptionsDefaultFrameworkFull.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFull.Name = "mnuOptionsDefaultFrameworkFull"
        Me.mnuOptionsDefaultFrameworkFull.Size = New System.Drawing.Size(180, 22)
        Me.mnuOptionsDefaultFrameworkFull.Text = ".Net Full Framework"
        '
        'mnuOptionsDefaultFrameworkFullAnyFull
        '
        Me.mnuOptionsDefaultFrameworkFullAnyFull.CheckOnClick = True
        Me.mnuOptionsDefaultFrameworkFullAnyFull.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Name = "mnuOptionsDefaultFrameworkFullAnyFull"
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Size = New System.Drawing.Size(167, 22)
        Me.mnuOptionsDefaultFrameworkFullAnyFull.Text = "NETFRAMEWORK"
        '
        'mnuOptionsAdvanced
        '
        Me.mnuOptionsAdvanced.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsAdvanced.Name = "mnuOptionsAdvanced"
        Me.mnuOptionsAdvanced.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsAdvanced.Text = "Advanced Options..."
        '
        'mnuView
        '
        Me.mnuView.CheckOnClick = True
        Me.mnuView.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuViewShowSourceLineNumbers, Me.mnuViewShowDestinationLineNumbers})
        Me.mnuView.Name = "mnuView"
        Me.mnuView.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.mnuView.Size = New System.Drawing.Size(44, 20)
        Me.mnuView.Text = "&View"
        '
        'mnuViewShowSourceLineNumbers
        '
        Me.mnuViewShowSourceLineNumbers.CheckOnClick = True
        Me.mnuViewShowSourceLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuViewShowSourceLineNumbers.Name = "mnuViewShowSourceLineNumbers"
        Me.mnuViewShowSourceLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.mnuViewShowSourceLineNumbers.Text = "Show Source Line Numbers"
        '
        'mnuViewShowDestinationLineNumbers
        '
        Me.mnuViewShowDestinationLineNumbers.CheckOnClick = True
        Me.mnuViewShowDestinationLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuViewShowDestinationLineNumbers.Name = "mnuViewShowDestinationLineNumbers"
        Me.mnuViewShowDestinationLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.mnuViewShowDestinationLineNumbers.Text = "Show Destination Line Numbers"
        '
        'mnuHelp
        '
        Me.mnuHelp.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuHelpReportIssueMenuItem, Me.mnuHelpCheckForUpdatesMenuItem, Me.mnuHelpAboutMenuItem})
        Me.mnuHelp.Name = "mnuHelp"
        Me.mnuHelp.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.H), System.Windows.Forms.Keys)
        Me.mnuHelp.Size = New System.Drawing.Size(44, 20)
        Me.mnuHelp.Text = "&Help"
        '
        'mnuHelpReportIssueMenuItem
        '
        Me.mnuHelpReportIssueMenuItem.Image = CType(resources.GetObject("mnuHelpReportIssueMenuItem.Image"), System.Drawing.Image)
        Me.mnuHelpReportIssueMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuHelpReportIssueMenuItem.Name = "mnuHelpReportIssueMenuItem"
        Me.mnuHelpReportIssueMenuItem.Size = New System.Drawing.Size(177, 22)
        Me.mnuHelpReportIssueMenuItem.Text = "Report A Problem..."
        '
        'mnuHelpCheckForUpdatesMenuItem
        '
        Me.mnuHelpCheckForUpdatesMenuItem.Name = "mnuHelpCheckForUpdatesMenuItem"
        Me.mnuHelpCheckForUpdatesMenuItem.Size = New System.Drawing.Size(177, 22)
        Me.mnuHelpCheckForUpdatesMenuItem.Text = "Check For Updates"
        '
        'mnuHelpAboutMenuItem
        '
        Me.mnuHelpAboutMenuItem.Name = "mnuHelpAboutMenuItem"
        Me.mnuHelpAboutMenuItem.Size = New System.Drawing.Size(177, 22)
        Me.mnuHelpAboutMenuItem.Text = "About"
        '
        'TSFindToolStrip
        '
        Me.TSFindToolStrip.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.TSFindToolStrip.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.TSFindFindWhatComboBox, Me.TSFindSeparator1, Me.TSFindLookInLabel, Me.TSFindLookInComboBox, Me.TSFindSeparator2, Me.TSFindFindPreviousButton, Me.TSFindFindNextButton, Me.TSFindSeparator3, Me.TSFindMatchCaseCheckBox, Me.TSFindMatchWholeWordCheckBox, Me.TSFindSeparator4, Me.TSFindClearHighlightsButton, Me.TSFindSeparator5})
        Me.TSFindToolStrip.Location = New System.Drawing.Point(0, 24)
        Me.TSFindToolStrip.Name = "TSFindToolStrip"
        Me.TSFindToolStrip.Size = New System.Drawing.Size(1923, 25)
        Me.TSFindToolStrip.TabIndex = 2
        Me.TSFindToolStrip.Text = "ToolStrip1"
        '
        'TSFindFindWhatComboBox
        '
        Me.TSFindFindWhatComboBox.AutoSize = False
        Me.TSFindFindWhatComboBox.ForeColor = System.Drawing.SystemColors.GrayText
        Me.TSFindFindWhatComboBox.Name = "TSFindFindWhatComboBox"
        Me.TSFindFindWhatComboBox.Size = New System.Drawing.Size(400, 23)
        Me.TSFindFindWhatComboBox.Text = "Search..."
        '
        'TSFindSeparator1
        '
        Me.TSFindSeparator1.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator1.Name = "TSFindSeparator1"
        Me.TSFindSeparator1.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindLookInLabel
        '
        Me.TSFindLookInLabel.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindLookInLabel.Name = "TSFindLookInLabel"
        Me.TSFindLookInLabel.Size = New System.Drawing.Size(49, 25)
        Me.TSFindLookInLabel.Text = "Look In:"
        '
        'TSFindLookInComboBox
        '
        Me.TSFindLookInComboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems
        Me.TSFindLookInComboBox.Items.AddRange(New Object() {"C# Source", "Visual Basic Output", "Both"})
        Me.TSFindLookInComboBox.MaxDropDownItems = 3
        Me.TSFindLookInComboBox.Name = "TSFindLookInComboBox"
        Me.TSFindLookInComboBox.Size = New System.Drawing.Size(130, 25)
        '
        'TSFindSeparator2
        '
        Me.TSFindSeparator2.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator2.Name = "TSFindSeparator2"
        Me.TSFindSeparator2.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindFindPreviousButton
        '
        Me.TSFindFindPreviousButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindFindPreviousButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindFindPreviousButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindFindPreviousButton.Name = "TSFindFindPreviousButton"
        Me.TSFindFindPreviousButton.Size = New System.Drawing.Size(82, 25)
        Me.TSFindFindPreviousButton.Text = "Find Previous"
        '
        'TSFindFindNextButton
        '
        Me.TSFindFindNextButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindFindNextButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindFindNextButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindFindNextButton.Name = "TSFindFindNextButton"
        Me.TSFindFindNextButton.Size = New System.Drawing.Size(62, 25)
        Me.TSFindFindNextButton.Text = "Find Next"
        '
        'TSFindSeparator3
        '
        Me.TSFindSeparator3.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator3.Name = "TSFindSeparator3"
        Me.TSFindSeparator3.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindMatchCaseCheckBox
        '
        Me.TSFindMatchCaseCheckBox.Checked = False
        Me.TSFindMatchCaseCheckBox.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindMatchCaseCheckBox.Name = "TSFindMatchCaseCheckBox"
        Me.TSFindMatchCaseCheckBox.Size = New System.Drawing.Size(88, 25)
        Me.TSFindMatchCaseCheckBox.Text = "Match Case"
        '
        'TSFindMatchWholeWordCheckBox
        '
        Me.TSFindMatchWholeWordCheckBox.Checked = False
        Me.TSFindMatchWholeWordCheckBox.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindMatchWholeWordCheckBox.Name = "TSFindMatchWholeWordCheckBox"
        Me.TSFindMatchWholeWordCheckBox.Size = New System.Drawing.Size(129, 25)
        Me.TSFindMatchWholeWordCheckBox.Text = "Match Whole Word"
        '
        'TSFindSeparator4
        '
        Me.TSFindSeparator4.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator4.Name = "TSFindSeparator4"
        Me.TSFindSeparator4.Size = New System.Drawing.Size(6, 25)
        '
        'TSFindClearHighlightsButton
        '
        Me.TSFindClearHighlightsButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text
        Me.TSFindClearHighlightsButton.ImageTransparentColor = System.Drawing.Color.Magenta
        Me.TSFindClearHighlightsButton.Margin = New System.Windows.Forms.Padding(1, 0, 1, 0)
        Me.TSFindClearHighlightsButton.Name = "TSFindClearHighlightsButton"
        Me.TSFindClearHighlightsButton.Size = New System.Drawing.Size(96, 25)
        Me.TSFindClearHighlightsButton.Text = "Clear Highlights"
        '
        'TSFindSeparator5
        '
        Me.TSFindSeparator5.Margin = New System.Windows.Forms.Padding(5, 0, 5, 0)
        Me.TSFindSeparator5.Name = "TSFindSeparator5"
        Me.TSFindSeparator5.Size = New System.Drawing.Size(6, 25)
        '
        'ContextMenuStrip1
        '
        Me.ContextMenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.ContextMenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ContextMenuUndo, Me.ContextMenuRedo, Me.ContextMenuSeparator1, Me.ContextMenuCut, Me.ContextMenuCopy, Me.ContextMenuPaste, Me.ContextMenuSelectAll})
        Me.ContextMenuStrip1.Name = "ContextMenuStrip1"
        Me.ContextMenuStrip1.Size = New System.Drawing.Size(165, 142)
        '
        'ContextMenuUndo
        '
        Me.ContextMenuUndo.Image = CType(resources.GetObject("ContextMenuUndo.Image"), System.Drawing.Image)
        Me.ContextMenuUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuUndo.Name = "ContextMenuUndo"
        Me.ContextMenuUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.ContextMenuUndo.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuUndo.Text = "Undo"
        '
        'ContextMenuRedo
        '
        Me.ContextMenuRedo.Image = CType(resources.GetObject("ContextMenuRedo.Image"), System.Drawing.Image)
        Me.ContextMenuRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuRedo.Name = "ContextMenuRedo"
        Me.ContextMenuRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.ContextMenuRedo.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuRedo.Text = "Redo"
        '
        'ContextMenuSeparator1
        '
        Me.ContextMenuSeparator1.Name = "ContextMenuSeparator1"
        Me.ContextMenuSeparator1.Size = New System.Drawing.Size(161, 6)
        '
        'ContextMenuCut
        '
        Me.ContextMenuCut.Image = CType(resources.GetObject("ContextMenuCut.Image"), System.Drawing.Image)
        Me.ContextMenuCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCut.Name = "ContextMenuCut"
        Me.ContextMenuCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.ContextMenuCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.ContextMenuCut.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuCut.Text = "Cut"
        '
        'ContextMenuCopy
        '
        Me.ContextMenuCopy.Image = CType(resources.GetObject("ContextMenuCopy.Image"), System.Drawing.Image)
        Me.ContextMenuCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCopy.Name = "ContextMenuCopy"
        Me.ContextMenuCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.ContextMenuCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.ContextMenuCopy.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuCopy.Text = "Copy"
        '
        'ContextMenuPaste
        '
        Me.ContextMenuPaste.Image = CType(resources.GetObject("ContextMenuPaste.Image"), System.Drawing.Image)
        Me.ContextMenuPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuPaste.Name = "ContextMenuPaste"
        Me.ContextMenuPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.ContextMenuPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.ContextMenuPaste.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuPaste.Text = "Paste"
        '
        'ContextMenuSelectAll
        '
        Me.ContextMenuSelectAll.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuSelectAll.Name = "ContextMenuSelectAll"
        Me.ContextMenuSelectAll.ShortcutKeyDisplayString = "Ctrl+A"
        Me.ContextMenuSelectAll.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.ContextMenuSelectAll.Size = New System.Drawing.Size(164, 22)
        Me.ContextMenuSelectAll.Text = "Select All"
        '
        'InputFolderBrowserDialog1
        '
        Me.InputFolderBrowserDialog1.RootFolder = System.Environment.SpecialFolder.CommonDocuments
        Me.InputFolderBrowserDialog1.ShowNewFolderButton = False
        '
        'ButtonStopConversion
        '
        Me.ButtonStopConversion.Location = New System.Drawing.Point(1250, 0)
        Me.ButtonStopConversion.Name = "ButtonStopConversion"
        Me.ButtonStopConversion.Size = New System.Drawing.Size(110, 23)
        Me.ButtonStopConversion.TabIndex = 5
        Me.ButtonStopConversion.Text = "Stop Conversion"
        Me.ButtonStopConversion.UseVisualStyleBackColor = True
        Me.ButtonStopConversion.Visible = False
        '
        'LabelErrorCount
        '
        Me.LabelErrorCount.AutoSize = True
        Me.LabelErrorCount.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.LabelErrorCount.Location = New System.Drawing.Point(1463, 4)
        Me.LabelErrorCount.Name = "LabelErrorCount"
        Me.LabelErrorCount.Size = New System.Drawing.Size(110, 15)
        Me.LabelErrorCount.TabIndex = 5
        Me.LabelErrorCount.Text = "Number of Errors: 0"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.BackColor = System.Drawing.SystemColors.Control
        Me.SplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2
        Me.SplitContainer1.Location = New System.Drawing.Point(0, 49)
        Me.SplitContainer1.Name = "SplitContainer1"
        Me.SplitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionOutput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionOutput)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxFileList)
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxErrorList)
        Me.SplitContainer1.Size = New System.Drawing.Size(1923, 566)
        Me.SplitContainer1.SplitterDistance = 509
        Me.SplitContainer1.SplitterWidth = 2
        Me.SplitContainer1.TabIndex = 22
        '
        'ConversionInput
        '
        Me.ConversionInput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionInput.DetectUrls = False
        Me.ConversionInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.ConversionInput.Font = New System.Drawing.Font("Consolas", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionInput.Location = New System.Drawing.Point(0, 0)
        Me.ConversionInput.Name = "ConversionInput"
        Me.ConversionInput.ShortcutsEnabled = True
        Me.ConversionInput.Size = New System.Drawing.Size(950, 509)
        Me.ConversionInput.TabIndex = 0
        Me.ConversionInput.Text = ""
        Me.ConversionInput.WordWrap = False
        '
        'ConversionOutput
        '
        Me.ConversionOutput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionOutput.DetectUrls = False
        Me.ConversionOutput.Dock = System.Windows.Forms.DockStyle.Right
        Me.ConversionOutput.Font = New System.Drawing.Font("Consolas", 11.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionOutput.Location = New System.Drawing.Point(999, 0)
        Me.ConversionOutput.Name = "ConversionOutput"
        Me.ConversionOutput.ShortcutsEnabled = True
        Me.ConversionOutput.Size = New System.Drawing.Size(924, 509)
        Me.ConversionOutput.TabIndex = 1
        Me.ConversionOutput.Text = ""
        Me.ConversionOutput.WordWrap = False
        '
        'ListBoxFileList
        '
        Me.ListBoxFileList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxFileList.Enabled = False
        Me.ListBoxFileList.ItemHeight = 15
        Me.ListBoxFileList.Location = New System.Drawing.Point(0, 5)
        Me.ListBoxFileList.Name = "ListBoxFileList"
        Me.ListBoxFileList.Size = New System.Drawing.Size(971, 64)
        Me.ListBoxFileList.TabIndex = 0
        '
        'LineNumbersForConversionInput
        '
        Me.LineNumbersForConversionInput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionInput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.LineNumbersForConversionInput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionInput.Location = New System.Drawing.Point(0, 0)
        Me.LineNumbersForConversionInput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionInput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Name = "LineNumbersForConversionInput"
        Me.LineNumbersForConversionInput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionInput.ParentRichTextBox = Me.ConversionInput
        Me.LineNumbersForConversionInput.Size = New System.Drawing.Size(23, 491)
        Me.LineNumbersForConversionInput.TabIndex = 23
        Me.LineNumbersForConversionInput.Visible = False
        '
        'LineNumbersForConversionOutput
        '
        Me.LineNumbersForConversionOutput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionOutput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionOutput.Location = New System.Drawing.Point(977, 0)
        Me.LineNumbersForConversionOutput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionOutput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.Name = "LineNumbersForConversionOutput"
        Me.LineNumbersForConversionOutput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionOutput.ParentRichTextBox = Me.ConversionOutput
        Me.LineNumbersForConversionOutput.Size = New System.Drawing.Size(21, 491)
        Me.LineNumbersForConversionOutput.TabIndex = 22
        Me.LineNumbersForConversionOutput.Visible = False
        '
        'ListBoxFileList
        '
        Me.ListBoxFileList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxFileList.Enabled = False
        Me.ListBoxFileList.ItemHeight = 15
        Me.ListBoxFileList.Location = New System.Drawing.Point(0, 5)
        Me.ListBoxFileList.Name = "ListBoxFileList"
        Me.ListBoxFileList.Size = New System.Drawing.Size(971, 64)
        Me.ListBoxFileList.TabIndex = 0
        '
        'ListBoxErrorList
        '
        Me.ListBoxErrorList.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ListBoxErrorList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxErrorList.Enabled = False
        Me.ListBoxErrorList.ItemHeight = 15
        Me.ListBoxErrorList.Location = New System.Drawing.Point(977, 5)
        Me.ListBoxErrorList.Name = "ListBoxErrorList"
        Me.ListBoxErrorList.Size = New System.Drawing.Size(958, 64)
        Me.ListBoxErrorList.TabIndex = 1
        '
        'StatusStrip1
        '
        Me.StatusStrip1.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.StatusStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.StatusStripElapasedTimeLabel, Me.StatusStripCurrentFileName, Me.StatusStripSpacer, Me.StatusStripConversionProgressBar, Me.StatusStripConversionFileProgressLabel, Me.StatusStripUpdateAvailable})
        Me.StatusStrip1.Location = New System.Drawing.Point(0, 615)
        Me.StatusStrip1.Name = "StatusStrip1"
        Me.StatusStrip1.ShowItemToolTips = True
        Me.StatusStrip1.Size = New System.Drawing.Size(1923, 22)
        Me.StatusStrip1.TabIndex = 6
        Me.StatusStrip1.Text = "StatusStrip1"
        '
        'StatusStripElapasedTimeLabel
        '
        Me.StatusStripElapasedTimeLabel.AutoSize = False
        Me.StatusStripElapasedTimeLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripElapasedTimeLabel.Name = "StatusStripElapasedTimeLabel"
        Me.StatusStripElapasedTimeLabel.Size = New System.Drawing.Size(150, 17)
        '
        'StatusStripCurrentFileName
        '
        Me.StatusStripCurrentFileName.AutoSize = False
        Me.StatusStripCurrentFileName.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.StatusStripCurrentFileName.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripCurrentFileName.Name = "StatusStripCurrentFileName"
        Me.StatusStripCurrentFileName.Size = New System.Drawing.Size(500, 17)
        Me.StatusStripCurrentFileName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'StatusStripSpacer
        '
        Me.StatusStripSpacer.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.StatusStripSpacer.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Right
        Me.StatusStripSpacer.Name = "StatusStripSpacer"
        Me.StatusStripSpacer.Size = New System.Drawing.Size(856, 17)
        Me.StatusStripSpacer.Spring = True
        '
        'StatusStripConversionProgressBar
        '
        Me.StatusStripConversionProgressBar.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right
        Me.StatusStripConversionProgressBar.AutoSize = False
        Me.StatusStripConversionProgressBar.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.StatusStripConversionProgressBar.ForeColor = System.Drawing.Color.FromArgb(CType(CType(52, Byte), Integer), CType(CType(47, Byte), Integer), CType(CType(16, Byte), Integer))
        Me.StatusStripConversionProgressBar.Name = "StatusStripConversionProgressBar"
        Me.StatusStripConversionProgressBar.Size = New System.Drawing.Size(200, 16)
        Me.StatusStripConversionProgressBar.Step = 1
        Me.StatusStripConversionProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous
        '
        'StatusStripConversionFileProgressLabel
        '
        Me.StatusStripConversionFileProgressLabel.AutoSize = False
        Me.StatusStripConversionFileProgressLabel.BackColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(213, Byte), Integer), CType(CType(240, Byte), Integer))
        Me.StatusStripConversionFileProgressLabel.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Left
        Me.StatusStripConversionFileProgressLabel.Name = "StatusStripConversionFileProgressLabel"
        Me.StatusStripConversionFileProgressLabel.Size = New System.Drawing.Size(200, 17)
        '
        'StatusStripUpdateAvailable
        '
        Me.StatusStripUpdateAvailable.DisplayStyle = ToolStripItemDisplayStyle.Image
        Me.StatusStripUpdateAvailable.Image = CType(resources.GetObject("StatusStripUpdateAvailable.Image"), System.Drawing.Image)
        Me.StatusStripUpdateAvailable.Name = "StatusStripUpdateAvailable"
        Me.StatusStripUpdateAvailable.Size = New System.Drawing.Size(16, 17)
        Me.StatusStripUpdateAvailable.ToolTipText = "Update Available"
        Me.StatusStripUpdateAvailable.Visible = False
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'ProjectConversionInitProgressBar
        '
        Me.ProjectConversionInitProgressBar.Location = New System.Drawing.Point(385, 206)
        Me.ProjectConversionInitProgressBar.Name = "ProjectConversionInitProgressBar"
        Me.ProjectConversionInitProgressBar.Size = New System.Drawing.Size(100, 23)
        Me.ProjectConversionInitProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Marquee
        Me.ProjectConversionInitProgressBar.TabIndex = 1
        '
        'ProjectConversionInitProgressLabel
        '
        Me.ProjectConversionInitProgressLabel.AutoSize = True
        Me.ProjectConversionInitProgressLabel.Location = New System.Drawing.Point(385, 196)
        Me.ProjectConversionInitProgressLabel.Name = "ProjectConversionInitProgressLabel"
        Me.ProjectConversionInitProgressLabel.Size = New System.Drawing.Size(30, 15)
        Me.ProjectConversionInitProgressLabel.TabIndex = 1
        Me.ProjectConversionInitProgressLabel.Text = "Step"
        Me.ProjectConversionInitProgressLabel.Visible = False
        '
        'ToolTipFileList
        '
        Me.ToolTipFileList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'ToolTipErrorList
        '
        Me.ToolTipErrorList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1923, 637)
        Me.Controls.Add(Me.ProjectConversionInitProgressBar)
        Me.Controls.Add(Me.ProjectConversionInitProgressLabel)
        Me.Controls.Add(Me.LabelErrorCount)
        Me.Controls.Add(Me.ButtonStopConversion)
        Me.Controls.Add(Me.SplitContainer1)
        Me.Controls.Add(Me.TSFindToolStrip)
        Me.Controls.Add(Me.MenuStrip1)
        Me.Controls.Add(Me.StatusStrip1)
        Me.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.KeyPreview = True
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Name = "Form1"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Convert C# to Visual Basic"
        Me.MenuStrip1.ResumeLayout(False)
        Me.MenuStrip1.PerformLayout()
        Me.TSFindToolStrip.ResumeLayout(False)
        Me.TSFindToolStrip.PerformLayout()
        Me.ContextMenuStrip1.ResumeLayout(False)
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        Me.StatusStrip1.ResumeLayout(False)
        Me.StatusStrip1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents MenuStrip1 As MenuStrip
    Friend WithEvents mnuEdit As ToolStripMenuItem
    Friend WithEvents mnuEditCopy As ToolStripMenuItem
    Friend WithEvents mnuEditCut As ToolStripMenuItem
    Friend WithEvents mnuEditPaste As ToolStripMenuItem
    Friend WithEvents mnuEditRedo As ToolStripMenuItem
    Friend WithEvents mnuEditUndo As ToolStripMenuItem
    Friend WithEvents mnuFile As ToolStripMenuItem
    Friend WithEvents mnuFileSaveAs As ToolStripMenuItem
    Friend WithEvents mnuOptions As ToolStripMenuItem
    Friend WithEvents mnuOptionsAdvanced As ToolStripMenuItem
    Friend WithEvents mnuConvert As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertFolder As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertSnippet As ToolStripMenuItem
    Friend WithEvents mnuConvertSep1 As ToolStripSeparator
    Friend WithEvents mnuConvertStartFolderConvertFromLastFile As ToolStripMenuItem
    Friend WithEvents mnuHelp As ToolStripMenuItem
    Friend WithEvents mnuHelpCheckForUpdatesMenuItem As ToolStripMenuItem
    Friend WithEvents mnuHelpAboutMenuItem As ToolStripMenuItem
    Friend WithEvents mnuHelpReportIssueMenuItem As ToolStripMenuItem
    Friend WithEvents SaveFileDialog1 As SaveFileDialog
    Friend WithEvents mnuOptionsColorizeSource As ToolStripMenuItem
    Friend WithEvents mnuEditFind As ToolStripMenuItem
    Friend WithEvents mnuEditSep1 As ToolStripSeparator
    Friend WithEvents mnuEditSep2 As ToolStripSeparator
    Friend WithEvents InputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents ContextMenuStrip1 As ContextMenuStrip
    Friend WithEvents ContextMenuCopy As ToolStripMenuItem
    Friend WithEvents ContextMenuCut As ToolStripMenuItem
    Friend WithEvents ContextMenuPaste As ToolStripMenuItem
    Friend WithEvents mnuOptionsPauseConvertOnSuccess As ToolStripMenuItem
    Friend WithEvents mnuFileLabelLastFolder As ToolStripMenuItem
    Friend WithEvents ButtonStopConversion As Button
    Friend WithEvents LabelErrorCount As Label
    Friend WithEvents mnuCompile As ToolStripMenuItem
    Friend WithEvents mnuOptionsSep2 As ToolStripSeparator
    Friend WithEvents mnuOptionsSep3 As ToolStripSeparator
    Friend WithEvents SplitContainer1 As SplitContainer
    Friend WithEvents ConversionOutput As RichTextBox
    Friend WithEvents ConversionInput As RichTextBox
    Friend WithEvents ListBoxErrorList As ListBox
    Friend WithEvents LineNumbersForConversionInput As LineNumbersForRichTextBox
    Friend WithEvents LineNumbersForConversionOutput As LineNumbersForRichTextBox
    Friend WithEvents ListBoxFileList As ListBox
    Friend WithEvents mnuFileExit As ToolStripMenuItem
    Friend WithEvents mnuFileSep4 As ToolStripSeparator
    Friend WithEvents mnuFileSep1 As ToolStripSeparator
    Friend WithEvents mnuFileSaveSnippet As ToolStripMenuItem
    Friend WithEvents mnuFileLoadLastSnippet As ToolStripMenuItem
    Friend WithEvents mnuFileSep3 As ToolStripSeparator
    Friend WithEvents mnuView As ToolStripMenuItem
    Friend WithEvents mnuViewShowSourceLineNumbers As ToolStripMenuItem
    Friend WithEvents mnuViewShowDestinationLineNumbers As ToolStripMenuItem
    Friend WithEvents mnuOptionsDelayBetweenConversions As ToolStripComboBox
    Friend WithEvents mnuOptionsColorizeResult As ToolStripMenuItem
    Friend WithEvents mnuFileOpen As ToolStripMenuItem
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents mnuFileSep2 As ToolStripSeparator
    Friend WithEvents mnuFileConvertProject As ToolStripMenuItem
    Friend WithEvents mnuFileLastFolder As ToolStripMenuItem
    Friend WithEvents mnuOptionsEditIgnoreFilesWithErrorsList As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptions As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipAutoGenerated As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipBinAndObjFolders As ToolStripMenuItem
    Friend WithEvents mnuOptionsFolderConversionsOptionsSkipTestResourceFiles As ToolStripMenuItem
    Friend WithEvents mnuOptionsSep1 As ToolStripSeparator
    Friend WithEvents mnuOptionsDefaultFramework As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkCore As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFullAnyCore As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFull As ToolStripMenuItem
    Friend WithEvents mnuOptionsDefaultFrameworkFullAnyFull As ToolStripMenuItem
    Friend WithEvents mnuOptionsAddFilesToIgnoreFilesEithErrorsList As ToolStripMenuItem
    Friend WithEvents StatusStrip1 As StatusStrip
    Friend WithEvents StatusStripElapasedTimeLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripSpacer As ToolStripStatusLabel
    Friend WithEvents StatusStripCurrentFileName As ToolStripStatusLabel
    Friend WithEvents StatusStripConversionFileProgressLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripConversionProgressBar As ToolStripTextProgressBar
    Friend WithEvents StatusStripUpdateAvailable As ToolStripStatusLabel
    Friend WithEvents ProjectConversionInitProgressBar As ProgressBar
    Friend WithEvents ProjectConversionInitProgressLabel As Label
    Friend WithEvents ToolTipFileList As ToolTip
    Friend WithEvents ToolTipErrorList As ToolTip
    Friend WithEvents mnuFileLastProject As ToolStripMenuItem
    Friend WithEvents mnuFileLastSolution As ToolStripMenuItem
    Friend WithEvents TSFindToolStrip As ToolStrip
    Friend WithEvents TSFindFindWhatComboBox As ToolStripComboBox
    Friend WithEvents TSFindMatchCaseCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindMatchWholeWordCheckBox As ToolStripCheckBox
    Friend WithEvents TSFindLookInLabel As ToolStripLabel
    Friend WithEvents TSFindLookInComboBox As ToolStripComboBox
    Friend WithEvents TSFindFindPreviousButton As ToolStripButton
    Friend WithEvents TSFindFindNextButton As ToolStripButton
    Friend WithEvents TSFindSeparator1 As ToolStripSeparator
    Friend WithEvents TSFindSeparator2 As ToolStripSeparator
    Friend WithEvents TSFindSeparator3 As ToolStripSeparator
    Friend WithEvents TSFindClearHighlightsButton As ToolStripButton
    Friend WithEvents ContextMenuUndo As ToolStripMenuItem
    Friend WithEvents ContextMenuRedo As ToolStripMenuItem
    Friend WithEvents ContextMenuSeparator1 As ToolStripSeparator
    Friend WithEvents TSFindSeparator4 As ToolStripSeparator
    Friend WithEvents TSFindSeparator5 As ToolStripSeparator
    Friend WithEvents mnuEditSelectAll As ToolStripMenuItem
    Friend WithEvents ContextMenuSelectAll As ToolStripMenuItem
End Class
