<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(disposing As Boolean)
        Try
            If disposing Then
                If components IsNot Nothing Then
                    components.Dispose()
                End If
                If _cancellationTokenSource IsNot Nothing Then
                    _cancellationTokenSource.Dispose()
                End If
                If _findDiablog IsNot Nothing Then
                    _findDiablog.Dispose()
                End If
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.
    'Do not modify it using the code editor.
    '<System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form1))
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
        Me.mnuFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileOpen = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileLabelLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep3 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileConvertProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastProject = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileLastSolution = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSaveAs = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep4 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSnippetLoadLast = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSnippetSave = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuFileSep6 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuFileExit = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEdit = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditFind = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuEditUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.mnuEditCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuEditPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuCompile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvert = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvertConvertFolder = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuConvertConvertSnippet = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptions = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsColorizeResult = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsColorizeSource = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsDelayBetweenConversions = New System.Windows.Forms.ToolStripComboBox()
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsEditIgnoreFilesWithErrorsList = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSep1 = New System.Windows.Forms.ToolStripSeparator()
        Me.SkipOptionsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSkipSkipAutoGenerated = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSkipSkipBinAndObjFolders = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSkipSkipTestResourceFiles = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsPauseConvertOnSuccess = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsStartFolderConvertFromLastFile = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsSep2 = New System.Windows.Forms.ToolStripSeparator()
        Me.FrameworkToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.CoreToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.NETCOREAPPToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.NetToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.NETFRAMEWORKToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuOptionsAdvanced = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuView = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuViewShowSourceLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuViewShowDestinationLineNumbers = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelp = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelpReportIssueMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.mnuHelpAboutMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.SaveFileDialog1 = New System.Windows.Forms.SaveFileDialog()
        Me.ContextMenuStrip1 = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.ContextMenuUndo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuRedo = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuSeparator1 = New System.Windows.Forms.ToolStripSeparator()
        Me.ContextMenuCut = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuCopy = New System.Windows.Forms.ToolStripMenuItem()
        Me.ContextMenuPaste = New System.Windows.Forms.ToolStripMenuItem()
        Me.InputFolderBrowserDialog1 = New System.Windows.Forms.FolderBrowserDialog()
        Me.ButtonStopConversion = New System.Windows.Forms.Button()
        Me.LabelErrorCount = New System.Windows.Forms.Label()
        Me.SplitContainer1 = New System.Windows.Forms.SplitContainer()
        Me.ConversionInput = New System.Windows.Forms.RichTextBox()
        Me.LineNumbersForConversionInput = New LineNumbersForRichTextBox()
        Me.ConversionOutput = New AdvancedRTB()
        Me.LineNumbersForConversionOutput = New LineNumbersForRichTextBox()
        Me.ListBoxFileList = New System.Windows.Forms.ListBox()
        Me.ListBoxErrorList = New System.Windows.Forms.ListBox()
        Me.StatusStrip1 = New System.Windows.Forms.StatusStrip()
        Me.StatusStripElapasedTimeLabel = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripCurrentFileName = New System.Windows.Forms.ToolStripStatusLabel()
        Me.StatusStripSpacer = New System.Windows.Forms.ToolStripStatusLabel()
        Me.ConversionProgressBar = New System.Windows.Forms.ToolStripProgressBar()
        Me.FilesConversionProgress = New System.Windows.Forms.ToolStripStatusLabel()
        Me.OpenFileDialog1 = New System.Windows.Forms.OpenFileDialog()
        Me.ProgressBar1 = New System.Windows.Forms.ProgressBar()
        Me.LabelProgress = New System.Windows.Forms.Label()
        Me.ToolTipFileList = New System.Windows.Forms.ToolTip(Me.components)
        Me.ToolTipErrorList = New System.Windows.Forms.ToolTip(Me.components)
        Me.MenuStrip1.SuspendLayout()
        Me.ContextMenuStrip1.SuspendLayout()
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        Me.StatusStrip1.SuspendLayout()
        Me.SuspendLayout()
        '
        'MenuStrip1
        '
        Me.MenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuFile, Me.mnuEdit, Me.mnuCompile, Me.mnuConvert, Me.mnuOptions, Me.mnuView, Me.mnuHelp})
        Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Padding = New System.Windows.Forms.Padding(7, 2, 0, 2)
        Me.MenuStrip1.Size = New System.Drawing.Size(1923, 24)
        Me.MenuStrip1.TabIndex = 0
        '
        'mnuFile
        '
        Me.mnuFile.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuFileOpen, Me.mnuFileSep1, Me.mnuFileSep2, Me.mnuFileLabelLastFolder, Me.mnuFileLastFolder, Me.mnuFileSep3, Me.mnuFileConvertProject, Me.mnuFileLastProject, Me.mnuFileLastSolution, Me.mnuFileSaveAs, Me.mnuFileSep4, Me.mnuFileSnippet, Me.mnuFileSep6, Me.mnuFileExit})
        Me.mnuFile.Name = "mnuFile"
        Me.mnuFile.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuFile.Size = New System.Drawing.Size(37, 20)
        Me.mnuFile.Text = "&File"
        '
        'mnuFileOpen
        '
        Me.mnuFileOpen.Image = CType(resources.GetObject("mnuFileOpen.Image"), System.Drawing.Image)
        Me.mnuFileOpen.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileOpen.Name = "mnuFileOpen"
        Me.mnuFileOpen.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuFileOpen.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileOpen.Text = "Open File..."
        '
        'mnuFileSep1
        '
        Me.mnuFileSep1.Name = "mnuFileSep1"
        Me.mnuFileSep1.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileSep2
        '
        Me.mnuFileSep2.Name = "mnuFileSep2"
        Me.mnuFileSep2.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileLabelLastFolder
        '
        Me.mnuFileLabelLastFolder.Enabled = False
        Me.mnuFileLabelLastFolder.Name = "mnuFileLabelLastFolder"
        Me.mnuFileLabelLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLabelLastFolder.Text = "Last Folder"
        '
        'mnuFileLastFolder
        '
        Me.mnuFileLastFolder.Name = "mnuFileLastFolder"
        Me.mnuFileLastFolder.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastFolder.Visible = False
        '
        'mnuFileSep3
        '
        Me.mnuFileSep3.Name = "mnuFileSep3"
        Me.mnuFileSep3.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileConvertProject
        '
        Me.mnuFileConvertProject.Image = CType(resources.GetObject("mnuFileConvertProject.Image"), System.Drawing.Image)
        Me.mnuFileConvertProject.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileConvertProject.Name = "mnuFileConvertProject"
        Me.mnuFileConvertProject.ShortcutKeys = CType(((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Shift) _
            Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuFileConvertProject.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileConvertProject.Text = "Convert Project/Solution..."
        '
        'mnuFileLastProject
        '
        Me.mnuFileLastProject.Enabled = False
        Me.mnuFileLastProject.Name = "mnuFileLastProject"
        Me.mnuFileLastProject.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastProject.Text = "Open Last Project"
        '
        'mnuFileLastSolution
        '
        Me.mnuFileLastSolution.Enabled = False
        Me.mnuFileLastSolution.Name = "mnuFileLastSolution"
        Me.mnuFileLastSolution.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileLastSolution.Text = "Open Last Solution"
        '
        'mnuFileSaveAs
        '
        Me.mnuFileSaveAs.Enabled = False
        Me.mnuFileSaveAs.Image = CType(resources.GetObject("mnuFileSaveAs.Image"), System.Drawing.Image)
        Me.mnuFileSaveAs.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuFileSaveAs.Name = "mnuFileSaveAs"
        Me.mnuFileSaveAs.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.A), System.Windows.Forms.Keys)
        Me.mnuFileSaveAs.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileSaveAs.Text = "Save Visual Basic File &As..."
        '
        'mnuFileSep4
        '
        Me.mnuFileSep4.Name = "mnuFileSep4"
        Me.mnuFileSep4.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileSnippet
        '
        Me.mnuFileSnippet.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuFileSnippetLoadLast, Me.mnuFileSnippetSave})
        Me.mnuFileSnippet.Name = "mnuFileSnippet"
        Me.mnuFileSnippet.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileSnippet.Text = "Snippet"
        '
        'mnuFileSnippetLoadLast
        '
        Me.mnuFileSnippetLoadLast.Enabled = False
        Me.mnuFileSnippetLoadLast.Name = "mnuFileSnippetLoadLast"
        Me.mnuFileSnippetLoadLast.Size = New System.Drawing.Size(124, 22)
        Me.mnuFileSnippetLoadLast.Text = "Load Last"
        '
        'mnuFileSnippetSave
        '
        Me.mnuFileSnippetSave.Enabled = False
        Me.mnuFileSnippetSave.Name = "mnuFileSnippetSave"
        Me.mnuFileSnippetSave.Size = New System.Drawing.Size(124, 22)
        Me.mnuFileSnippetSave.Text = "Save"
        '
        'mnuFileSep6
        '
        Me.mnuFileSep6.Name = "mnuFileSep6"
        Me.mnuFileSep6.Size = New System.Drawing.Size(286, 6)
        '
        'mnuFileExit
        '
        Me.mnuFileExit.Name = "mnuFileExit"
        Me.mnuFileExit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.mnuFileExit.Size = New System.Drawing.Size(289, 22)
        Me.mnuFileExit.Text = "E&xit"
        '
        'mnuEdit
        '
        Me.mnuEdit.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuEditFind, Me.mnuEditSep1, Me.mnuEditUndo, Me.mnuEditRedo, Me.mnuEditSep2, Me.mnuEditCut, Me.mnuEditCopy, Me.mnuEditPaste})
        Me.mnuEdit.Name = "mnuEdit"
        Me.mnuEdit.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.E), System.Windows.Forms.Keys)
        Me.mnuEdit.Size = New System.Drawing.Size(39, 20)
        Me.mnuEdit.Text = "&Edit"
        '
        'mnuEditFind
        '
        Me.mnuEditFind.Image = CType(resources.GetObject("mnuEditFind.Image"), System.Drawing.Image)
        Me.mnuEditFind.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditFind.Name = "mnuEditFind"
        Me.mnuEditFind.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuEditFind.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditFind.Text = "&Find..."
        '
        'mnuEditSep1
        '
        Me.mnuEditSep1.Name = "mnuEditSep1"
        Me.mnuEditSep1.Size = New System.Drawing.Size(143, 6)
        '
        'mnuEditUndo
        '
        Me.mnuEditUndo.Image = CType(resources.GetObject("mnuEditUndo.Image"), System.Drawing.Image)
        Me.mnuEditUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditUndo.Name = "mnuEditUndo"
        Me.mnuEditUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.mnuEditUndo.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditUndo.Text = "Undo"
        '
        'mnuEditRedo
        '
        Me.mnuEditRedo.Image = CType(resources.GetObject("mnuEditRedo.Image"), System.Drawing.Image)
        Me.mnuEditRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditRedo.Name = "mnuEditRedo"
        Me.mnuEditRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.mnuEditRedo.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditRedo.Text = "Redo"
        '
        'mnuEditSep2
        '
        Me.mnuEditSep2.Name = "mnuEditSep2"
        Me.mnuEditSep2.Size = New System.Drawing.Size(143, 6)
        '
        'mnuEditCut
        '
        Me.mnuEditCut.Image = CType(resources.GetObject("mnuEditCut.Image"), System.Drawing.Image)
        Me.mnuEditCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditCut.Name = "mnuEditCut"
        Me.mnuEditCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.mnuEditCut.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditCut.Text = "Cut"
        '
        'mnuEditCopy
        '
        Me.mnuEditCopy.Image = CType(resources.GetObject("mnuEditCopy.Image"), System.Drawing.Image)
        Me.mnuEditCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditCopy.Name = "mnuEditCopy"
        Me.mnuEditCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.mnuEditCopy.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditCopy.Text = "Copy"
        '
        'mnuEditPaste
        '
        Me.mnuEditPaste.Image = CType(resources.GetObject("mnuEditPaste.Image"), System.Drawing.Image)
        Me.mnuEditPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuEditPaste.Name = "mnuEditPaste"
        Me.mnuEditPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.mnuEditPaste.Size = New System.Drawing.Size(146, 22)
        Me.mnuEditPaste.Text = "Paste"
        '
        'mnuCompile
        '
        Me.mnuCompile.Enabled = False
        Me.mnuCompile.Name = "mnuCompile"
        Me.mnuCompile.Size = New System.Drawing.Size(64, 20)
        Me.mnuCompile.Text = "Compile"
        '
        'mnuConvert
        '
        Me.mnuConvert.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuConvertConvertFolder, Me.mnuConvertConvertSnippet})
        Me.mnuConvert.Name = "mnuConvert"
        Me.mnuConvert.Size = New System.Drawing.Size(61, 20)
        Me.mnuConvert.Text = "Convert"
        '
        'mnuConvertConvertFolder
        '
        Me.mnuConvertConvertFolder.Image = CType(resources.GetObject("mnuConvertConvertFolder.Image"), System.Drawing.Image)
        Me.mnuConvertConvertFolder.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuConvertConvertFolder.Name = "mnuConvertConvertFolder"
        Me.mnuConvertConvertFolder.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.F), System.Windows.Forms.Keys)
        Me.mnuConvertConvertFolder.Size = New System.Drawing.Size(199, 22)
        Me.mnuConvertConvertFolder.Text = "Convert Folder"
        '
        'mnuConvertConvertSnippet
        '
        Me.mnuConvertConvertSnippet.Enabled = False
        Me.mnuConvertConvertSnippet.Image = CType(resources.GetObject("mnuConvertConvertSnippet.Image"), System.Drawing.Image)
        Me.mnuConvertConvertSnippet.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuConvertConvertSnippet.Name = "mnuConvertConvertSnippet"
        Me.mnuConvertConvertSnippet.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.S), System.Windows.Forms.Keys)
        Me.mnuConvertConvertSnippet.Size = New System.Drawing.Size(199, 22)
        Me.mnuConvertConvertSnippet.Text = "Convert Snippet"
        '
        'mnuOptions
        '
        Me.mnuOptions.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsColorizeResult, Me.mnuOptionsColorizeSource, Me.mnuOptionsDelayBetweenConversions, Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList, Me.mnuOptionsEditIgnoreFilesWithErrorsList, Me.mnuOptionsSep1, Me.SkipOptionsToolStripMenuItem, Me.mnuOptionsPauseConvertOnSuccess, Me.mnuOptionsStartFolderConvertFromLastFile, Me.mnuOptionsSep2, Me.FrameworkToolStripMenuItem, Me.mnuOptionsAdvanced})
        Me.mnuOptions.Name = "mnuOptions"
        Me.mnuOptions.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.O), System.Windows.Forms.Keys)
        Me.mnuOptions.Size = New System.Drawing.Size(61, 20)
        Me.mnuOptions.Text = "&Options"
        '
        'mnuOptionsColorizeResult
        '
        Me.mnuOptionsColorizeResult.CheckOnClick = True
        Me.mnuOptionsColorizeResult.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeResult.Name = "mnuOptionsColorizeResult"
        Me.mnuOptionsColorizeResult.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsColorizeResult.Text = "Colorize Result"
        '
        'mnuOptionsColorizeSource
        '
        Me.mnuOptionsColorizeSource.CheckOnClick = True
        Me.mnuOptionsColorizeSource.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsColorizeSource.Name = "mnuOptionsColorizeSource"
        Me.mnuOptionsColorizeSource.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsColorizeSource.Text = "Colorize Source"
        '
        'mnuOptionsDelayBetweenConversions
        '
        Me.mnuOptionsDelayBetweenConversions.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.mnuOptionsDelayBetweenConversions.Items.AddRange(New Object() {"Delay Between Conversions = None", "Delay Between Conversions = 5 Seconds", "Delay Between Conversions = 10 Seconds"})
        Me.mnuOptionsDelayBetweenConversions.MaxDropDownItems = 3
        Me.mnuOptionsDelayBetweenConversions.Name = "mnuOptionsDelayBetweenConversions"
        Me.mnuOptionsDelayBetweenConversions.Size = New System.Drawing.Size(300, 23)
        '
        'mnuOptionsAddFilesToIgnoreFilesEithErrorsList
        '
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image = CType(resources.GetObject("mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Image"), System.Drawing.Image)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Name = "mnuOptionsAddFilesToIgnoreFilesEithErrorsList"
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsAddFilesToIgnoreFilesEithErrorsList.Text = "Add File to the ""Ignore files with errors list"""
        '
        'mnuOptionsEditIgnoreFilesWithErrorsList
        '
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Name = "mnuOptionsEditIgnoreFilesWithErrorsList"
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsEditIgnoreFilesWithErrorsList.Text = "Show/Edit the ""Ignore files with errors"" list..."
        '
        'mnuOptionsSep1
        '
        Me.mnuOptionsSep1.Name = "mnuOptionsSep1"
        Me.mnuOptionsSep1.Size = New System.Drawing.Size(357, 6)
        '
        'SkipOptionsToolStripMenuItem
        '
        Me.SkipOptionsToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuOptionsSkipSkipAutoGenerated, Me.mnuOptionsSkipSkipBinAndObjFolders, Me.mnuOptionsSkipSkipTestResourceFiles})
        Me.SkipOptionsToolStripMenuItem.Name = "SkipOptionsToolStripMenuItem"
        Me.SkipOptionsToolStripMenuItem.Size = New System.Drawing.Size(360, 22)
        Me.SkipOptionsToolStripMenuItem.Text = "Folder Conversions Options"
        '
        'mnuOptionsSkipSkipAutoGenerated
        '
        Me.mnuOptionsSkipSkipAutoGenerated.Checked = True
        Me.mnuOptionsSkipSkipAutoGenerated.CheckOnClick = True
        Me.mnuOptionsSkipSkipAutoGenerated.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsSkipSkipAutoGenerated.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsSkipSkipAutoGenerated.Name = "mnuOptionsSkipSkipAutoGenerated"
        Me.mnuOptionsSkipSkipAutoGenerated.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsSkipSkipAutoGenerated.Text = "Skip Auto Generated"
        '
        'mnuOptionsSkipSkipBinAndObjFolders
        '
        Me.mnuOptionsSkipSkipBinAndObjFolders.Checked = True
        Me.mnuOptionsSkipSkipBinAndObjFolders.CheckOnClick = True
        Me.mnuOptionsSkipSkipBinAndObjFolders.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsSkipSkipBinAndObjFolders.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsSkipSkipBinAndObjFolders.Name = "mnuOptionsSkipSkipBinAndObjFolders"
        Me.mnuOptionsSkipSkipBinAndObjFolders.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsSkipSkipBinAndObjFolders.Text = "Skip Bin and Obj Folders"
        '
        'mnuOptionsSkipSkipTestResourceFiles
        '
        Me.mnuOptionsSkipSkipTestResourceFiles.Checked = True
        Me.mnuOptionsSkipSkipTestResourceFiles.CheckOnClick = True
        Me.mnuOptionsSkipSkipTestResourceFiles.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsSkipSkipTestResourceFiles.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsSkipSkipTestResourceFiles.Name = "mnuOptionsSkipSkipTestResourceFiles"
        Me.mnuOptionsSkipSkipTestResourceFiles.Size = New System.Drawing.Size(202, 22)
        Me.mnuOptionsSkipSkipTestResourceFiles.Text = "Skip Test/Resource Files"
        '
        'mnuOptionsPauseConvertOnSuccess
        '
        Me.mnuOptionsPauseConvertOnSuccess.CheckOnClick = True
        Me.mnuOptionsPauseConvertOnSuccess.Image = CType(resources.GetObject("mnuOptionsPauseConvertOnSuccess.Image"), System.Drawing.Image)
        Me.mnuOptionsPauseConvertOnSuccess.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsPauseConvertOnSuccess.Name = "mnuOptionsPauseConvertOnSuccess"
        Me.mnuOptionsPauseConvertOnSuccess.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsPauseConvertOnSuccess.Text = "Pause Conversion on Success"
        '
        'mnuOptionsStartFolderConvertFromLastFile
        '
        Me.mnuOptionsStartFolderConvertFromLastFile.Checked = True
        Me.mnuOptionsStartFolderConvertFromLastFile.CheckOnClick = True
        Me.mnuOptionsStartFolderConvertFromLastFile.CheckState = System.Windows.Forms.CheckState.Checked
        Me.mnuOptionsStartFolderConvertFromLastFile.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsStartFolderConvertFromLastFile.Name = "mnuOptionsStartFolderConvertFromLastFile"
        Me.mnuOptionsStartFolderConvertFromLastFile.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsStartFolderConvertFromLastFile.Text = "Start Conversion From Last File"
        '
        'mnuOptionsSep2
        '
        Me.mnuOptionsSep2.Name = "mnuOptionsSep2"
        Me.mnuOptionsSep2.Size = New System.Drawing.Size(357, 6)
        '
        'FrameworkToolStripMenuItem
        '
        Me.FrameworkToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.CoreToolStripMenuItem, Me.NetToolStripMenuItem})
        Me.FrameworkToolStripMenuItem.Name = "FrameworkToolStripMenuItem"
        Me.FrameworkToolStripMenuItem.Size = New System.Drawing.Size(360, 22)
        Me.FrameworkToolStripMenuItem.Text = "Framework"
        '
        'CoreToolStripMenuItem
        '
        Me.CoreToolStripMenuItem.Checked = True
        Me.CoreToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.CoreToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.NETCOREAPPToolStripMenuItem})
        Me.CoreToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.CoreToolStripMenuItem.Name = "CoreToolStripMenuItem"
        Me.CoreToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.CoreToolStripMenuItem.Text = ".Net Core"
        '
        'NETCOREAPPToolStripMenuItem
        '
        Me.NETCOREAPPToolStripMenuItem.Checked = True
        Me.NETCOREAPPToolStripMenuItem.CheckOnClick = True
        Me.NETCOREAPPToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked
        Me.NETCOREAPPToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.NETCOREAPPToolStripMenuItem.Name = "NETCOREAPPToolStripMenuItem"
        Me.NETCOREAPPToolStripMenuItem.Size = New System.Drawing.Size(146, 22)
        Me.NETCOREAPPToolStripMenuItem.Text = "NETCOREAPP"
        '
        'NetToolStripMenuItem
        '
        Me.NetToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.NETFRAMEWORKToolStripMenuItem})
        Me.NetToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.NetToolStripMenuItem.Name = "NetToolStripMenuItem"
        Me.NetToolStripMenuItem.Size = New System.Drawing.Size(180, 22)
        Me.NetToolStripMenuItem.Text = ".Net Full Framework"
        '
        'NETFRAMEWORKToolStripMenuItem
        '
        Me.NETFRAMEWORKToolStripMenuItem.CheckOnClick = True
        Me.NETFRAMEWORKToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.NETFRAMEWORKToolStripMenuItem.Name = "NETFRAMEWORKToolStripMenuItem"
        Me.NETFRAMEWORKToolStripMenuItem.Size = New System.Drawing.Size(167, 22)
        Me.NETFRAMEWORKToolStripMenuItem.Text = "NETFRAMEWORK"
        '
        'mnuOptionsAdvanced
        '
        Me.mnuOptionsAdvanced.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuOptionsAdvanced.Name = "mnuOptionsAdvanced"
        Me.mnuOptionsAdvanced.Size = New System.Drawing.Size(360, 22)
        Me.mnuOptionsAdvanced.Text = "Advanced Options..."
        '
        'mnuView
        '
        Me.mnuView.CheckOnClick = True
        Me.mnuView.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuViewShowSourceLineNumbers, Me.mnuViewShowDestinationLineNumbers})
        Me.mnuView.Name = "mnuView"
        Me.mnuView.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.mnuView.Size = New System.Drawing.Size(44, 20)
        Me.mnuView.Text = "&View"
        '
        'mnuViewShowSourceLineNumbers
        '
        Me.mnuViewShowSourceLineNumbers.CheckOnClick = True
        Me.mnuViewShowSourceLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuViewShowSourceLineNumbers.Name = "mnuViewShowSourceLineNumbers"
        Me.mnuViewShowSourceLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.mnuViewShowSourceLineNumbers.Text = "Show Source Line Numbers"
        '
        'mnuViewShowDestinationLineNumbers
        '
        Me.mnuViewShowDestinationLineNumbers.CheckOnClick = True
        Me.mnuViewShowDestinationLineNumbers.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuViewShowDestinationLineNumbers.Name = "mnuViewShowDestinationLineNumbers"
        Me.mnuViewShowDestinationLineNumbers.Size = New System.Drawing.Size(243, 22)
        Me.mnuViewShowDestinationLineNumbers.Text = "Show Destination Line Numbers"
        '
        'mnuHelp
        '
        Me.mnuHelp.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.mnuHelpReportIssueMenuItem, Me.mnuHelpAboutMenuItem})
        Me.mnuHelp.Name = "mnuHelp"
        Me.mnuHelp.ShortcutKeys = CType((System.Windows.Forms.Keys.Alt Or System.Windows.Forms.Keys.H), System.Windows.Forms.Keys)
        Me.mnuHelp.Size = New System.Drawing.Size(44, 20)
        Me.mnuHelp.Text = "&Help"
        '
        'mnuHelpReportIssueMenuItem
        '
        Me.mnuHelpReportIssueMenuItem.Image = CType(resources.GetObject("mnuHelpReportIssueMenuItem.Image"), System.Drawing.Image)
        Me.mnuHelpReportIssueMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.mnuHelpReportIssueMenuItem.Name = "mnuHelpReportIssueMenuItem"
        Me.mnuHelpReportIssueMenuItem.Size = New System.Drawing.Size(177, 22)
        Me.mnuHelpReportIssueMenuItem.Text = "Report A Problem..."
        '
        'mnuHelpAboutMenuItem
        '
        Me.mnuHelpAboutMenuItem.Name = "mnuHelpAboutMenuItem"
        Me.mnuHelpAboutMenuItem.Size = New System.Drawing.Size(177, 22)
        Me.mnuHelpAboutMenuItem.Text = "About"
        '
        'ContextMenuStrip1
        '
        Me.ContextMenuStrip1.ImageScalingSize = New System.Drawing.Size(36, 36)
        Me.ContextMenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.ContextMenuUndo, Me.ContextMenuRedo, Me.ContextMenuSeparator1, Me.ContextMenuCut, Me.ContextMenuCopy, Me.ContextMenuPaste})
        Me.ContextMenuStrip1.Name = "ContextMenuStrip1"
        Me.ContextMenuStrip1.Size = New System.Drawing.Size(145, 120)
        '
        'ContextMenuUndo
        '
        Me.ContextMenuUndo.Image = CType(resources.GetObject("ContextMenuUndo.Image"), System.Drawing.Image)
        Me.ContextMenuUndo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuUndo.Name = "ContextMenuUndo"
        Me.ContextMenuUndo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Z), System.Windows.Forms.Keys)
        Me.ContextMenuUndo.Size = New System.Drawing.Size(144, 22)
        Me.ContextMenuUndo.Text = "Undo"
        '
        'ContextMenuRedo
        '
        Me.ContextMenuRedo.Image = CType(resources.GetObject("ContextMenuRedo.Image"), System.Drawing.Image)
        Me.ContextMenuRedo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuRedo.Name = "ContextMenuRedo"
        Me.ContextMenuRedo.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.Y), System.Windows.Forms.Keys)
        Me.ContextMenuRedo.Size = New System.Drawing.Size(144, 22)
        Me.ContextMenuRedo.Text = "Redo"
        '
        'ContextMenuSeparator1
        '
        Me.ContextMenuSeparator1.Name = "ContextMenuSeparator1"
        Me.ContextMenuSeparator1.Size = New System.Drawing.Size(141, 6)
        '
        'ContextMenuCut
        '
        Me.ContextMenuCut.Image = CType(resources.GetObject("ContextMenuCut.Image"), System.Drawing.Image)
        Me.ContextMenuCut.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCut.Name = "ContextMenuCut"
        Me.ContextMenuCut.ShortcutKeyDisplayString = "Ctrl+X"
        Me.ContextMenuCut.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.X), System.Windows.Forms.Keys)
        Me.ContextMenuCut.Size = New System.Drawing.Size(144, 22)
        Me.ContextMenuCut.Text = "Cut"
        '
        'ContextMenuCopy
        '
        Me.ContextMenuCopy.Image = CType(resources.GetObject("ContextMenuCopy.Image"), System.Drawing.Image)
        Me.ContextMenuCopy.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuCopy.Name = "ContextMenuCopy"
        Me.ContextMenuCopy.ShortcutKeyDisplayString = "Ctrl+C"
        Me.ContextMenuCopy.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.C), System.Windows.Forms.Keys)
        Me.ContextMenuCopy.Size = New System.Drawing.Size(144, 22)
        Me.ContextMenuCopy.Text = "Copy"
        '
        'ContextMenuPaste
        '
        Me.ContextMenuPaste.Image = CType(resources.GetObject("ContextMenuPaste.Image"), System.Drawing.Image)
        Me.ContextMenuPaste.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None
        Me.ContextMenuPaste.Name = "ContextMenuPaste"
        Me.ContextMenuPaste.ShortcutKeyDisplayString = "Ctrl+V"
        Me.ContextMenuPaste.ShortcutKeys = CType((System.Windows.Forms.Keys.Control Or System.Windows.Forms.Keys.V), System.Windows.Forms.Keys)
        Me.ContextMenuPaste.Size = New System.Drawing.Size(144, 22)
        Me.ContextMenuPaste.Text = "Paste"
        '
        'InputFolderBrowserDialog1
        '
        Me.InputFolderBrowserDialog1.RootFolder = System.Environment.SpecialFolder.CommonDocuments
        Me.InputFolderBrowserDialog1.ShowNewFolderButton = False
        '
        'ButtonStopConversion
        '
        Me.ButtonStopConversion.Location = New System.Drawing.Point(1250, 0)
        Me.ButtonStopConversion.Name = "ButtonStopConversion"
        Me.ButtonStopConversion.Size = New System.Drawing.Size(110, 23)
        Me.ButtonStopConversion.TabIndex = 5
        Me.ButtonStopConversion.Text = "Stop Conversion"
        Me.ButtonStopConversion.UseVisualStyleBackColor = True
        Me.ButtonStopConversion.Visible = False
        '
        'LabelErrorCount
        '
        Me.LabelErrorCount.AutoSize = True
        Me.LabelErrorCount.Location = New System.Drawing.Point(1463, 4)
        Me.LabelErrorCount.Name = "LabelErrorCount"
        Me.LabelErrorCount.Size = New System.Drawing.Size(110, 15)
        Me.LabelErrorCount.TabIndex = 5
        Me.LabelErrorCount.Text = "Number of Errors: 0"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.BackColor = System.Drawing.SystemColors.Control
        Me.SplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel2
        Me.SplitContainer1.Location = New System.Drawing.Point(0, 24)
        Me.SplitContainer1.Name = "SplitContainer1"
        Me.SplitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionInput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.ConversionOutput)
        Me.SplitContainer1.Panel1.Controls.Add(Me.LineNumbersForConversionOutput)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxFileList)
        Me.SplitContainer1.Panel2.Controls.Add(Me.ListBoxErrorList)
        Me.SplitContainer1.Size = New System.Drawing.Size(1923, 591)
        Me.SplitContainer1.SplitterDistance = 510
        Me.SplitContainer1.SplitterWidth = 2
        Me.SplitContainer1.TabIndex = 22
        '
        'ConversionInput
        '
        Me.ConversionInput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionInput.DetectUrls = False
        Me.ConversionInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.ConversionInput.Font = New System.Drawing.Font("Segoe UI", 11.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionInput.Location = New System.Drawing.Point(23, 0)
        Me.ConversionInput.Name = "ConversionInput"
        Me.ConversionInput.Size = New System.Drawing.Size(950, 510)
        Me.ConversionInput.TabIndex = 0
        Me.ConversionInput.Text = ""
        Me.ConversionInput.WordWrap = False
        '
        'LineNumbersForConversionInput
        '
        Me.LineNumbersForConversionInput.AutoSizing = True
        Me.LineNumbersForConversionInput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionInput.BackgroundGradientBetaColor = System.Drawing.Color.LightSteelBlue
        Me.LineNumbersForConversionInput.BackgroundGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal
        Me.LineNumbersForConversionInput.BorderLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionInput.BorderLinesStyle = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbersForConversionInput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Dock = System.Windows.Forms.DockStyle.Left
        Me.LineNumbersForConversionInput.DockSide = LineNumbersForRichTextBox.LineNumberDockSides.Left
        Me.LineNumbersForConversionInput.GridLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionInput.GridLinesStyle = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbersForConversionInput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.LineNrsAlignment = System.Drawing.ContentAlignment.TopRight
        Me.LineNumbersForConversionInput.LineNrsAntiAlias = True
        Me.LineNumbersForConversionInput.LineNrsAsHexadecimal = False
        Me.LineNumbersForConversionInput.LineNrsClippedByItemRectangle = True
        Me.LineNumbersForConversionInput.LineNrsLeadingZeroes = True
        Me.LineNumbersForConversionInput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionInput.Location = New System.Drawing.Point(0, 0)
        Me.LineNumbersForConversionInput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionInput.MarginLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionInput.MarginLinesSide = LineNumbersForRichTextBox.LineNumberDockSides.Right
        Me.LineNumbersForConversionInput.MarginLinesStyle = System.Drawing.Drawing2D.DashStyle.Solid
        Me.LineNumbersForConversionInput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionInput.Name = "LineNumbersForConversionInput"
        Me.LineNumbersForConversionInput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionInput.ParentRichTextBox = Me.ConversionInput
        Me.LineNumbersForConversionInput.SeeThroughMode = False
        Me.LineNumbersForConversionInput.ShowBackgroundGradient = True
        Me.LineNumbersForConversionInput.ShowBorderLines = True
        Me.LineNumbersForConversionInput.ShowGridLines = True
        Me.LineNumbersForConversionInput.ShowLineNrs = True
        Me.LineNumbersForConversionInput.ShowMarginLines = True
        Me.LineNumbersForConversionInput.Size = New System.Drawing.Size(23, 510)
        Me.LineNumbersForConversionInput.TabIndex = 23
        Me.LineNumbersForConversionInput.Visible = False
        '
        'ConversionOutput
        '
        Me.ConversionOutput.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ConversionOutput.DetectUrls = False
        Me.ConversionOutput.Dock = System.Windows.Forms.DockStyle.Right
        Me.ConversionOutput.Font = New System.Drawing.Font("Segoe UI", 11.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.ConversionOutput.HScrollPos = 0
        Me.ConversionOutput.Location = New System.Drawing.Point(999, 0)
        Me.ConversionOutput.Name = "ConversionOutput"
        Me.ConversionOutput.Size = New System.Drawing.Size(924, 510)
        Me.ConversionOutput.TabIndex = 1
        Me.ConversionOutput.Text = ""
        Me.ConversionOutput.VScrollPos = 0
        Me.ConversionOutput.WordWrap = False
        '
        'LineNumbersForConversionOutput
        '
        Me.LineNumbersForConversionOutput.AutoSizing = True
        Me.LineNumbersForConversionOutput.BackgroundGradientAlphaColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        Me.LineNumbersForConversionOutput.BackgroundGradientBetaColor = System.Drawing.Color.LightSteelBlue
        Me.LineNumbersForConversionOutput.BackgroundGradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal
        Me.LineNumbersForConversionOutput.BorderLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionOutput.BorderLinesStyle = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbersForConversionOutput.BorderLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.DockSide = LineNumbersForRichTextBox.LineNumberDockSides.Left
        Me.LineNumbersForConversionOutput.GridLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionOutput.GridLinesStyle = System.Drawing.Drawing2D.DashStyle.Dot
        Me.LineNumbersForConversionOutput.GridLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.LineNrsAlignment = System.Drawing.ContentAlignment.TopRight
        Me.LineNumbersForConversionOutput.LineNrsAntiAlias = True
        Me.LineNumbersForConversionOutput.LineNrsAsHexadecimal = False
        Me.LineNumbersForConversionOutput.LineNrsClippedByItemRectangle = True
        Me.LineNumbersForConversionOutput.LineNrsLeadingZeroes = True
        Me.LineNumbersForConversionOutput.LineNrsOffset = New System.Drawing.Size(0, 0)
        Me.LineNumbersForConversionOutput.Location = New System.Drawing.Point(977, 0)
        Me.LineNumbersForConversionOutput.Margin = New System.Windows.Forms.Padding(0)
        Me.LineNumbersForConversionOutput.MarginLinesColor = System.Drawing.Color.SlateGray
        Me.LineNumbersForConversionOutput.MarginLinesSide = LineNumbersForRichTextBox.LineNumberDockSides.Right
        Me.LineNumbersForConversionOutput.MarginLinesStyle = System.Drawing.Drawing2D.DashStyle.Solid
        Me.LineNumbersForConversionOutput.MarginLinesThickness = 1.0!
        Me.LineNumbersForConversionOutput.Name = "LineNumbersForConversionOutput"
        Me.LineNumbersForConversionOutput.Padding = New System.Windows.Forms.Padding(0, 0, 2, 0)
        Me.LineNumbersForConversionOutput.ParentRichTextBox = Me.ConversionOutput
        Me.LineNumbersForConversionOutput.SeeThroughMode = False
        Me.LineNumbersForConversionOutput.ShowBackgroundGradient = True
        Me.LineNumbersForConversionOutput.ShowBorderLines = True
        Me.LineNumbersForConversionOutput.ShowGridLines = True
        Me.LineNumbersForConversionOutput.ShowLineNrs = True
        Me.LineNumbersForConversionOutput.ShowMarginLines = True
        Me.LineNumbersForConversionOutput.Size = New System.Drawing.Size(21, 510)
        Me.LineNumbersForConversionOutput.TabIndex = 22
        Me.LineNumbersForConversionOutput.Visible = False
        '
        'ListBoxFileList
        '
        Me.ListBoxFileList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxFileList.Enabled = False
        Me.ListBoxFileList.ItemHeight = 15
        Me.ListBoxFileList.Location = New System.Drawing.Point(0, 5)
        Me.ListBoxFileList.Name = "ListBoxFileList"
        Me.ListBoxFileList.Size = New System.Drawing.Size(973, 109)
        Me.ListBoxFileList.TabIndex = 0
        '
        'ListBoxErrorList
        '
        Me.ListBoxErrorList.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ListBoxErrorList.ContextMenuStrip = Me.ContextMenuStrip1
        Me.ListBoxErrorList.Enabled = False
        Me.ListBoxErrorList.ItemHeight = 15
        Me.ListBoxErrorList.Location = New System.Drawing.Point(977, 5)
        Me.ListBoxErrorList.Name = "ListBoxErrorList"
        Me.ListBoxErrorList.Size = New System.Drawing.Size(958, 109)
        Me.ListBoxErrorList.TabIndex = 1
        '
        'StatusStrip1
        '
        Me.StatusStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.StatusStripElapasedTimeLabel, Me.StatusStripCurrentFileName, Me.StatusStripSpacer, Me.ConversionProgressBar, Me.FilesConversionProgress})
        Me.StatusStrip1.Location = New System.Drawing.Point(0, 615)
        Me.StatusStrip1.Name = "StatusStrip1"
        Me.StatusStrip1.Size = New System.Drawing.Size(1923, 22)
        Me.StatusStrip1.TabIndex = 6
        Me.StatusStrip1.Text = "StatusStrip1"
        '
        'StatusStripElapasedTimeLabel
        '
        Me.StatusStripElapasedTimeLabel.Name = "StatusStripElapasedTimeLabel"
        Me.StatusStripElapasedTimeLabel.Size = New System.Drawing.Size(0, 17)
        '
        'StatusStripCurrentFileName
        '
        Me.StatusStripCurrentFileName.BackColor = System.Drawing.SystemColors.Menu
        Me.StatusStripCurrentFileName.Name = "StatusStripCurrentFileName"
        Me.StatusStripCurrentFileName.Size = New System.Drawing.Size(0, 17)
        Me.StatusStripCurrentFileName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        '
        'StatusStripSpacer
        '
        Me.StatusStripSpacer.BackColor = System.Drawing.SystemColors.MenuBar
        Me.StatusStripSpacer.Enabled = False
        Me.StatusStripSpacer.Name = "StatusStripSpacer"
        Me.StatusStripSpacer.Size = New System.Drawing.Size(1658, 17)
        Me.StatusStripSpacer.Spring = True
        '
        'ConversionProgressBar
        '
        Me.ConversionProgressBar.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right
        Me.ConversionProgressBar.AutoSize = False
        Me.ConversionProgressBar.ForeColor = System.Drawing.Color.LightCyan
        Me.ConversionProgressBar.Name = "ConversionProgressBar"
        Me.ConversionProgressBar.Size = New System.Drawing.Size(257, 16)
        Me.ConversionProgressBar.Step = 1
        Me.ConversionProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous
        Me.ConversionProgressBar.Visible = False
        '
        'FilesConversionProgress
        '
        Me.FilesConversionProgress.AutoSize = False
        Me.FilesConversionProgress.BackColor = System.Drawing.SystemColors.Control
        Me.FilesConversionProgress.Name = "FilesConversionProgress"
        Me.FilesConversionProgress.Size = New System.Drawing.Size(250, 17)
        '
        'OpenFileDialog1
        '
        Me.OpenFileDialog1.FileName = "OpenFileDialog1"
        '
        'ProgressBar1
        '
        Me.ProgressBar1.Location = New System.Drawing.Point(385, 206)
        Me.ProgressBar1.Name = "ProgressBar1"
        Me.ProgressBar1.Size = New System.Drawing.Size(100, 23)
        Me.ProgressBar1.Style = System.Windows.Forms.ProgressBarStyle.Marquee
        Me.ProgressBar1.TabIndex = 1
        '
        'LabelProgress
        '
        Me.LabelProgress.AutoSize = True
        Me.LabelProgress.Location = New System.Drawing.Point(385, 196)
        Me.LabelProgress.Name = "LabelProgress"
        Me.LabelProgress.Size = New System.Drawing.Size(30, 15)
        Me.LabelProgress.TabIndex = 1
        Me.LabelProgress.Text = "Step"
        Me.LabelProgress.Visible = False
        '
        'ToolTipFileList
        '
        Me.ToolTipFileList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'ToolTipErrorList
        '
        Me.ToolTipErrorList.ToolTipIcon = System.Windows.Forms.ToolTipIcon.Info
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1923, 637)
        Me.Controls.Add(Me.ProgressBar1)
        Me.Controls.Add(Me.LabelProgress)
        Me.Controls.Add(Me.LabelErrorCount)
        Me.Controls.Add(Me.ButtonStopConversion)
        Me.Controls.Add(Me.SplitContainer1)
        Me.Controls.Add(Me.MenuStrip1)
        Me.Controls.Add(Me.StatusStrip1)
        Me.Font = New System.Drawing.Font("Segoe UI", 9.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.KeyPreview = True
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Name = "Form1"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Convert C# to Visual Basic"
        Me.MenuStrip1.ResumeLayout(False)
        Me.MenuStrip1.PerformLayout()
        Me.ContextMenuStrip1.ResumeLayout(False)
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        Me.StatusStrip1.ResumeLayout(False)
        Me.StatusStrip1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents MenuStrip1 As MenuStrip
    Friend WithEvents mnuEdit As ToolStripMenuItem
    Friend WithEvents mnuEditCopy As ToolStripMenuItem
    Friend WithEvents mnuEditCut As ToolStripMenuItem
    Friend WithEvents mnuEditPaste As ToolStripMenuItem
    Friend WithEvents mnuEditRedo As ToolStripMenuItem
    Friend WithEvents mnuEditUndo As ToolStripMenuItem
    Friend WithEvents mnuFile As ToolStripMenuItem
    Friend WithEvents mnuFileSaveAs As ToolStripMenuItem
    Friend WithEvents mnuOptions As ToolStripMenuItem
    Friend WithEvents mnuOptionsAdvanced As ToolStripMenuItem
    Friend WithEvents mnuConvert As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertFolder As ToolStripMenuItem
    Friend WithEvents mnuConvertConvertSnippet As ToolStripMenuItem
    Friend WithEvents mnuHelp As ToolStripMenuItem
    Friend WithEvents mnuHelpAboutMenuItem As ToolStripMenuItem
    Friend WithEvents mnuHelpReportIssueMenuItem As ToolStripMenuItem
    Friend WithEvents SaveFileDialog1 As SaveFileDialog
    Friend WithEvents mnuOptionsColorizeSource As ToolStripMenuItem
    Friend WithEvents mnuEditFind As ToolStripMenuItem
    Friend WithEvents mnuEditSep1 As ToolStripSeparator
    Friend WithEvents mnuEditSep2 As ToolStripSeparator
    Friend WithEvents InputFolderBrowserDialog1 As FolderBrowserDialog
    Friend WithEvents ContextMenuStrip1 As ContextMenuStrip
    Friend WithEvents ContextMenuCopy As ToolStripMenuItem
    Friend WithEvents ContextMenuCut As ToolStripMenuItem
    Friend WithEvents ContextMenuPaste As ToolStripMenuItem
    Friend WithEvents mnuOptionsPauseConvertOnSuccess As ToolStripMenuItem
    Friend WithEvents mnuFileSep4 As ToolStripSeparator
    Friend WithEvents mnuFileLabelLastFolder As ToolStripMenuItem
    Friend WithEvents ButtonStopConversion As Button
    Friend WithEvents LabelErrorCount As Label
    Friend WithEvents mnuCompile As ToolStripMenuItem
    Friend WithEvents mnuOptionsSep2 As ToolStripSeparator
    Friend WithEvents SplitContainer1 As SplitContainer
    Friend WithEvents ConversionOutput As AdvancedRTB
    Friend WithEvents ConversionInput As RichTextBox
    Friend WithEvents ListBoxErrorList As ListBox
    Friend WithEvents LineNumbersForConversionInput As LineNumbersForRichTextBox
    Friend WithEvents LineNumbersForConversionOutput As LineNumbersForRichTextBox
    Friend WithEvents ListBoxFileList As ListBox
    Friend WithEvents mnuOptionsStartFolderConvertFromLastFile As ToolStripMenuItem
    Friend WithEvents mnuFileExit As ToolStripMenuItem
    Friend WithEvents mnuFileSep6 As ToolStripSeparator
    Friend WithEvents mnuFileSep1 As ToolStripSeparator
    Friend WithEvents mnuFileSnippet As ToolStripMenuItem
    Friend WithEvents mnuFileSnippetSave As ToolStripMenuItem
    Friend WithEvents mnuFileSnippetLoadLast As ToolStripMenuItem
    Friend WithEvents mnuFileSep3 As ToolStripSeparator
    Friend WithEvents mnuView As ToolStripMenuItem
    Friend WithEvents mnuViewShowSourceLineNumbers As ToolStripMenuItem
    Friend WithEvents mnuViewShowDestinationLineNumbers As ToolStripMenuItem
    Friend WithEvents mnuOptionsDelayBetweenConversions As ToolStripComboBox
    Friend WithEvents mnuOptionsColorizeResult As ToolStripMenuItem
    Friend WithEvents mnuFileOpen As ToolStripMenuItem
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents mnuFileSep2 As ToolStripSeparator
    Friend WithEvents mnuFileConvertProject As ToolStripMenuItem
    Friend WithEvents mnuFileLastFolder As ToolStripMenuItem
    Friend WithEvents mnuOptionsEditIgnoreFilesWithErrorsList As ToolStripMenuItem
    Friend WithEvents SkipOptionsToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents mnuOptionsSkipSkipAutoGenerated As ToolStripMenuItem
    Friend WithEvents mnuOptionsSkipSkipBinAndObjFolders As ToolStripMenuItem
    Friend WithEvents mnuOptionsSkipSkipTestResourceFiles As ToolStripMenuItem
    Friend WithEvents mnuOptionsSep1 As ToolStripSeparator
    Friend WithEvents FrameworkToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents CoreToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents NETCOREAPPToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents NetToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents NETFRAMEWORKToolStripMenuItem As ToolStripMenuItem
    Friend WithEvents mnuOptionsAddFilesToIgnoreFilesEithErrorsList As ToolStripMenuItem
    Friend WithEvents StatusStrip1 As StatusStrip
    Friend WithEvents StatusStripElapasedTimeLabel As ToolStripStatusLabel
    Friend WithEvents StatusStripSpacer As ToolStripStatusLabel
    Friend WithEvents StatusStripCurrentFileName As ToolStripStatusLabel
    Friend WithEvents FilesConversionProgress As ToolStripStatusLabel
    Friend WithEvents ConversionProgressBar As ToolStripProgressBar
    Friend WithEvents ProgressBar1 As ProgressBar
    Friend WithEvents LabelProgress As Label
    Friend WithEvents ToolTipFileList As ToolTip
    Friend WithEvents ToolTipErrorList As ToolTip
    Friend WithEvents mnuFileLastProject As ToolStripMenuItem
    Friend WithEvents mnuFileLastSolution As ToolStripMenuItem
    Friend WithEvents ContextMenuUndo As ToolStripMenuItem
    Friend WithEvents ContextMenuRedo As ToolStripMenuItem
    Friend WithEvents ContextMenuSeparator1 As ToolStripSeparator
End Class
