'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CSharpToVBApp.My_Project
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")>  _
    Partial Friend NotInheritable Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
        
        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ColorizeInput() As Boolean
            Get
                Return CType(Me("ColorizeInput"),Boolean)
            End Get
            Set
                Me("ColorizeInput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ColorizeOutput() As Boolean
            Get
                Return CType(Me("ColorizeOutput"),Boolean)
            End Get
            Set
                Me("ColorizeOutput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ConversionDelay() As Integer
            Get
                Return CType(Me("ConversionDelay"),Integer)
            End Get
            Set
                Me("ConversionDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultProjectDirectory() As String
            Get
                Return CType(Me("DefaultProjectDirectory"),String)
            End Get
            Set
                Me("DefaultProjectDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NETCOREAPP")>  _
        Public Property Framework() As String
            Get
                Return CType(Me("Framework"),String)
            End Get
            Set
                Me("Framework") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IgnoreFileList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("IgnoreFileList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("IgnoreFileList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastPath() As String
            Get
                Return CType(Me("LastPath"),String)
            End Get
            Set
                Me("LastPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MRU_Data() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("MRU_Data"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("MRU_Data") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PauseConvertOnSuccess() As Boolean
            Get
                Return CType(Me("PauseConvertOnSuccess"),Boolean)
            End Get
            Set
                Me("PauseConvertOnSuccess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowDestinationLineNumbers() As Boolean
            Get
                Return CType(Me("ShowDestinationLineNumbers"),Boolean)
            End Get
            Set
                Me("ShowDestinationLineNumbers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowSourceLineNumbers() As Boolean
            Get
                Return CType(Me("ShowSourceLineNumbers"),Boolean)
            End Get
            Set
                Me("ShowSourceLineNumbers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SkipAutoGenerated() As Boolean
            Get
                Return CType(Me("SkipAutoGenerated"),Boolean)
            End Get
            Set
                Me("SkipAutoGenerated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SkipBinAndObjFolders() As Boolean
            Get
                Return CType(Me("SkipBinAndObjFolders"),Boolean)
            End Get
            Set
                Me("SkipBinAndObjFolders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SkipTestResourceFiles() As Boolean
            Get
                Return CType(Me("SkipTestResourceFiles"),Boolean)
            End Get
            Set
                Me("SkipTestResourceFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartFolderConvertFromLastFile() As Boolean
            Get
                Return CType(Me("StartFolderConvertFromLastFile"),Boolean)
            End Get
            Set
                Me("StartFolderConvertFromLastFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeRequired() As Boolean
            Get
                Return CType(Me("UpgradeRequired"),Boolean)
            End Get
            Set
                Me("UpgradeRequired") = value
            End Set
        End Property
    End Class
End Namespace
