' Licensed to the .NET Foundation under one or more agreements.
' The .NET Foundation licenses this file to you under the MIT license.
' See the LICENSE file in the project root for more information.

Module ClassificationTypeNames
    Public Const DefaultValue As String = "default"
    Public Const ErrorValue As String = "error"

    Public Const Comment As String = "comment"
    Public Const ExcludedCode As String = "excluded code"
    Public Const Identifier As String = "identifier"
    Public Const Keyword As String = "keyword"
    Public Const FunctionKeyword As String = "Function"
    Public Const ControlKeyword As String = "keyword - control"
    Public Const NumericLiteral As String = "number"
    Public Const [Operator] As String = "operator"
    Public Const OperatorOverloaded As String = "operator - overloaded"
    Public Const PreprocessorKeyword As String = "preprocessor keyword"
    Public Const StringLiteral As String = "string"
    Public Const WhiteSpace As String = "whitespace"
    Public Const Text As String = "text"

    Public Const StaticSymbol As String = "static symbol"

    Public Const PreprocessorText As String = "preprocessor text"
    Public Const Punctuation As String = "punctuation"
    Public Const VerbatimStringLiteral As String = "string - verbatim"
    Public Const StringEscapeCharacter As String = "string - escape character"

    Public Const ClassName As String = "class name"
    Public Const DelegateName As String = "delegate name"
    Public Const EnumName As String = "enum name"
    Public Const InterfaceName As String = "interface name"
    Public Const ModuleName As String = "module name"
    Public Const StructName As String = "struct name"
    Public Const TypeParameterName As String = "type parameter name"

    Public Const FieldName As String = "field name"
    Public Const EnumMemberName As String = "enum member name"
    Public Const ConstantName As String = "constant name"
    Public Const LocalName As String = "local name"
    Public Const ParameterName As String = "parameter name"
    Public Const MethodName As String = "method name"
    Public Const ExtensionMethodName As String = "extension method name"
    Public Const PropertyName As String = "property name"
    Public Const EventName As String = "event name"
    Public Const NamespaceName As String = "namespace name"
    Public Const LabelName As String = "label name"

    Public Const XmlDocCommentAttributeName As String = "xml doc comment - attribute name"
    Public Const XmlDocCommentAttributeQuotes As String = "xml doc comment - attribute quotes"
    Public Const XmlDocCommentAttributeValue As String = "xml doc comment - attribute value"
    Public Const XmlDocCommentCDataSection As String = "xml doc comment - cdata section"
    Public Const XmlDocCommentComment As String = "xml doc comment - comment"
    Public Const XmlDocCommentDelimiter As String = "xml doc comment - delimiter"
    Public Const XmlDocCommentEntityReference As String = "xml doc comment - entity reference"
    Public Const XmlDocCommentName As String = "xml doc comment - name"
    Public Const XmlDocCommentProcessingInstruction As String = "xml doc comment - processing instruction"
    Public Const XmlDocCommentText As String = "xml doc comment - text"

    Public Const XmlLiteralAttributeName As String = "xml literal - attribute name"
    Public Const XmlLiteralAttributeQuotes As String = "xml literal - attribute quotes"
    Public Const XmlLiteralAttributeValue As String = "xml literal - attribute value"
    Public Const XmlLiteralCDataSection As String = "xml literal - cdata section"
    Public Const XmlLiteralComment As String = "xml literal - comment"
    Public Const XmlLiteralDelimiter As String = "xml literal - delimiter"
    Public Const XmlLiteralEmbeddedExpression As String = "xml literal - embedded expression"
    Public Const XmlLiteralEntityReference As String = "xml literal - entity reference"
    Public Const XmlLiteralName As String = "xml literal - name"
    Public Const XmlLiteralProcessingInstruction As String = "xml literal - processing instruction"
    Public Const XmlLiteralText As String = "xml literal - text"

    Public Const RegexComment As String = "regex - comment"
    Public Const RegexCharacterClass As String = "regex - character class"
    Public Const RegexAnchor As String = "regex - anchor"
    Public Const RegexQuantifier As String = "regex - quantifier"
    Public Const RegexGrouping As String = "regex - grouping"
    Public Const RegexAlternation As String = "regex - alternation"
    Public Const RegexText As String = "regex - text"
    Public Const RegexSelfEscapedCharacter As String = "regex - self escaped character"
    Public Const RegexOtherEscape As String = "regex - other escape"

End Module
