' Licensed to the .NET Foundation under one or more agreements.
' The .NET Foundation licenses this file to you under the MIT license.
' See the LICENSE file in the project root for more information.

Imports System.Collections.Immutable
Imports System.Threading
Imports Microsoft.CodeAnalysis
Imports ProgressReportLibrary

Namespace CSharpToVBConverter

    Public Class ConvertRequest

        Public Sub New(mSkipAutoGenerated As Boolean, mProgress As IProgress(Of ProgressReport), mCancelToken As CancellationToken)
            Me.Progress = mProgress
            Me.SkipAutoGenerated = mSkipAutoGenerated
            Me.CancelToken = mCancelToken
            Me.UsedStacks = New Stack(New Dictionary(Of String, SymbolTableEntry)(StringComparer.Ordinal))
            Me.ImplementedMembers = (New List(Of (type As INamedTypeSymbol, members As ImmutableArray(Of ISymbol)))).ToImmutableArray
            Me.ImplementedMembersStack = New Stack(ImmutableArray(Of (type As INamedTypeSymbol, members As ImmutableArray(Of ISymbol))).Empty)
        End Sub

        Public Property CancelToken As CancellationToken
        Public Property ImplementedMembers As ImmutableArray(Of (type As INamedTypeSymbol, members As ImmutableArray(Of ISymbol)))
        Public ReadOnly Property ImplementedMembersStack As Stack
        Public ReadOnly Property Progress As IProgress(Of ProgressReport)
        Public ReadOnly Property SkipAutoGenerated As Boolean
        Public Property SourceCode As String
        Public ReadOnly Property UsedStacks As Stack
    End Class

End Namespace
